// SPDX-License-Identifier: GPL-3.0-only
/* eslint-disable security/detect-object-injection */
/* eslint-disable jsx-a11y/label-has-associated-control */
import React, { useState, useMemo, useCallback } from 'react'
import { Rocket, Zap, Target, CheckCircle2, Circle, Download, Copy, Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import type { RoleGuideData } from './types'

const PHASE_META: Record<string, { label: string; color: string; bgClass: string }> = {
  immediate: {
    label: 'This Week',
    color: 'text-status-error',
    bgClass: 'bg-status-error/10 border-status-error/30',
  },
  '30-day': {
    label: '30 Days',
    color: 'text-status-warning',
    bgClass: 'bg-status-warning/10 border-status-warning/30',
  },
  '90-day': { label: '90 Days', color: 'text-primary', bgClass: 'bg-primary/10 border-primary/30' },
  '6-month': {
    label: '6 Months',
    color: 'text-status-success',
    bgClass: 'bg-status-success/10 border-status-success/30',
  },
}

const PHASES = ['immediate', '30-day', '90-day', '6-month'] as const

interface Props {
  data: RoleGuideData
  onComplete?: () => void
}

export const RoleHowToAct: React.FC<Props> = ({ data }) => {
  const [checkedItems, setCheckedItems] = useState<Set<string>>(new Set())
  const [quickWinsDone, setQuickWinsDone] = useState<Set<string>>(new Set())
  const [copied, setCopied] = useState(false)

  const toggleCheck = (key: string) => {
    setCheckedItems((prev) => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  const toggleQuickWin = (id: string) => {
    setQuickWinsDone((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const actionsByPhase = useMemo(() => {
    const grouped: Record<string, typeof data.actionItems> = {}
    for (const phase of PHASES) grouped[phase] = []
    for (const item of data.actionItems) {
      if (grouped[item.phase]) grouped[item.phase].push(item)
    }
    return grouped
  }, [data.actionItems])

  const totalChecklist = useMemo(() => {
    let total = 0
    for (const item of data.actionItems) total += item.checklist.length
    return total
  }, [data.actionItems])

  const completionPct =
    totalChecklist > 0 ? Math.round((checkedItems.size / totalChecklist) * 100) : 0

  const generateExport = useCallback(() => {
    const lines: string[] = [`# PQC Action Plan: ${data.roleLabel}`, '', `> ${data.tagline}`, '']

    for (const phase of PHASES) {
      const meta = PHASE_META[phase]
      const items = actionsByPhase[phase]
      if (items.length === 0) continue
      lines.push(`## ${meta.label}`, '')
      for (const item of items) {
        lines.push(`### ${item.title}`, '', item.description, '')
        for (const check of item.checklist) {
          const key = `${item.id}-${check}`
          const done = checkedItems.has(key)
          lines.push(`- [${done ? 'x' : ' '}] ${check}`)
        }
        lines.push('')
      }
    }

    if (data.quickWins.length > 0) {
      lines.push('## Quick Wins', '')
      for (const qw of data.quickWins) {
        const done = quickWinsDone.has(qw.id)
        lines.push(`- [${done ? 'x' : ' '}] **${qw.label}**: ${qw.description}`)
      }
      lines.push('')
    }

    if (data.kpiMetrics.length > 0) {
      lines.push('## Success Metrics', '')
      lines.push('| Metric | Target | Description |')
      lines.push('|--------|--------|-------------|')
      for (const kpi of data.kpiMetrics) {
        lines.push(`| ${kpi.label} | ${kpi.target} | ${kpi.description} |`)
      }
      lines.push('')
    }

    lines.push('---', `Generated by PQC Today on ${new Date().toLocaleDateString()}`)
    return lines.join('\n')
  }, [data, checkedItems, quickWinsDone, actionsByPhase])

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(generateExport())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }, [generateExport])

  const handleDownload = useCallback(() => {
    const blob = new Blob([generateExport()], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `pqc-action-plan-${data.roleId}.md`
    link.click()
    URL.revokeObjectURL(url)
  }, [generateExport, data.roleId])

  return (
    <div className="space-y-8 w-full">
      {/* Progress Bar */}
      <div className="glass-panel p-5">
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <Rocket size={18} className="text-primary" />
            Action Plan Progress
          </h3>
          <span className="text-lg font-bold text-primary">{completionPct}%</span>
        </div>
        <div className="w-full h-3 bg-muted rounded-full overflow-hidden">
          <div
            className="h-full bg-primary rounded-full transition-all duration-500"
            style={{ width: `${completionPct}%` }}
          />
        </div>
        <p className="text-xs text-muted-foreground mt-2">
          {checkedItems.size} of {totalChecklist} action items completed
        </p>
      </div>

      {/* Quick Wins */}
      {data.quickWins.length > 0 && (
        <div className="glass-panel p-6">
          <h3 className="text-lg font-semibold text-foreground mb-3 flex items-center gap-2">
            <Zap size={18} className="text-status-warning" />
            Quick Wins &mdash; Start Today
          </h3>
          <div className="space-y-2">
            {data.quickWins.map((qw) => (
              <label
                key={qw.id}
                htmlFor={`qw-${qw.id}`}
                className="flex items-start gap-3 p-3 rounded-lg border border-border hover:bg-muted/30 transition-colors cursor-pointer"
              >
                <input
                  id={`qw-${qw.id}`}
                  type="checkbox"
                  checked={quickWinsDone.has(qw.id)}
                  onChange={() => toggleQuickWin(qw.id)}
                  className="mt-0.5 h-4 w-4 rounded border-border accent-primary"
                />
                <div>
                  <span className="text-sm font-medium text-foreground">{qw.label}</span>
                  <p className="text-xs text-muted-foreground">{qw.description}</p>
                </div>
              </label>
            ))}
          </div>
        </div>
      )}

      {/* Phased Action Plan */}
      <div>
        <h3 className="text-lg font-semibold text-foreground mb-4">Phased Action Plan</h3>
        <div className="space-y-6">
          {PHASES.map((phase) => {
            const items = actionsByPhase[phase]
            const meta = PHASE_META[phase]
            if (items.length === 0) return null
            return (
              <div key={phase}>
                <div className="flex items-center gap-2 mb-3">
                  <span
                    className={`px-2.5 py-1 text-xs font-bold rounded-full border ${meta.bgClass}`}
                  >
                    {meta.label}
                  </span>
                </div>
                <div className="space-y-4 ml-1 pl-4 border-l-2 border-border">
                  {items.map((item) => {
                    const doneCount = item.checklist.filter((c) =>
                      checkedItems.has(`${item.id}-${c}`)
                    ).length
                    return (
                      <div key={item.id} className="glass-panel p-4">
                        <div className="flex items-start justify-between gap-2 mb-2">
                          <div>
                            <h4 className="text-sm font-semibold text-foreground">{item.title}</h4>
                            <p className="text-xs text-muted-foreground">{item.description}</p>
                          </div>
                          <span className="text-xs text-muted-foreground whitespace-nowrap">
                            {doneCount}/{item.checklist.length}
                          </span>
                        </div>
                        <div className="space-y-1.5 mt-3">
                          {item.checklist.map((check) => {
                            const key = `${item.id}-${check}`
                            const isDone = checkedItems.has(key)
                            return (
                              <label
                                key={key}
                                className="flex items-start gap-2.5 cursor-pointer group"
                              >
                                <span className="mt-0.5 shrink-0">
                                  {isDone ? (
                                    <CheckCircle2 size={16} className="text-status-success" />
                                  ) : (
                                    <Circle
                                      size={16}
                                      className="text-muted-foreground group-hover:text-foreground transition-colors"
                                    />
                                  )}
                                </span>
                                <input
                                  type="checkbox"
                                  checked={isDone}
                                  onChange={() => toggleCheck(key)}
                                  className="sr-only"
                                />
                                <span
                                  className={`text-sm ${isDone ? 'line-through text-muted-foreground' : 'text-foreground/90'}`}
                                >
                                  {check}
                                </span>
                              </label>
                            )
                          })}
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* KPI Metrics */}
      {data.kpiMetrics.length > 0 && (
        <div className="glass-panel p-6">
          <h3 className="text-lg font-semibold text-foreground mb-3 flex items-center gap-2">
            <Target size={18} className="text-primary" />
            Success Metrics
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {data.kpiMetrics.map((kpi) => (
              <div key={kpi.label} className="bg-muted/50 rounded-lg p-3 border border-border">
                <div className="text-xs font-bold text-primary mb-1">{kpi.label}</div>
                <div className="text-lg font-bold text-foreground">{kpi.target}</div>
                <p className="text-xs text-muted-foreground mt-1">{kpi.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Export */}
      <div className="glass-panel p-5">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div>
            <h3 className="text-sm font-semibold text-foreground">Export Your Action Plan</h3>
            <p className="text-xs text-muted-foreground">
              Download your personalized plan with all checked items preserved.
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleCopy}>
              {copied ? <Check size={14} /> : <Copy size={14} />}
              <span className="ml-1.5">{copied ? 'Copied' : 'Copy'}</span>
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownload}>
              <Download size={14} />
              <span className="ml-1.5">.md</span>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
