// SPDX-License-Identifier: GPL-3.0-only
import PptxGenJS from 'pptxgenjs'

/**
 * Convert an artifact's markdown export into a 16:9 PPTX deck.
 *
 * Parsing rules (intentionally loose — artifact builders emit consistent md):
 *   - `# Heading` → deck title slide (first occurrence)
 *   - `## Heading` → new slide, heading becomes the slide title
 *   - Body paragraphs → bullet/paragraph content on the current slide
 *   - `- item` → bullet
 *   - `**bold**` markers are stripped (PPTX inline bold not yet wired)
 *
 * Designed for executive artifacts (Board Pitch, CRQC Scenario, etc.) where
 * slides map 1:1 to H2 sections.
 */
export async function markdownToPptx(markdown: string, filename: string): Promise<void> {
  const pres = new PptxGenJS()
  pres.layout = 'LAYOUT_WIDE' // 13.333 × 7.5 inches, 16:9

  // Normalize line endings and strip trailing "*generated using*" disclaimer markers
  const lines = markdown.split(/\r?\n/)

  type Block = { title: string; body: string[] }
  let deckTitle = ''
  const slides: Block[] = []
  let current: Block | null = null

  for (const rawLine of lines) {
    const line = rawLine.trimEnd()
    if (!deckTitle && line.startsWith('# ')) {
      deckTitle = stripInline(line.slice(2))
      continue
    }
    if (line.startsWith('## ')) {
      if (current) slides.push(current)
      current = { title: stripInline(line.slice(3)), body: [] }
      continue
    }
    if (line.startsWith('---')) continue // md hr
    if (line.trim() === '') {
      if (current && current.body.length > 0) current.body.push('') // preserve paragraph breaks
      continue
    }
    if (!current) continue // content before any H2 is ignored
    current.body.push(stripInline(line))
  }
  if (current) slides.push(current)

  // ── Title slide ──
  if (deckTitle) {
    const title = pres.addSlide()
    title.background = { color: 'F8FAFC' }
    title.addText(deckTitle, {
      x: 0.5,
      y: 2.8,
      w: 12.3,
      h: 1.2,
      fontSize: 40,
      bold: true,
      color: '0F172A',
      align: 'center',
    })
    title.addText('Generated by PQC Today · Command Center', {
      x: 0.5,
      y: 4.2,
      w: 12.3,
      h: 0.5,
      fontSize: 14,
      color: '64748B',
      align: 'center',
    })
    title.addText(new Date().toLocaleDateString(undefined, { dateStyle: 'long' }), {
      x: 0.5,
      y: 4.8,
      w: 12.3,
      h: 0.4,
      fontSize: 12,
      color: '94A3B8',
      align: 'center',
    })
  }

  // ── Content slides ──
  for (const s of slides) {
    const slide = pres.addSlide()
    slide.background = { color: 'FFFFFF' }
    slide.addText(s.title, {
      x: 0.5,
      y: 0.4,
      w: 12.3,
      h: 0.7,
      fontSize: 26,
      bold: true,
      color: '0F172A',
    })
    // Divider
    slide.addShape('line', {
      x: 0.5,
      y: 1.15,
      w: 12.3,
      h: 0,
      line: { color: 'CBD5E1', width: 1 },
    })

    // Body — each non-empty line becomes a text block; bullets handled naturally.
    const bodyBlocks: { text: string; options?: PptxGenJS.TextPropsOptions }[] = []
    for (const b of s.body) {
      const trimmed = b.trim()
      if (!trimmed) continue
      if (trimmed.startsWith('- ')) {
        bodyBlocks.push({
          text: trimmed.slice(2),
          options: { bullet: { type: 'bullet' } },
        })
      } else {
        bodyBlocks.push({ text: trimmed })
      }
    }

    if (bodyBlocks.length > 0) {
      slide.addText(
        bodyBlocks.map((b) => ({ text: b.text, options: b.options })),
        {
          x: 0.5,
          y: 1.4,
          w: 12.3,
          h: 5.8,
          fontSize: 16,
          color: '334155',
          valign: 'top',
          paraSpaceAfter: 8,
        }
      )
    }

    // Footer
    slide.addText('PQC Today · Command Center', {
      x: 0.5,
      y: 7.1,
      w: 12.3,
      h: 0.3,
      fontSize: 9,
      color: '94A3B8',
      align: 'right',
    })
  }

  await pres.writeFile({ fileName: `${filename}.pptx` })
}

/** Strip minimal inline markdown (bold / italic markers) for PPTX text. */
function stripInline(s: string): string {
  return s
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/__([^_]+)__/g, '$1')
    .replace(/\*(?!\s)([^*]+?)\*/g, '$1')
    .replace(/_([^_\s][^_]*?)_/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
}
