import type { VendorRegistryEntry } from './vendorRegistry'
import testVendorCertFull from '../../../pqc-tools/embed-test-site/test-fixtures/test-vendor.crt?raw'
import testVendorCertRestricted from '../../../pqc-tools/embed-test-site/test-fixtures/test-vendor-restricted.crt?raw'
import testVendorCertCustomDesign from '../../../pqc-tools/embed-test-site/test-fixtures/test-vendor-custom-design.crt?raw'

/**
 * Dynamic preview cert — generated fresh on every ▶ Preview click by the SDK test site.
 * Stored in localStorage('pqc-dynamic-vendor') on the SAME origin as the embed app
 * (both run on localhost:5175 in dev mode via the Vite proxy).
 * kid is always 'pqc-preview'.
 */
function getDynamicVendorEntry(): VendorRegistryEntry | null {
  try {
    const raw = localStorage.getItem('pqc-dynamic-vendor')
    if (!raw) return null
    const { kid, certPem } = JSON.parse(raw) as { kid: string; certPem: string }
    if (!kid || !certPem) return null
    return {
      kid,
      vendorId: 'SDK Preview',
      vendorName: 'SDK Preview',
      certPem,
      revoked: false,
      isTest: true,
    }
  } catch {
    return null
  }
}

export const TEST_VENDOR_REGISTRY: readonly VendorRegistryEntry[] = [
  {
    kid: 'test-vendor',
    vendorId: 'Acme Corp',
    vendorName: 'Test Vendor Full',
    certPem: testVendorCertFull,
    revoked: false,
    isTest: true,
  },
  {
    kid: 'test-vendor-restricted',
    vendorId: 'Limited Corp',
    vendorName: 'Test Vendor Restricted',
    certPem: testVendorCertRestricted,
    revoked: false,
    isTest: true,
  },
  {
    kid: 'test-vendor-custom-design',
    vendorId: 'Custom Design Corp',
    vendorName: 'Test Vendor Custom Design (Full Access)',
    certPem: testVendorCertCustomDesign,
    revoked: false,
    isTest: true,
  },
]

/**
 * Lookup including the dynamic test vendor generated by the SDK test site.
 * Called by findVendor() — returns the dynamic entry if kid matches, else
 * falls through to the static TEST_VENDOR_REGISTRY.
 */
export function findTestVendor(kid: string): VendorRegistryEntry | undefined {
  const dynamic = getDynamicVendorEntry()
  if (dynamic && dynamic.kid === kid) return dynamic
  return TEST_VENDOR_REGISTRY.find((v) => v.kid === kid)
}
