// SPDX-License-Identifier: GPL-3.0-only
import { Scale, ExternalLink } from 'lucide-react'

const EFFECTIVE_DATE = 'March 22, 2026'

function Section({
  number,
  title,
  children,
}: {
  number: number
  title: string
  children: React.ReactNode
}) {
  return (
    <section className="glass-panel p-6">
      <h2 className="text-lg font-semibold text-foreground mb-4">
        {number}. {title}
      </h2>
      <div className="space-y-3 text-sm leading-relaxed text-secondary">{children}</div>
    </section>
  )
}

export function TermsView() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <Scale className="text-primary shrink-0" size={28} />
          <h1 className="text-2xl font-bold text-gradient">Terms of Service</h1>
        </div>
        <p className="text-muted-foreground text-sm">
          Legal terms governing the use of PQC Today and its embedded cryptographic software
        </p>
        <p className="text-xs text-muted-foreground mt-2">
          Effective Date: {EFFECTIVE_DATE} &middot; Last Updated: {EFFECTIVE_DATE}
        </p>
      </div>

      <div className="space-y-4">
        <Section number={1} title="Acceptance of Terms">
          <p>
            By accessing or using PQC Today (the &ldquo;Platform&rdquo;), available at{' '}
            <a
              href="https://pqctoday.github.io/pqctoday-hub/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:underline"
            >
              pqctoday.github.io/pqctoday-hub
            </a>{' '}
            and its associated GitHub repositories, you agree to be bound by these Terms of Service
            (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not access or use the
            Platform.
          </p>
        </Section>

        <Section number={2} title="License">
          <p>
            The Platform&apos;s source code is licensed under the{' '}
            <strong>GNU General Public License v3.0 (GPL-3.0-only)</strong>. The full license text
            is available in the{' '}
            <a
              href="https://github.com/pqctoday/pqctoday-hub/blob/main/LICENSE"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:underline inline-flex items-center gap-1"
            >
              LICENSE file
              <ExternalLink size={12} />
            </a>
            . Nothing in these Terms restricts rights granted under the GPL-3.0.
          </p>
        </Section>

        <Section number={3} title="Educational Purpose and Cryptographic Disclaimer">
          <p>
            The Platform is an <strong>educational and research tool</strong> for post-quantum
            cryptography (PQC). All cryptographic operations &mdash; including key generation,
            signing, verification, encryption, decryption, and key encapsulation &mdash; are
            performed <strong>client-side in your browser</strong> using WebAssembly (WASM) and are
            intended <strong>for educational and demonstration purposes only</strong>.
          </p>
          <p className="font-medium text-foreground">You must not:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              Use cryptographic keys generated by this Platform to protect production systems, real
              data, or financial transactions.
            </li>
            <li>
              Rely on this Platform as a substitute for professionally audited cryptographic
              implementations.
            </li>
            <li>
              Treat assessment results, migration recommendations, or compliance guidance as
              professional legal, security, or regulatory advice.
            </li>
          </ul>
        </Section>

        <Section number={4} title="Export Compliance and Sanctions">
          <div className="space-y-4">
            <div>
              <h3 className="font-medium text-foreground mb-1">4.1 Classification</h3>
              <p>
                The Platform embeds open-source cryptographic software classified under{' '}
                <strong>Export Control Classification Number (ECCN) 5D002</strong> pursuant to the
                U.S. Export Administration Regulations (EAR). This includes but is not limited to:
                OpenSSL, liboqs, ML-KEM (FIPS 203), ML-DSA (FIPS 204), SLH-DSA (FIPS 205), AES, RSA,
                ECDSA, ECDH, Ed25519, secp256k1, FrodoKEM, HQC, Classic McEliece, and Falcon.
              </p>
            </div>
            <div>
              <h3 className="font-medium text-foreground mb-1">4.2 License Exception</h3>
              <p>
                Distribution is authorized under{' '}
                <strong>License Exception TSU (&sect;740.13 EAR)</strong> for publicly available
                encryption source code and <strong>License Exception ENC (&sect;740.17 EAR)</strong>{' '}
                for mass-market encryption software.
              </p>
            </div>
            <div>
              <h3 className="font-medium text-foreground mb-1">4.3 Prohibited Destinations</h3>
              <p>
                You may not access, download, or use the Platform if you are located in, or a
                national or resident of, any country or territory subject to comprehensive U.S.
                sanctions, including but not limited to:
              </p>
              <ul className="list-disc pl-5 space-y-1 mt-2">
                <li>Cuba</li>
                <li>Iran</li>
                <li>North Korea (DPRK)</li>
                <li>Syria</li>
                <li>The Crimea, Donetsk, and Luhansk regions of Ukraine</li>
              </ul>
            </div>
            <div>
              <h3 className="font-medium text-foreground mb-1">4.4 Denied Parties</h3>
              <p>
                You may not access or use the Platform if you are listed on, or acting on behalf of
                any party listed on, the U.S. Bureau of Industry and Security (BIS) Entity List, the
                U.S. Treasury Department&apos;s Specially Designated Nationals (SDN) List, or any
                other applicable restricted party list.
              </p>
            </div>
            <div>
              <h3 className="font-medium text-foreground mb-1">4.5 User Responsibility</h3>
              <p>
                You are solely responsible for complying with all applicable export control and
                sanctions laws in your jurisdiction. By using the Platform, you represent and
                warrant that you are not located in a prohibited destination and are not a denied
                party.
              </p>
            </div>
          </div>
        </Section>

        <Section number={5} title="Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              Use the Platform for any unlawful purpose or in violation of any applicable laws or
              regulations.
            </li>
            <li>
              Misrepresent the Platform as your own creation or remove attribution and license
              notices.
            </li>
            <li>
              Attempt to compromise, disrupt, or interfere with the Platform&apos;s infrastructure
              or other users&apos; access.
            </li>
            <li>
              Use the Platform to develop weapons, conduct surveillance, or engage in any activity
              that violates human rights.
            </li>
            <li>
              Scrape, crawl, or harvest data from the Platform in a manner that degrades service for
              other users.
            </li>
          </ul>
        </Section>

        <Section number={6} title="No Warranty">
          <p className="uppercase font-medium text-foreground">
            The Platform is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
            warranties of any kind, express or implied, including but not limited to warranties of
            merchantability, fitness for a particular purpose, accuracy, or non-infringement.
          </p>
          <p>This is consistent with Sections 15 and 16 of the GPL-3.0 license.</p>
          <p>
            The Platform aggregates data from public sources including NIST, ETSI, IETF, BSI, ANSSI,
            ISO/IEC, and others. Content may be inaccurate, incomplete, or outdated. You should
            independently verify all information before making decisions based on it.
          </p>
        </Section>

        <Section number={7} title="Limitation of Liability">
          <p className="uppercase font-medium text-foreground">
            To the maximum extent permitted by law, the maintainers, contributors, and affiliates of
            PQC Today shall not be liable for any indirect, incidental, special, consequential, or
            punitive damages, or any loss of profits, data, or goodwill, arising from your use of or
            inability to use the Platform.
          </p>
        </Section>

        <Section number={8} title="Third-Party Content and Attribution">
          <p>
            The Platform references and aggregates content from third-party organizations including
            but not limited to:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong>NIST</strong> &mdash; National Institute of Standards and Technology
            </li>
            <li>
              <strong>ETSI</strong> &mdash; European Telecommunications Standards Institute
            </li>
            <li>
              <strong>IETF</strong> &mdash; Internet Engineering Task Force
            </li>
            <li>
              <strong>BSI</strong> &mdash; Bundesamt f&uuml;r Sicherheit in der Informationstechnik
            </li>
            <li>
              <strong>ANSSI</strong> &mdash; Agence nationale de la s&eacute;curit&eacute; des
              syst&egrave;mes d&apos;information
            </li>
            <li>
              <strong>ISO/IEC</strong> &mdash; International Organization for Standardization
            </li>
            <li>
              <strong>Common Criteria</strong> (CCRA)
            </li>
          </ul>
          <p>
            The Platform is not affiliated with, endorsed by, or sponsored by any of these
            organizations. All trademarks, service marks, and trade names are the property of their
            respective owners.
          </p>
        </Section>

        <Section number={9} title="Intellectual Property">
          <ul className="list-disc pl-5 space-y-1">
            <li>The Platform&apos;s source code is licensed under GPL-3.0.</li>
            <li>
              Original educational content, data compilations, and visualizations are copyright of
              the PQC Today maintainers.
            </li>
            <li>
              Third-party standards, specifications, and documents referenced by the Platform are
              subject to their respective licenses and copyright terms.
            </li>
          </ul>
        </Section>

        <Section number={10} title="Privacy and Analytics">
          <p>
            The Platform collects <strong>no personal data</strong>. There are no user accounts, no
            login credentials, and no server-side data processing. All cryptographic operations and
            assessments run entirely in your browser using client-side WebAssembly.
          </p>
          <p>
            We use <strong>Google Analytics 4 (GA4)</strong> to collect anonymous usage data,
            including page views and aggregated interaction events (e.g., which learning modules are
            started or completed, search queries with PII scrubbed). GA4 may set cookies on your
            device to distinguish unique visitors. No personally identifiable information is
            collected or transmitted. Analytics are disabled entirely when the Platform is accessed
            on localhost.
          </p>
          <p>
            For details on how Google processes analytics data, see{' '}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:underline inline-flex items-center gap-1"
            >
              Google&apos;s Privacy Policy
              <ExternalLink size={12} />
            </a>
            .
          </p>
          <p>
            The Platform&apos;s <strong>PQC Assistant</strong> chat feature offers two modes. When
            using <strong>Google Gemini Flash</strong>, your chat messages and page context are sent
            to Google&apos;s servers for processing. You must provide your own Google AI API key to
            use this mode. Your API key is stored locally in your browser and is never transmitted
            to PQC Today&apos;s infrastructure. Google&apos;s use of data sent via the Gemini API is
            governed by{' '}
            <a
              href="https://ai.google.dev/gemini-api/terms"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:underline inline-flex items-center gap-1"
            >
              Google&apos;s Gemini API Terms of Service
              <ExternalLink size={12} />
            </a>
            . Alternatively, you can use the <strong>Local LLM (WebLLM)</strong> mode, which runs
            the AI model entirely in your browser &mdash; no data leaves your device.
          </p>
          <p>
            Local browser storage (localStorage) is used solely to persist your learning progress
            and preferences on your device. This data never leaves your browser.
          </p>
        </Section>

        <Section number={11} title="Modifications">
          <p>
            We reserve the right to modify these Terms at any time. Changes will be indicated by
            updating the &ldquo;Last Updated&rdquo; date. Continued use of the Platform after
            changes constitutes acceptance of the modified Terms.
          </p>
        </Section>

        <Section number={12} title="Governing Law">
          <p>
            These Terms are governed by and construed in accordance with the laws of the State of
            Texas, United States, without regard to its conflict of law provisions.
          </p>
        </Section>

        <Section number={13} title="Contact">
          <p>
            For questions about these Terms, please open a discussion on{' '}
            <a
              href="https://github.com/pqctoday/pqctoday-hub/discussions"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent hover:underline inline-flex items-center gap-1"
            >
              GitHub Discussions
              <ExternalLink size={12} />
            </a>{' '}
            or contact the maintainers through the repository.
          </p>
        </Section>

        {/* Footer note */}
        <p className="text-xs text-muted-foreground text-center pt-4 pb-8">
          PQC Today is an open-source, community-driven educational platform. These Terms supplement
          &mdash; and do not replace &mdash; the rights and obligations under the GPL-3.0 license.
        </p>
      </div>
    </div>
  )
}
