// SPDX-License-Identifier: GPL-3.0-only
/**
 * simAutoRun — the director for the simulation auto-run.
 *
 * It walks the REAL phase trees and drives each GATING step to genuine completion
 * through the same store actions the player's clicks call, so the sim truly
 * progresses (phases reach their maturity bands, the run completes) rather than
 * being faked. The SAME walk is the backbone of the validation harness
 * (`simAutoRun.test.ts`): drive every gating step, assert each completes and every
 * lifecycle phase reaches the win level.
 *
 * Design facts it relies on (see the plan doc + embedContract.ts):
 *  - Completion is read from hub state via `isStepComplete` — the exact predicate
 *    the sim uses, reused here so the walk can't drift from the app.
 *  - Activity completion is keyed by artifact TYPE: one real document of a type
 *    satisfies every step of that type. The director records that real document
 *    via `addExecutiveDocument` (NOT the AI-delegation shortcut, which writes none).
 *  - `scenario` (sandbox-lab) steps are NON-gating and need a live sandbox, so the
 *    director SKIPS them; the run completes without them.
 *  - Org context is set on the reset-safe sim store — never on the user's
 *    persisted assessment / persona / Migrate selection.
 */
import { useSimulationStore } from '@/store/useSimulationStore'
import { useModuleStore } from '@/store/useModuleStore'
import { SIM_TREES, flattenTree, isGatingStep, achievedTreeLevel } from '@/simulation'
import type { TreeStep, PhaseTree, StepKind } from '@/simulation'
import { isStepComplete, type StepCompletionContext } from '../embedContract'
import { PHASE_ORDER, LIFECYCLE_PHASES, type PhaseId } from '@/data/frameworkPhases'
import { PHASE_WIN_LEVEL } from '@/data/phaseMaturity'
import { EXEC_TOUR_STAGES } from './execTourConfig'
import { demoDocFor, ORG, type DemoSector } from './demoDocs'
import { REAL_DOC_GENERATORS } from './realToolDocs'
import { ARCHITECTURES, edgeState, edgeKey } from '@/data/simArchitecture'
import { jurisdictionFor } from '@/data/jurisdiction'
import {
  distinctRunQuarters,
  documentApplicability,
  evidenceId,
  hasEvidence,
  runFingerprint,
  type EvidenceKind,
  type EvidenceOrigin,
  type EvidenceStatus,
} from '@/simulation/evidence'

/** Runtime membership check for `DemoSector` — `ORG` is keyed by every sector
 *  the demo-content system knows about, so this can't drift from the type. */
const KNOWN_SECTORS = new Set<string>(Object.keys(ORG))
function isKnownSector(sector: string): sector is DemoSector {
  return KNOWN_SECTORS.has(sector)
}

/** A handful of Command Center tools (Program Charter, Initial Scoping, Skills
 *  & Team Plan, Infra Modernization, Refresh-Cycle Alignment, Accelerated
 *  Execution Profile, Data-at-Rest Strategy) have no other presence in
 *  Learn/Simulation, so their fast-forward demo doc is generated by calling
 *  the REAL tool's own `buildMarkdown()` with sample inputs — not a
 *  hand-authored lookalike. Every other artifact type still resolves through
 *  `demoDocFor`'s authored content.
 *
 *  Exported (sim-mobile-full-play WS-2) so the phone Brief+check flow reads
 *  the EXACT same generated body this director files for the narrated
 *  auto-run — no second copy of the REAL_DOC_GENERATORS/demoDocFor fallback
 *  chain to drift from this one. */
export function docFor(type: TreeStep['artifactType'], sector: string) {
  if (!type) return undefined
  const real = REAL_DOC_GENERATORS[type]
  // An unrecognized sector (e.g. stale/corrupted persisted state) falls back
  // to 'general' rather than reaching the real generator's unguarded
  // Record<DemoSector, ...> lookups, which would otherwise produce
  // "undefinedNaN"-style garbage instead of degrading gracefully.
  if (real) return real(isKnownSector(sector) ? sector : 'general')
  return demoDocFor(type, sector)
}

/** SIM_TREES is keyed by PhaseId; centralise the typed-key read so the safe
 *  dynamic index lives behind one suppression rather than scattered call sites. */
function treeFor(phase: PhaseId): PhaseTree | undefined {
  // eslint-disable-next-line security/detect-object-injection
  return SIM_TREES[phase]
}
const hasTree = (phase: PhaseId): boolean => Boolean(treeFor(phase))

/** A live completion context read fresh from the hub stores on every call — the
 *  same six predicates the sim builds in `SimulationView`. */
export function liveCompletionContext(): StepCompletionContext {
  return {
    // W1: a learn step is satisfied by the learner's own global completion OR by
    // this run's evidence (which is where a narrated demonstration now lands).
    // The two are kept apart on purpose — the run advances, the shared
    // curriculum does not.
    isModuleComplete: (id) =>
      // eslint-disable-next-line security/detect-object-injection
      useModuleStore.getState().modules[id]?.status === 'completed' ||
      hasEvidence(useSimulationStore.getState().evidence, { resourceId: id, kind: 'learn' }),
    // W1.4: a document of the right TYPE is no longer enough on its own — it
    // must also belong to this run's world (or predate the run entirely).
    hasArtifact: (t) => {
      const sim = useSimulationStore.getState()
      const app = documentApplicability({
        type: t,
        docs: useModuleStore.getState().artifacts.executiveDocuments ?? [],
        records: sim.evidence,
        fingerprint: runFingerprint(sim.size, sim.country, sim.sector),
      })
      return app.present && app.matchesWorld
    },
    isRefVisited: (id) => useSimulationStore.getState().visitedRefs.includes(id),
    isWorkshopComplete: (id) => useSimulationStore.getState().visitedWorkshops.includes(id),
    isCatalogStepDone: (id) => useSimulationStore.getState().catalogCompleted.includes(id),
    isScenarioComplete: (id) => useSimulationStore.getState().visitedScenarios.includes(id),
    edgeDecisionCount: () => Object.keys(useSimulationStore.getState().edgeDecisions).length,
    edgeDecisionCapacity: () => architectureEdgeCapacity(),
    recurrenceCount: (type) =>
      distinctRunQuarters(useSimulationStore.getState().evidence, type).length,
  }
}

/** WS-04: total migratable edges in the run's current architecture size — the
 *  same derivation `SimulationView` uses, kept here so the auto-run's live
 *  completion context and its `completeStepGenuine` driver agree with the
 *  player's own board on what "capacity" means. */
function architectureEdgeCapacity(): number {
  const { size } = useSimulationStore.getState()
  const arch = ARCHITECTURES[size as 'small' | 'mid' | 'large' | 'global']
  return arch.edges.filter((e) => e.vulnerable && edgeState(arch, e) === 'migratable').length
}

/** The ordered, gating (non-scenario) steps of a phase, in unlock order. */
export function gatingStepsForPhase(phase: PhaseId): TreeStep[] {
  const tree = treeFor(phase)
  return tree ? flattenTree(tree).filter(isGatingStep) : []
}

/** The highest maturity band any phase's tree ships — the top of the climb. */
export const AUTO_RUN_MAX_LEVEL = 4

/** The gating steps of a single phase that belong to one maturity band (level),
 *  in unlock order. Empty when the phase's tree has no band at that level. */
export function gatingStepsForPhaseLevel(phase: PhaseId, level: number): TreeStep[] {
  const tree = treeFor(phase)
  if (!tree) return []
  const band = tree.levels.find((b) => b.level === level)
  return band ? band.activities.flatMap((a) => a.steps).filter(isGatingStep) : []
}

/** The optional deep-dive steps of a single phase that belong to one maturity
 *  band (level), in the same per-activity order `deepDive` is authored. Stamped
 *  `optional: true` (mirrors `flattenTree`'s own stamping) so any consumer that
 *  checks `step.optional` sees the same signal regardless of which function
 *  produced the step. Empty when the phase has no band at that level, or the
 *  band's activities carry no deep-dive content. */
export function deepDiveStepsForPhaseLevel(phase: PhaseId, level: number): TreeStep[] {
  const tree = treeFor(phase)
  if (!tree) return []
  const band = tree.levels.find((b) => b.level === level)
  if (!band) return []
  return band.activities.flatMap((a) => (a.deepDive ?? []).map((s) => ({ ...s, optional: true })))
}

/** The maturity level a phase has currently EARNED from live hub state. */
export function levelOfPhase(
  phase: PhaseId,
  ctx: StepCompletionContext = liveCompletionContext()
): number {
  const tree = treeFor(phase)
  return tree ? achievedTreeLevel(tree, (s) => isStepComplete(s, ctx)) : 0
}

/**
 * Genuinely complete one step via the real store action for its kind. Scenario
 * (sandbox-lab) steps are intentionally skipped — they are non-gating and require
 * a live sandbox. Returns true if an action was taken.
 */
/** File a run-scoped evidence record for a step the auto-run just performed.
 *  Provenance is explicit so the board can show a demonstration as a worked
 *  example rather than as the learner's own achievement. */
function recordStepEvidence(
  step: TreeStep,
  kind: EvidenceKind,
  resourceId: string,
  phase: PhaseId,
  origin: EvidenceOrigin,
  status: EvidenceStatus
): void {
  const sim = useSimulationStore.getState()
  const runId = `run-${sim.seed}`
  const runQuarter = `Q${sim.q} ${sim.year}`
  sim.recordEvidence({
    id: evidenceId(runId, phase, kind, resourceId, kind === 'artifact' ? runQuarter : undefined),
    runId,
    phase,
    resourceId,
    kind,
    origin,
    status,
    fingerprint: runFingerprint(sim.size, sim.country, sim.sector),
    createdAt: Date.now(),
    runQuarter,
    artifactType: step.artifactType,
  })
}

export function completeStepGenuine(
  step: TreeStep,
  sector?: string,
  opts: { phase?: PhaseId; origin?: EvidenceOrigin } = {}
): boolean {
  const sim = useSimulationStore.getState()
  const mod = useModuleStore.getState()
  const phase = opts.phase ?? sim.sel
  const origin = opts.origin ?? 'narrated-example'
  switch (step.kind) {
    case 'learn':
      if (!step.moduleId) return false
      // W1.3: a narrated demonstration is NOT the learner's own study. This used
      // to write global Learn completion (`updateModuleProgress(..., completed)`),
      // which finished modules in the shared curriculum with zero recorded time
      // and no quiz score. The run now records what actually happened — a worked
      // example was shown — and the sim's own completion context reads that.
      recordStepEvidence(step, 'learn', step.moduleId, phase, origin, 'viewed')
      return true
    case 'reference':
      if (!step.refId) return false
      sim.markRefVisited(step.refId)
      recordStepEvidence(step, 'reference', step.refId, phase, origin, 'viewed')
      return true
    case 'workshop':
      if (!step.workshopId) return false
      sim.markWorkshopVisited(step.workshopId)
      recordStepEvidence(step, 'workshop', step.workshopId, phase, origin, 'practiced')
      return true
    case 'catalog':
      if (!step.catalogId) return false
      sim.markCatalogStepDone(step.catalogId)
      recordStepEvidence(step, 'catalog', step.catalogId, phase, origin, 'practiced')
      return true
    case 'activity': {
      if (!step.artifactType) return false
      const activeSector = sector ?? useSimulationStore.getState().sector
      const doc = docFor(step.artifactType, activeSector)
      if (!doc) return false
      // Dedupe is on moduleId+type, and this always files under the
      // 'sim-autorun' moduleId — so a document the LEARNER authored (any other
      // moduleId) is never replaced by a generated example.
      mod.addExecutiveDocument({
        id: `sim-autorun-${step.artifactType}`,
        moduleId: 'sim-autorun',
        type: step.artifactType,
        title: `${doc.title} (worked example)`,
        data: doc.data,
        createdAt: Date.now(),
      })
      recordStepEvidence(step, 'artifact', step.artifactType, phase, origin, 'practiced')
      return true
    }
    case 'recurrence': {
      // W2.4: this criterion is an existing activity OPERATED AGAIN over time,
      // so it cannot be faked by filing one document. The narrated run does the
      // honest thing — it records the artifact, genuinely advances the run's
      // reporting period, and records it again. The clock really moves; the
      // evidence really lands in two distinct periods.
      if (!step.recurrenceOf) return false
      const needed = 1 + (step.recurrenceQuarters ?? 1)
      for (let i = 0; i < needed; i++) {
        const now = useSimulationStore.getState()
        recordStepEvidence(
          { ...step, artifactType: step.recurrenceOf },
          'artifact',
          step.recurrenceOf,
          phase,
          origin,
          'criterion-met'
        )
        if (i === needed - 1) break
        // Advance one reporting period, exactly as the exercise asks.
        const q = now.q === 4 ? 1 : now.q + 1
        const year = now.q === 4 ? now.year + 1 : now.year
        now.applyQuarter({ crqcShift: now.crqcShift, year, q, newEvents: [] })
      }
      return true
    }
    case 'scenario':
      // Non-gating sandbox lab — needs a live sandbox; skipped on purpose.
      return false
    case 'architecture': {
      // WS-04: decide enough migratable edges (in architecture order, so the
      // walk is deterministic) to reach this step's threshold, capped at the
      // run's actual capacity. Choice follows the run's jurisdiction stance —
      // hybrid unless the jurisdiction discourages it (end state pure) — the
      // same policy a player is taught to follow, narrated per decision by
      // the walkthrough (execTourConfig.ts).
      if (!step.minDecisions) return false
      const target = Math.min(step.minDecisions, architectureEdgeCapacity())
      const arch = ARCHITECTURES[sim.size as 'small' | 'mid' | 'large' | 'global']
      const rule = jurisdictionFor(sim.country)
      const choice: 'hybrid' | 'pure' = rule?.hybrid === 'discouraged' ? 'pure' : 'hybrid'
      const migratable = arch.edges.filter(
        (e) => e.vulnerable && edgeState(arch, e) === 'migratable'
      )
      let decided = 0
      for (const e of migratable) {
        if (Object.keys(useSimulationStore.getState().edgeDecisions).length >= target) break
        const key = edgeKey(e)
        if (useSimulationStore.getState().edgeDecisions[key]) continue
        sim.setEdgeDecision(key, choice)
        decided++
      }
      return decided > 0
    }
    default:
      return false
  }
}

export interface PhaseRunResult {
  phase: PhaseId
  /** Maturity level earned after the walk. */
  level: number
  /** Number of gating steps in the phase. */
  gating: number
  /** Number of gating steps confirmed complete. */
  completed: number
  /** Whether the phase reached the run win level. */
  cleared: boolean
}

export interface AutoRunReport {
  phases: PhaseRunResult[]
  /** True when every lifecycle phase reached the win level (the run-end ceremony). */
  runComplete: boolean
}

/** One (phase, gating step) the live player walks, in unlock order. */
export interface AutoRunQueueItem {
  phase: PhaseId
  step: TreeStep
  /** The maturity band (1..4) this step belongs to — i.e. which climb pass. */
  level: number
}

/** A deduplication key for a step based on its completion-predicate key.
 *  Steps with the same key satisfy the same completion check, so only the
 *  first occurrence in the queue needs to be shown. */
function stepDedupeKey(step: TreeStep): string | null {
  switch (step.kind) {
    case 'learn':
      return step.moduleId ? `learn:${step.moduleId}` : null
    case 'reference':
      return step.refId ? `ref:${step.refId}` : null
    case 'activity':
      return step.artifactType ? `activity:${step.artifactType}` : null
    case 'workshop':
      return step.workshopId ? `workshop:${step.workshopId}` : null
    case 'catalog':
      return step.catalogId ? `catalog:${step.catalogId}` : null
    default:
      return null
  }
}

/**
 * The live playthrough queue, ordered as a MATURITY CLIMB rather than phase-by-phase.
 *
 * Framework 2.1 is explicit that phases are NOT a clean waterfall — they overlap and
 * run concurrently, climbing maturity together ("the phase structure provides a
 * logical dependency order; the calendar comes from the roadmap"). So the queue is
 * LEVEL-MAJOR: pass 1 raises every phase to L1, pass 2 to L2 (the framework's
 * "done well enough to proceed" bar — governance in place + critical assets
 * protected), then L3 and L4. Within a pass, phases are visited in PHASE_ORDER.
 *
 * The per-phase gating order is preserved (a phase's L1 band is queued before its L2
 * band, across passes), so `achievedTreeLevel` still unlocks levels in order.
 *
 * Duplicate steps — same resource referenced from multiple phases or levels — are
 * deduplicated by their completion-predicate key (moduleId / refId / artifactType /
 * workshopId / catalogId). Only the first occurrence is kept; later appearances would
 * re-open the same page for a step that is already satisfied.
 */
export function autoRunQueue(): AutoRunQueueItem[] {
  const items: AutoRunQueueItem[] = []
  const seen = new Set<string>()
  const phases = PHASE_ORDER.filter(hasTree)
  for (let level = 1; level <= AUTO_RUN_MAX_LEVEL; level++) {
    for (const phase of phases) {
      for (const step of gatingStepsForPhaseLevel(phase, level)) {
        const key = stepDedupeKey(step)
        if (key !== null) {
          if (seen.has(key)) continue
          seen.add(key)
        }
        items.push({ phase, step, level })
      }
    }
  }
  return items
}

/**
 * Extended Migration Journey queue — same breadth-first maturity climb as
 * `autoRunQueue`, but after each phase's gating steps for a level, appends that
 * same band's deep-dive steps before moving to the next phase. Deep-dive steps
 * are still deduplicated against everything already queued (a deep-dive tool
 * that happens to share a completion key with a required step elsewhere is
 * only shown once), but they never gate — `achievedTreeLevel` only ever reads
 * `steps`, never `deepDive`, so their presence here is purely additive content,
 * not a change to what "reaching a level" means.
 */
export function autoRunDeepQueue(): AutoRunQueueItem[] {
  const items: AutoRunQueueItem[] = []
  const seen = new Set<string>()
  const phases = PHASE_ORDER.filter(hasTree)
  for (let level = 1; level <= AUTO_RUN_MAX_LEVEL; level++) {
    for (const phase of phases) {
      for (const step of [
        ...gatingStepsForPhaseLevel(phase, level),
        ...deepDiveStepsForPhaseLevel(phase, level),
      ]) {
        const key = stepDedupeKey(step)
        if (key !== null) {
          if (seen.has(key)) continue
          seen.add(key)
        }
        items.push({ phase, step, level })
      }
    }
  }
  return items
}

/**
 * Play This Phase queue — the same genuine, narrated auto-advance as
 * `autoRunQueue`/`autoRunDeepQueue`, scoped to a single phase's own bands
 * instead of climbing all 9 at once. Bands are walked in the phase's own
 * level order (already monotonic — mirrors `stepsForPhase`), so the
 * level-major invariant `autoRunQueue` relies on holds trivially here too.
 */
export function autoRunPhaseQueue(phase: PhaseId, includeDeepDive: boolean): AutoRunQueueItem[] {
  const items: AutoRunQueueItem[] = []
  const seen = new Set<string>()
  const tree = treeFor(phase)
  if (!tree) return items
  for (const band of tree.levels) {
    const steps = includeDeepDive
      ? [
          ...gatingStepsForPhaseLevel(phase, band.level),
          ...deepDiveStepsForPhaseLevel(phase, band.level),
        ]
      : gatingStepsForPhaseLevel(phase, band.level)
    for (const step of steps) {
      const key = stepDedupeKey(step)
      if (key !== null) {
        if (seen.has(key)) continue
        seen.add(key)
      }
      items.push({ phase, step, level: band.level })
    }
  }
  return items
}

/** The identifier used to match a hand-picked light-stage step (mirrors stepDedupeKey's fields). */
function stepRef(step: TreeStep): string | undefined {
  switch (step.kind) {
    case 'learn':
      return step.moduleId
    case 'reference':
      return step.refId
    case 'activity':
      return step.artifactType
    case 'workshop':
      return step.workshopId
    case 'catalog':
      return step.catalogId
    default:
      return undefined
  }
}

/**
 * The Executive Overview walkthrough queue — a phase-major SINGLE PASS through the
 * program, ordered and shaped by EXEC_TOUR_STAGES. DEEP stages contribute the activity
 * steps that generate their reveal documents (hoisted across maturity bands, since a
 * phase's artifact steps may not live at level 1 — e.g. p6 has no level-1 band); LIGHT
 * stages contribute their one hand-picked step. Every item's level is normalized to 1
 * so the walkthrough fires no maturity-pass intros (the player also empties the clock
 * plan, so the calendar stays frozen). Reveal order follows revealArtifacts.
 *
 * `includeDeepDive` (Executive Overview — Deep Dive): for each `'deep'`-depth stage
 * only, additionally appends that stage's phase's deep-dive steps across every band
 * it has (the walkthrough already normalizes level to 1, so deep-dive content is
 * hoisted the same way the deep-stage reveal steps already are). `'light'` stages are
 * unaffected — they stay a single hand-picked step either way, since they're meant to
 * stay brief regardless of depth.
 */
export function autoRunWalkthroughQueue(includeDeepDive = false): AutoRunQueueItem[] {
  const items: AutoRunQueueItem[] = []
  const seen = new Set<string>()
  for (const stage of EXEC_TOUR_STAGES) {
    const phaseSteps = gatingStepsForPhase(stage.phase)
    const steps: TreeStep[] = []
    if (stage.depth === 'deep') {
      for (const artifactType of stage.revealArtifacts ?? []) {
        const match = phaseSteps.find(
          (s) => s.kind === 'activity' && s.artifactType === artifactType
        )
        if (match) steps.push(match)
      }
      if (includeDeepDive) {
        const tree = treeFor(stage.phase)
        for (const band of tree?.levels ?? []) {
          steps.push(...deepDiveStepsForPhaseLevel(stage.phase, band.level))
        }
      }
    } else if (stage.lightStep) {
      const { kind, ref } = stage.lightStep
      const match = phaseSteps.find((s) => s.kind === kind && stepRef(s) === ref)
      if (match) steps.push(match)
    }
    for (const step of steps) {
      const key = stepDedupeKey(step)
      if (key !== null) {
        if (seen.has(key)) continue
        seen.add(key)
      }
      items.push({ phase: stage.phase, step, level: 1 })
    }
  }
  return items
}

export interface DriveOptions {
  /** Restrict the walk to these phases (default: every phase with a tree). */
  phases?: PhaseId[]
  /** Called after each step is driven — for live narration / progress. */
  onStep?: (step: TreeStep, phase: PhaseId, index: number, total: number) => void
}

/**
 * Drive the gating steps of the given phases (default: all) to genuine completion.
 * `setSel` is moved per phase so a live overlay shows the active phase; for the
 * headless validation walk this is harmless (completion is global state).
 */
export function driveAllPhases(opts: DriveOptions = {}): AutoRunReport {
  const phases = opts.phases ?? PHASE_ORDER.filter(hasTree)
  for (const phase of phases) {
    useSimulationStore.getState().setSel(phase)
    const steps = gatingStepsForPhase(phase)
    steps.forEach((step, i) => {
      completeStepGenuine(step)
      opts.onStep?.(step, phase, i, steps.length)
    })
  }

  const ctx = liveCompletionContext()
  const results: PhaseRunResult[] = PHASE_ORDER.filter(hasTree).map((phase) => {
    const gating = gatingStepsForPhase(phase)
    const completed = gating.filter((s) => isStepComplete(s, ctx)).length
    const level = levelOfPhase(phase, ctx)
    return { phase, level, gating: gating.length, completed, cleared: level >= PHASE_WIN_LEVEL }
  })
  const runComplete = LIFECYCLE_PHASES.every((p) => levelOfPhase(p, ctx) >= PHASE_WIN_LEVEL)
  return { phases: results, runComplete }
}

// ---- PLAY-modal duration estimates (simulation-unified-play-mechanism-plan) -------
//
// Weighted by step `kind`, not a flat per-step constant: a multi-step hands-on
// workshop (e.g. the PKI enrollment WASM lab) runs meaningfully longer than a
// one-click reference link, and a uniform constant would systematically
// under/over-estimate paths depending on their step-kind mix. Placeholder minutes —
// tune once real analytics on completed runs exist; `scenario` is excluded
// entirely (sandbox-gated bonus content, usually locked/skipped, not something a
// duration estimate should count against the player).
const PER_STEP_MINUTES: Partial<Record<StepKind, number>> = {
  reference: 1,
  learn: 3,
  activity: 3,
  catalog: 2,
  workshop: 5.5,
}

/** Approximate minutes to work through a set of steps, weighted by kind. Used
 *  for the PLAY modal's "~N min (approximate)" labels — never measured wall-clock
 *  time, always derived from the live tree data so it can't drift stale. */
export function estimatedMinutes(steps: TreeStep[]): number {
  return steps.reduce((sum, s) => sum + (PER_STEP_MINUTES[s.kind] ?? 2), 0)
}

/** All of one phase's steps across every level it has — required only, or
 *  required + deep-dive. Used by the Play This Phase card (no auto-run queue
 *  needed for v1, which just deep-links to the board at that phase; this is
 *  purely for the card's live duration estimate as the phase dropdown changes). */
export function stepsForPhase(phase: PhaseId, includeDeepDive: boolean): TreeStep[] {
  const tree = treeFor(phase)
  if (!tree) return []
  const steps: TreeStep[] = []
  for (const band of tree.levels) {
    steps.push(...gatingStepsForPhaseLevel(phase, band.level))
    if (includeDeepDive) steps.push(...deepDiveStepsForPhaseLevel(phase, band.level))
  }
  return steps
}
