// SPDX-License-Identifier: GPL-3.0-only
/**
 * useSimAutoRunPlayer — the LIVE guided playthrough.
 *
 * The phase BOARD is the primary view: per gating step the tool opens inline for a
 * brief peek (like a manual click), then it completes the step and RETURNS to the
 * board so every section (Phase Journey, maturity checks, Critical Assets, KPIs,
 * stats) updates in view. The program clock advances Q1 2026 → Q1 2035 across the
 * run. Before each phase a framework-anchored intro modal explains what to expect.
 * Controls: play / pause / resume / stop / speed / voice / previous + next phase.
 * Scenario (sandbox-lab) steps are excluded by the queue (non-gating).
 */
import { useCallback, useEffect, useRef, useState } from 'react'
import { useSimulationStore } from '@/store/useSimulationStore'
import type { PhaseId } from '@/data/frameworkPhases'
import type { TreeStep } from '@/simulation'
import {
  autoRunQueue,
  autoRunDeepQueue,
  autoRunWalkthroughQueue,
  autoRunIntroQueue,
  autoRunPhaseQueue,
  completeStepGenuine,
  estimatedMinutes,
  gatingStepsForPhaseLevel,
  type AutoRunQueueItem,
} from './simAutoRun'
import { PHASE_ORDER } from '@/data/frameworkPhases'
import { SIM_TREES } from '@/simulation'
import { countryNameFor, getScenario, type SimScenario } from './scenarioConfig'
import { EXEC_TOUR_REVEAL_TYPES } from './execTourConfig'
import type { ExecutiveDocumentType } from '@/services/storage/types'
import { seedDemoOrg } from './seedDemoOrg'
import { setAutoRunFill } from './autoRunFill'
import { FRAMEWORK_PHASE_INTROS } from '@/data/frameworkPhaseIntros.generated'

export type AutoRunSpeed = 'slow' | 'normal' | 'fast' | 'turbo'

/** The framework explanation for the phase the board is currently focused on —
 *  drives the persistent (non-modal) banner in the overlay and the first-encounter
 *  modal. Verbatim framework text from FRAMEWORK_PHASE_INTROS. */
export interface PhaseFocus {
  phase: PhaseId
  name: string
  summary: string
  gate: string | null
}

/** A one-time scenario-framing card shown at the very start of the run (before the
 *  first maturity pass). Years / standards are pulled LIVE from getScenario(). */
export interface ScenarioIntro {
  title: string
  summary: string
}

/** Which run the player is driving: the full maturity CLIMB (Play 0→7), the
 *  executive WALKTHROUGH (a phase-major single pass — a tour, not a win), or a
 *  single-PHASE run (Play This Phase — the same genuine auto-advance as climb,
 *  scoped to one phase's own bands). Each has a "-deep" variant (Extended
 *  Migration Journey / Executive Overview — Deep Dive / Play This Phase — Deep
 *  Dive) that additionally walks the deep-dive (optional, non-gating) content —
 *  see `simulation-unified-play-mechanism-plan-07052026.md`. */
export type RunMode =
  /** W7.1 — the ~10-minute introductory journey. Tour-family: linear, no
   *  resume, and deliberately the shortest way to find out whether any of this
   *  concerns you. */
  'intro' | 'climb' | 'climb-deep' | 'walkthrough' | 'walkthrough-deep' | 'phase' | 'phase-deep'

/** True for either walkthrough variant — the tour family (frozen clock, no
 *  resume, single linear pass), as opposed to the climb family. Exported: the
 *  board (`SimulationView.tsx`) needs the same check for its win-UI suppression
 *  and concept-peek gating, which predate the "-deep" variants and only checked
 *  `=== 'walkthrough'`. */
export const isWalkthroughMode = (m: RunMode): boolean =>
  m === 'walkthrough' || m === 'walkthrough-deep' || m === 'intro'

/** True for either Play-This-Phase variant — a single-phase run. Like
 *  walkthrough, it never participates in the shared climb resume playhead
 *  (`autoRunResumeIndex`): the queue's length/shape differs per phase, so
 *  reusing that index across modes would resume at a nonsensical position
 *  (or silently clobber an in-progress climb's saved playhead). Always starts
 *  fresh from the top of the chosen phase. */
export const isPhaseMode = (m: RunMode): boolean => m === 'phase' || m === 'phase-deep'

/** True for either "-deep" variant, regardless of family. */
const includesDeepDive = (m: RunMode): boolean =>
  m === 'climb-deep' || m === 'walkthrough-deep' || m === 'phase-deep'

/** True for a mode that reads/writes the single shared `autoRunResumeIndex`
 *  playhead — only the climb family. Walkthrough and phase runs always
 *  restart at 0 and never touch it (see `isPhaseMode`). */
const usesSharedResumeIndex = (m: RunMode): boolean => m === 'climb' || m === 'climb-deep'

export interface SimAutoRunPlayer {
  running: boolean
  paused: boolean
  done: boolean
  /** The run currently loaded — drives tour-vs-climb UI (win ceremony, dates, panels). */
  mode: RunMode
  /** In walkthrough mode, the board document just generated by a reveal step (else null). */
  reveal: ExecutiveDocumentType | null
  caption: string
  phaseLabel: string
  index: number
  total: number
  speed: AutoRunSpeed
  voiceOn: boolean
  /** Name of the speech voice in use (so the UI can show which one). */
  voiceName: string
  /** When set, the run is paused on a maturity-pass intro modal. */
  passIntro: PassIntro | null
  /** Framework explanation for the currently-focused phase — drives the persistent
   *  (always-visible) banner in the overlay. Null until the first phase is focused. */
  phaseFocus: PhaseFocus | null
  /** When set, the run is paused on a first-encounter phase intro modal (shown at
   *  most once per phase across the whole run). */
  phaseIntro: PhaseFocus | null
  /** When set, the run is paused on the one-time scenario-framing card (run start). */
  scenarioIntro: ScenarioIntro | null
  /** True when there is saved progress to RESUME — the first gating step of the run
   *  is already complete (so `start()` will pick up mid-queue rather than from the
   *  top). Reactive: flips as steps complete and back to false after a Reset clears
   *  completion. Drives the play button's "Resume" vs "PLAY ALL" label. */
  resumable: boolean
  /** The mode "▶ Resume" should pass to `start()` — the last climb-family mode
   *  that ran, so an interrupted Extended Migration Journey resumes as itself. */
  resumeMode: RunMode
  /** `phase` is required for `mode: 'phase'` / `'phase-deep'` — which phase's
   *  own queue to build and drive. Ignored for every other mode. */
  start: (opts?: { mode?: RunMode; phase?: PhaseId }) => void
  pause: () => void
  resume: () => void
  stop: () => void
  cycleSpeed: () => void
  toggleVoice: () => void
  /** Dismiss the pass-intro modal and start that pass's steps. */
  beginPass: () => void
  /** Dismiss the first-encounter phase modal and continue the run. */
  beginPhase: () => void
  /** Dismiss the one-time scenario-framing card and continue to the first pass. */
  beginScenario: () => void
  /** Jump the playhead to the start of the previous maturity pass (re-shows its intro). */
  prevPass: () => void
  /** Jump the playhead to the start of the next maturity pass (shows its intro). */
  nextPass: () => void
}

// ── Program clock — paced by the SCENARIO's maturity passes (not linear). ──────
// The four maturity passes (L1→L4) land on scenario years: governance(~2027) ·
// L2 "proceed" bar(~2029) · critical assets protected(scenario, e.g. 2031) ·
// program horizon(2035). The general-asset tracks genuinely carry the clock to 2035.
function passEndYears(scenario: SimScenario): number[] {
  const gov = scenario.governanceYear
  const critical =
    scenario.objectives.find((o) => o.id === 'critical')?.byYear ?? scenario.programEndYear
  const proceed = Math.round((gov + critical) / 2)
  return [gov, proceed, critical, scenario.programEndYear] // pass 1..4 end years
}

function yearToQuarter(frac: number): { year: number; q: number } {
  const year = Math.floor(frac)
  const q = Math.min(4, Math.max(1, Math.floor((frac - year) * 4) + 1))
  return { year, q }
}

/** A per-queue-index {year,q} plan: within each maturity pass, interpolate from the
 *  previous pass-end year to this pass-end year by progress through the pass. */
export function buildClockPlan(
  queue: AutoRunQueueItem[],
  scenario: SimScenario
): { year: number; q: number }[] {
  const ends = passEndYears(scenario)
  const startYear = scenario.programStartYear
  const first = new Map<number, number>()
  const last = new Map<number, number>()
  queue.forEach((it, i) => {
    if (!first.has(it.level)) first.set(it.level, i)
    last.set(it.level, i)
  })
  return queue.map((it, i) => {
    const lvl = it.level
    const ps = first.get(lvl) ?? 0
    const pe = last.get(lvl) ?? ps
    const span = Math.max(1, pe - ps)
    const frac = (i - ps) / span
    const prevEnd = lvl <= 1 ? startYear : (ends[lvl - 2] ?? startYear)
    const thisEnd = ends[lvl - 1] ?? scenario.programEndYear
    return yearToQuarter(prevEnd + frac * (thisEnd - prevEnd))
  })
}

// Maturity-pass (climb) metadata for the intro modal + voice-over.
const PASS_META: Record<number, { name: string; goal: string }> = {
  1: {
    name: 'Establish',
    goal: 'Stand up governance and a baseline cryptographic inventory across the whole program.',
  },
  2: {
    name: 'Protect',
    goal: 'Raise every phase to maturity level 2 — the framework’s "done well enough to proceed" bar. Governance is in place and pilots are running.',
  },
  3: {
    name: 'Scale',
    goal: 'Drive the migration: critical / high-value assets onto post-quantum cryptography, harvest-now (HNDL) first, then forge-later (TNFL).',
  },
  4: {
    name: 'Optimise',
    goal: 'Complete the migration across the general estate and make crypto-agility business-as-usual.',
  },
}

export interface PassIntro {
  level: number
  name: string
  /** The objective — what this chapter is for. */
  summary: string
  /**
   * W7.2/W7.3 — estimated effort, MEASURED from this pass's own steps with the
   * same estimator every play mode reports with, rather than an advertised
   * duration nobody checked.
   */
  effortMinutes: number
  /** W7.2 — what completing this chapter actually produces. */
  evidence: string
  /** W7.2 — a short reflection prompt, so a chapter ends by asking the learner
   *  to account for what changed rather than simply advancing. */
  reflection: string
}

export function passIntroFor(level: number, scenario: SimScenario): PassIntro {
  const meta = PASS_META[level] ?? { name: `Pass ${level}`, goal: '' }
  const crit = scenario.objectives.find((o) => o.id === 'critical')?.byYear
  const anchor =
    level === 2
      ? ` Governance in place by ${scenario.governanceYear}.`
      : level === 3 && crit
        ? ` Critical assets protected by ${crit} (${scenario.standards.HNDL}, then ${scenario.standards.TNFL}).`
        : level === 4
          ? ` Full migration complete by ${scenario.programEndYear}.`
          : ''
  // W7.2 — effort and evidence derived from the pass's REAL steps.
  const steps = PHASE_ORDER.filter((phase) => !!SIM_TREES[phase]).flatMap((phase) =>
    gatingStepsForPhaseLevel(phase, level)
  )
  const kinds = new Set(steps.map((st) => st.kind))
  const parts: string[] = []
  if (kinds.has('activity')) parts.push('documents you produce')
  if (kinds.has('learn')) parts.push('comprehension checks')
  if (kinds.has('workshop')) parts.push('hands-on practice results')
  if (kinds.has('recurrence')) parts.push('evidence of the activity operated again over time')
  if (kinds.has('reference')) parts.push('reviewed source material')
  return {
    level,
    name: `Pass ${level} — ${meta.name}`,
    summary: meta.goal + anchor,
    effortMinutes: estimatedMinutes(steps),
    evidence: parts.length ? parts.join(', ') : 'no recorded evidence',
    reflection: PASS_REFLECTION[level] ?? 'What changed in the programme during this chapter?',
  }
}

/** Test seam for the chapter metadata (W7.2). */
export const passIntroForTest = passIntroFor

/** W7.2 — one reflection per chapter. Deliberately asks the learner to ACCOUNT
 *  for a change, not to rate their confidence: a chapter that ends with "next"
 *  teaches sequence, not reasoning. */
const PASS_REFLECTION: Record<number, string> = {
  1: 'Which part of the estate turned out to be exposed in a way you would not have guessed at the start?',
  2: 'Who now owns this programme, and what did they have to accept to fund it?',
  3: 'Which asset moved up the priority order in this chapter, and what evidence moved it?',
  4: 'What would have to change in the scenario for this plan to stop being the right one?',
}

// ── Voice selection (avoid robotic novelty voices; prefer natural ones). ───────
let cachedVoice: SpeechSynthesisVoice | null = null
let voiceResolved = false

function pickVoice(): SpeechSynthesisVoice | null {
  if (typeof window === 'undefined' || !window.speechSynthesis) return null
  const voices = window.speechSynthesis.getVoices()
  if (!voices.length) return null
  const english = voices.filter((v) => /^en(-|_|$)/i.test(v.lang) || /english/i.test(v.name))
  const pool = english.length ? english : voices
  // Neural / "AI" voices first: macOS (Premium)/(Enhanced) downloads, Edge "Online
  // (Natural)", then Chrome's network-neural "Google US English"; plain local
  // voices only as a fallback.
  const prefer = [
    /\((?:Premium|Enhanced)\)/i,
    /Online \(Natural\)/i,
    /Neural/i,
    /Google US English/i,
    /Google UK English (?:Female|Male)/i,
    /Microsoft (?:Aria|Jenny|Ava|Michelle|Libby|Sonia|Emma|Guy)/i,
    /Samantha/i,
    /Ava/i,
    /Allison/i,
    /Serena/i,
  ]
  for (const re of prefer) {
    const match = pool.find((v) => re.test(v.name))
    if (match) return match
  }
  const robotic =
    /Albert|Zarvox|Fred|Bad News|Bahh|Bells|Boing|Bubbles|Cellos|Deranged|eSpeak|Trinoids|Whisper|Wobble|Organ|Jester|Superstar|Good News|Pipe|Hysterical/i
  return pool.find((v) => !robotic.test(v.name)) ?? pool[0]
}

function resolveVoice(): SpeechSynthesisVoice | null {
  if (voiceResolved) return cachedVoice
  cachedVoice = pickVoice()
  if (cachedVoice) voiceResolved = true
  return cachedVoice
}

// Hard cap on spoken length. Chrome loops/freezes on long utterances and can keep
// the OS speech daemon running after the tab closes — so we NEVER speak long text.
const MAX_SPEAK_CHARS = 200

// Phonetic fixes so the voice pronounces domain abbreviations correctly. Applied to
// SPOKEN text only — the on-screen text is unchanged. Word-boundary replacements.
const PRONUNCIATION: Array<[RegExp, string]> = [
  [/\bCBOM\b/g, 'see-bom'],
  [/\bHNDL\b/g, 'harvest-now decrypt-later'],
  [/\bTNFL\b/g, 'trust-now forge-later'],
  [/\bCRQC\b/g, 'C R Q C'],
  [/\bPQC\b/g, 'P Q C'],
  [/\bQRPM\b/g, 'Q R P M'],
  [/\bRACI\b/g, 'racey'],
  [/\bSteerCo\b/g, 'steer-co'],
  [/\bHSMs\b/g, 'H S Ms'],
  [/\bHSM\b/g, 'H S M'],
  [/\bKMS\b/g, 'K M S'],
  [/\bPKI\b/g, 'P K I'],
  [/\bCISO\b/g, 'sea-so'],
  [/\bROI\b/g, 'R O I'],
  [/\bKPIs\b/g, 'K P Is'],
  [/\bKPI\b/g, 'K P I'],
  [/\bGRC\b/g, 'G R C'],
  [/\bSOC\b/g, 'sock'],
  [/\bNIST\b/g, 'nihst'],
  [/\bCNSA\b/g, 'C N S A'],
  [/\bGDPR\b/g, 'G D P R'],
  [/\bNIS2\b/g, 'N I S two'],
  [/\bPCI DSS\b/g, 'P C I, D S S'],
  [/\bTLS\b/g, 'T L S'],
  [/\bVPN\b/g, 'V P N'],
]

function pronounce(text: string): string {
  let out = text
  for (const [re, sub] of PRONUNCIATION) out = out.replace(re, sub)
  return out
}

// Speech sequencing — a monotonic token invalidates any in-flight sequence, so
// pause/stop/navigate cleanly halt it and nothing keeps speaking.
let seqToken = 0

function stopSpeech(): void {
  seqToken++
  if (typeof window !== 'undefined' && window.speechSynthesis) window.speechSynthesis.cancel()
}

function splitSentences(text: string): string[] {
  return text
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter(Boolean)
}

/** Read a passage SENTENCE BY SENTENCE so each utterance stays short (avoids the
 *  Chrome long-utterance loop) while reading the full text. Phonetics applied per
 *  sentence; cleanly cancelled by stopSpeech() (token bump).
 *
 *  `onDone` fires EXACTLY ONCE when the sequence finishes NATURALLY (the last
 *  chunk's `next` runs with no more chunks) — it does NOT fire when the sequence is
 *  superseded/cancelled by a newer seqToken (pause/stop/navigate or a fresh
 *  speakSequence). This lets the caller pace UI transitions to the actual voice
 *  rather than a length estimate. The dropped-onend fallback also reaches `onDone`,
 *  so a sequence can never stall a caller that is waiting on it. If speech is
 *  unavailable, `onDone` is NOT called here (the caller's MAX safety timer drives
 *  advancement instead — see the modal/step effects). */
function speakSequence(chunks: string[], onDone?: () => void): void {
  if (typeof window === 'undefined' || !window.speechSynthesis || chunks.length === 0) return
  const synth = window.speechSynthesis
  synth.cancel()
  const myToken = ++seqToken
  let i = 0
  const speakNext = () => {
    if (myToken !== seqToken) return // superseded / cancelled — do NOT call onDone
    const raw = chunks.at(i)
    if (raw === undefined) {
      onDone?.() // natural completion: the last chunk finished and there are no more
      return
    }
    i++
    const spoken = pronounce(raw)
    const clipped =
      spoken.length > MAX_SPEAK_CHARS ? `${spoken.slice(0, MAX_SPEAK_CHARS)}…` : spoken
    const utterance = new SpeechSynthesisUtterance(clipped)
    const voice = resolveVoice()
    if (voice) utterance.voice = voice
    utterance.rate = 0.9
    utterance.pitch = 1.0
    let fired = false
    const next = () => {
      if (fired || myToken !== seqToken) return
      fired = true
      speakNext()
    }
    utterance.onend = next
    utterance.onerror = next
    synth.speak(utterance)
    // Fallback so a dropped onend never stalls the sequence (or its onDone).
    setTimeout(next, clipped.length * 95 + 2500)
  }
  speakNext()
}

// Intro-modal hold bounds. The modal now advances WHEN ITS NARRATION FINISHES, not
// on a length estimate — so the voice-over and the on-screen transition stay in
// sync. MIN keeps a very short line on screen long enough to register; MAX is a
// safety cap in case the browser drops the final onend; OFF is the fixed hold when
// there's nothing to narrate (voice off, turbo phase modal, or no speech engine).
const MODAL_MIN_HOLD_MS = 4000 // pause after an intro's narration ends, before advancing
const MODAL_MAX_HOLD_MS = 22000
const MODAL_OFF_HOLD_MS = 6000

// Per-step announcement pacing. A step's brief "resource name" voice should finish
// before the next step starts; the step never advances before the existing dwell
// floor (lookMs — the MIN) and never waits past STEP_VOICE_MAX_MS (the MAX, so a
// dropped onend can't stall the run).
const STEP_VOICE_MAX_MS = 6000

/** Generous upper bound on how long narrating `text` can take (~130ms/char at the
 *  slowed rate, incl. dropped-onend per-sentence fallbacks), floored at `floor`.
 *  Used as the speech-safety cap so it can NEVER fire before the voice finishes —
 *  it only fires if speech never completes at all. Without this, a fixed cap (22s)
 *  cut every phase whose summary runs longer than the cap (most are 23–42s). */
function voiceSafetyMs(text: string, floor: number): number {
  return Math.max(floor, Math.round(text.length * 130) + 5000)
}

/** Time to LOOK at the step's output on the board after it completes. */
function lookMs(speed: AutoRunSpeed): number {
  return speed === 'turbo' ? 600 : speed === 'slow' ? 4500 : speed === 'fast' ? 1800 : 3200
}

function phaseLabel(phase: PhaseId): string {
  if (phase === 'foundations') return 'Foundations'
  if (phase === 'verify-close') return 'Verify & Close'
  return `Phase ${phase.slice(1)}`
}

/** The framework explanation for a phase — name + "what to expect" summary + exit
 *  gate, verbatim from FRAMEWORK_PHASE_INTROS (the framework SoT). Used for both the
 *  persistent banner and the first-encounter modal. */
function phaseFocusFor(phase: PhaseId): PhaseFocus {
  // eslint-disable-next-line security/detect-object-injection
  const intro = FRAMEWORK_PHASE_INTROS[phase]
  return {
    phase,
    name: intro?.name ?? phaseLabel(phase),
    summary: intro?.summary ?? '',
    gate: intro?.gate ?? null,
  }
}

/** Build the one-time scenario-framing card from LIVE scenario dates / standards.
 *  US → the June-2026 federal PQC executive order (EO 14412); other countries
 *  degrade to a generic country framing anchored to the same scenario
 *  milestones. */
function scenarioIntroFor(scenario: SimScenario): ScenarioIntro {
  const hndl = scenario.tracks.find((t) => t.id === 'hndl-critical')?.year
  const tnfl = scenario.tracks.find((t) => t.id === 'tnfl-critical')?.year
  if (scenario.countryCode === 'US') {
    return {
      title: 'United States — federal PQC executive order',
      summary:
        `United States — the June 2026 executive order "Securing the Nation Against Advanced ` +
        `Cryptographic Attacks". Two hard deadlines map to the framework's two-track model: key ` +
        `establishment (${scenario.standards.HNDL}) by ${hndl} for harvest-now / HNDL data, and ` +
        `digital signatures (${scenario.standards.TNFL}) by ${tnfl}. A 30-day deadline to name a PQC ` +
        `lead. General-estate assets trail to the ${scenario.programEndYear} program horizon. Watch ` +
        `the program climb maturity together to hit these dates.`,
    }
  }
  const name = countryNameFor(scenario.countryCode)
  // Show the standard in parentheses only when it's a specific named standard
  // (e.g. "FIPS 203 / ML-KEM"), not the generic "PQC key establishment" placeholder.
  const std = (s: string) => (/\d|FIPS|ML-|SLH|FN-/.test(s) ? ` (${s})` : '')
  return {
    title: `${name} — national PQC migration`,
    summary:
      `${name} — national post-quantum migration scenario. Two deadlines map to the ` +
      `framework's two-track model: key establishment${std(scenario.standards.HNDL)} by ${hndl} for ` +
      `harvest-now / HNDL data, and digital signatures${std(scenario.standards.TNFL)} by ${tnfl}. ` +
      `Governance is in place by ${scenario.governanceYear}; general-estate assets trail to the ` +
      `${scenario.programEndYear} program horizon. Watch the program climb maturity together to hit these dates.`,
  }
}

function narrationFor(item: AutoRunQueueItem): string {
  // Just the step's own label — no phase prefix (it's in the badge) and no verb.
  return item.step.label
}

function scrollDurationMs(overflowPx: number, speed: AutoRunSpeed): number {
  // Constant SPEED (px per ms): longer content takes proportionally longer to scroll
  // (it does NOT scroll faster). The cap is only a generous safety bound.
  const pxPerMs = speed === 'turbo' ? 1 : speed === 'slow' ? 0.08 : speed === 'fast' ? 0.26 : 0.13
  return Math.max(2000, Math.min(45000, overflowPx / pxPerMs))
}

/** Reset the board's scroll to the top so the Phase Journey + steps are visible
 *  again when we return from an embed. */
function scrollBoardToTop(): void {
  if (typeof document === 'undefined') return
  const board = document.querySelector<HTMLElement>('[data-sim-board]')
  if (!board) return
  board.scrollTop = 0
  board.querySelectorAll<HTMLElement>('[class*="overflow"]').forEach((el) => {
    el.scrollTop = 0
  })
}

/** Slowly auto-scroll the open embed through its FULL content, then call onDone —
 *  so a step never advances until the scroll has finished. Works for ANY embedded
 *  resource (Learn, reference, activity tools, workshops, catalog, scenarios) —
 *  they all mount in the one `[data-sim-embed-pane]`. Graceful: if nothing is
 *  scrollable it just dwells briefly; it bails WITHOUT advancing if the run is
 *  cancelled or the embed closes. */
function slowScrollEmbed(opts: {
  speed: AutoRunSpeed
  isCancelled: () => boolean
  onDone: () => void
}): void {
  const { speed, isCancelled, onDone } = opts
  const noScrollDwell =
    speed === 'turbo' ? 400 : speed === 'slow' ? 4500 : speed === 'fast' ? 1800 : 3000
  const finish = () => {
    if (!isCancelled()) onDone()
  }
  if (typeof document === 'undefined' || typeof window === 'undefined') {
    finish()
    return
  }
  const pane = document.querySelector<HTMLElement>('[data-sim-embed-pane]')
  if (!pane) {
    window.setTimeout(finish, noScrollDwell)
    return
  }
  // The real scroller may be the pane or a descendant — pick the most-scrollable.
  let scroller: HTMLElement = pane
  let maxOverflow = pane.scrollHeight - pane.clientHeight
  pane.querySelectorAll<HTMLElement>('div, section, main, article').forEach((el) => {
    const overflow = el.scrollHeight - el.clientHeight
    if (overflow > maxOverflow && /auto|scroll/.test(getComputedStyle(el).overflowY)) {
      maxOverflow = overflow
      scroller = el
    }
  })
  if (maxOverflow < 60) {
    window.setTimeout(finish, noScrollDwell) // nothing to scroll — just dwell
    return
  }
  const from = scroller.scrollTop
  const distance = maxOverflow - from
  if (speed === 'turbo') {
    scroller.scrollTop = maxOverflow // jump to the bottom so the output is seen, then advance
    window.setTimeout(finish, noScrollDwell)
    return
  }
  const duration = scrollDurationMs(distance, speed)
  const startedAt = window.performance.now()
  const tick = (now: number) => {
    if (isCancelled() || !document.body.contains(scroller)) return // bail, no advance
    const t = Math.min(1, (now - startedAt) / duration)
    const eased = t < 0.5 ? 2 * t * t : 1 - (-2 * t + 2) ** 2 / 2 // ease-in-out
    scroller.scrollTop = from + distance * eased
    if (t < 1) window.requestAnimationFrame(tick)
    else finish() // reached the bottom → now advance
  }
  window.requestAnimationFrame(tick)
}

export function useSimAutoRunPlayer({
  openStep,
  closeEmbed,
}: {
  openStep: (step: TreeStep) => void
  closeEmbed: () => void
}): SimAutoRunPlayer {
  const [running, setRunning] = useState(false)
  const [paused, setPaused] = useState(false)
  const [done, setDone] = useState(false)
  const [index, setIndex] = useState(0)
  const [total, setTotal] = useState(0)
  const [caption, setCaption] = useState('')
  const [label, setLabel] = useState('')
  const [speed, setSpeed] = useState<AutoRunSpeed>('normal')
  const [voiceOn, setVoiceOn] = useState(false) // OFF by default (user preference); toggle in the overlay
  const [voiceName, setVoiceName] = useState('')
  const [passIntro, setPassIntro] = useState<PassIntro | null>(null)
  const [phaseFocus, setPhaseFocus] = useState<PhaseFocus | null>(null)
  const [phaseIntro, setPhaseIntro] = useState<PhaseFocus | null>(null)
  const [scenarioIntro, setScenarioIntro] = useState<ScenarioIntro | null>(null)
  const [mode, setMode] = useState<RunMode>('climb')
  const [reveal, setReveal] = useState<ExecutiveDocumentType | null>(null)

  const queueRef = useRef<AutoRunQueueItem[]>([])
  const passStartsRef = useRef<{ level: number; start: number }[]>([])
  const lastLevelRef = useRef<number | null>(null) // the pass whose intro was consumed
  const lastSelPhaseRef = useRef<PhaseId | null>(null) // the phase the board is focused on
  const clockPlanRef = useRef<{ year: number; q: number }[]>([])
  const scenarioRef = useRef<SimScenario | null>(null)
  const modeRef = useRef<RunMode>('climb') // synchronous mode read for the step effect + end caption
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const voiceOnRef = useRef(voiceOn)
  const openStepRef = useRef(openStep)
  const closeEmbedRef = useRef(closeEmbed)
  const indexRef = useRef(index)
  const passIntroRef = useRef<number | null>(null)
  const spokenIntroForRef = useRef<number | null>(null)
  // Set-guards so the heavier per-phase narration / first-encounter modal fire AT
  // MOST ONCE per phase across the whole run (the level-major queue would otherwise
  // re-focus each phase ~36×).
  const spokenPhaseRef = useRef<Set<PhaseId>>(new Set())
  const shownPhaseModalRef = useRef<Set<PhaseId>>(new Set())
  const phaseIntroRef = useRef<PhaseId | null>(null)
  // One-time scenario-framing card: tracks "is showing" + "already spoken".
  const scenarioIntroRef = useRef(false)
  const spokenScenarioRef = useRef(false)
  useEffect(() => {
    voiceOnRef.current = voiceOn
  }, [voiceOn])
  useEffect(() => {
    openStepRef.current = openStep
  }, [openStep])
  useEffect(() => {
    closeEmbedRef.current = closeEmbed
  }, [closeEmbed])
  useEffect(() => {
    indexRef.current = index
  }, [index])
  useEffect(() => {
    passIntroRef.current = passIntro?.level ?? null
  }, [passIntro])
  useEffect(() => {
    phaseIntroRef.current = phaseIntro?.phase ?? null
  }, [phaseIntro])
  useEffect(() => {
    scenarioIntroRef.current = scenarioIntro != null
  }, [scenarioIntro])

  // Warm the voice list (loads async) + HARD speech safety: cancel any speech if
  // the tab is hidden, navigated, or closed so it can never keep speaking after the
  // page goes away.
  useEffect(() => {
    if (typeof window === 'undefined' || !window.speechSynthesis) return
    const warm = () => {
      const v = resolveVoice()
      setVoiceName(v?.name ?? '')
    }
    warm()
    const onHide = () => {
      if (document.hidden) stopSpeech()
    }
    window.speechSynthesis.addEventListener?.('voiceschanged', warm)
    window.addEventListener('pagehide', stopSpeech)
    window.addEventListener('beforeunload', stopSpeech)
    document.addEventListener('visibilitychange', onHide)
    return () => {
      window.speechSynthesis.removeEventListener?.('voiceschanged', warm)
      window.removeEventListener('pagehide', stopSpeech)
      window.removeEventListener('beforeunload', stopSpeech)
      document.removeEventListener('visibilitychange', onHide)
      stopSpeech()
    }
  }, [])

  const clearTimer = useCallback(() => {
    if (timerRef.current) {
      clearTimeout(timerRef.current)
      timerRef.current = null
    }
  }, [])

  const start = useCallback(
    (opts?: { mode?: RunMode; phase?: PhaseId }) => {
      const runMode: RunMode = opts?.mode ?? 'climb'
      setMode(runMode)
      modeRef.current = runMode
      // Remember the mode for "▶ Resume" — only climb-family runs are ever
      // resumable (walkthrough and single-phase runs always restart at 0), so
      // only persist those.
      if (usesSharedResumeIndex(runMode)) {
        useSimulationStore.getState().setAutoRunLastMode(runMode)
      }
      clearTimer()
      seedDemoOrg() // populate the scenario context so embeds have data + a scope to filter by
      setAutoRunFill(true) // tools opened during the run fill their forms with demo content
      // The first-run tour must not block the playthrough — but permanently marking it
      // seen here (as this used to do) meant a user entering via ?run=exec or "Play all"
      // never got onboarded, even after the run ended. The consumer (SimulationView)
      // suppresses the tour for the DURATION of an active run via `running`, without
      // burning the persisted `tourSeen` flag — so it's offered once the run completes.
      const deep = includesDeepDive(runMode)
      const q =
        runMode === 'intro'
          ? autoRunIntroQueue()
          : isWalkthroughMode(runMode)
            ? autoRunWalkthroughQueue(deep)
            : isPhaseMode(runMode)
              ? autoRunPhaseQueue(opts?.phase ?? useSimulationStore.getState().sel, deep)
              : deep
                ? autoRunDeepQueue()
                : autoRunQueue()
      queueRef.current = q
      // RESUME from the remembered playhead — the queue index where the last run was
      // interrupted (saved by stop(), cleared on completion + by Reset). Completion can
      // NOT locate the playhead: the queue shares completion keys across passes (a
      // module / reference / artifact-type recurs), so "first step not yet complete"
      // skips ahead to a unique late step — the closure. The remembered index is the
      // literal last position; Reset clears it (it lives in SEED) so a fresh run starts
      // at the top.
      const remembered = usesSharedResumeIndex(runMode)
        ? useSimulationStore.getState().autoRunResumeIndex
        : 0
      // Walkthrough and single-phase runs are short, scoped passes — always start
      // at the top (no resume).
      const startAt = !usesSharedResumeIndex(runMode)
        ? 0
        : remembered > 0 && remembered < q.length
          ? remembered
          : 0
      const scenario = getScenario(useSimulationStore.getState().country)
      scenarioRef.current = scenario
      // Walkthrough freezes the calendar (a tour, not a timed run): an empty clock plan
      // means the per-step advance never calls applyQuarter, so no dates ever move.
      clockPlanRef.current = isWalkthroughMode(runMode) ? [] : buildClockPlan(q, scenario)
      const starts: { level: number; start: number }[] = []
      q.forEach((it, i) => {
        const last = starts.at(-1)
        if (!last || last.level !== it.level) starts.push({ level: it.level, start: i })
      })
      passStartsRef.current = starts
      lastLevelRef.current = null
      lastSelPhaseRef.current = null
      // Reset the per-phase Set-guards + arm the one-time scenario-framing card.
      spokenPhaseRef.current = new Set()
      shownPhaseModalRef.current = new Set()
      spokenIntroForRef.current = null
      spokenScenarioRef.current = false
      setPhaseFocus(null)
      setPhaseIntro(null)
      // Only show the one-time scenario-framing card on a FRESH start; resuming
      // mid-queue skips it (it's already been seen).
      // The climb opens on the dated scenario-framing card; the walkthrough suppresses it
      // (dates are hidden) and leads with its own concept-led opening instead. A
      // single-phase run is a quick, already-in-context preview — the whole-program
      // framing ("watch the program climb maturity together") doesn't fit, so it's
      // suppressed the same way.
      setScenarioIntro(
        isWalkthroughMode(runMode) || isPhaseMode(runMode)
          ? null
          : startAt === 0
            ? scenarioIntroFor(scenario)
            : null
      )
      setTotal(q.length)
      setIndex(startAt)
      setDone(false)
      setPaused(false)
      setLabel('')
      setCaption('Starting the migration playthrough…')
      setRunning(true)
    },
    [clearTimer]
  )

  const pause = useCallback(() => {
    stopSpeech()
    setPaused(true)
  }, [])
  const resume = useCallback(() => setPaused(false), [])
  const stop = useCallback(() => {
    clearTimer()
    stopSpeech()
    // Remember WHERE we stopped so the play button resumes from here (not the
    // top) — climb-family only. A walkthrough or single-phase run's index is
    // meaningless against the climb queue's shape and must never overwrite its
    // saved playhead.
    if (usesSharedResumeIndex(modeRef.current)) {
      useSimulationStore.getState().setAutoRunResumeIndex(indexRef.current)
    }
    setAutoRunFill(false)
    setRunning(false)
    setPaused(false)
    // Also clear `done` — the transport band renders while `running || done`, so
    // after a run FINISHES (done=true) the band stays up showing "Close". That
    // Close button calls stop(); without resetting done here the band never
    // unmounts. Clearing done also resets the phase-run-complete "celebrated"
    // guard (SimulationView effect on `done`), so the next phase run re-opens it.
    setDone(false)
    setScenarioIntro(null)
    setPhaseIntro(null)
  }, [clearTimer])
  const cycleSpeed = useCallback(
    () =>
      setSpeed((s) =>
        s === 'normal' ? 'fast' : s === 'fast' ? 'turbo' : s === 'turbo' ? 'slow' : 'normal'
      ),
    []
  )
  const toggleVoice = useCallback(() => {
    setVoiceOn((v) => {
      if (v) stopSpeech()
      return !v
    })
  }, [])
  const advancePass = useCallback((stopVoice: boolean) => {
    const lvl = passIntroRef.current
    if (lvl == null) return
    lastLevelRef.current = lvl // mark this pass's intro consumed so steps don't re-trigger it
    if (stopVoice) stopSpeech()
    setPassIntro(null)
  }, [])
  // Manual "Begin" click cuts the narration short; the 6s auto-advance lets it keep
  // reading the pass description.
  const beginPass = useCallback(() => advancePass(true), [advancePass])

  // First-encounter phase modal: dismiss (manual click cuts the voice; the 6s
  // auto-advance lets it keep reading the phase summary into the steps).
  const advancePhase = useCallback((stopVoice: boolean) => {
    if (phaseIntroRef.current == null) return
    if (stopVoice) stopSpeech()
    setPhaseIntro(null)
  }, [])
  const beginPhase = useCallback(() => advancePhase(true), [advancePhase])

  // One-time scenario-framing card: dismiss and let the first pass begin.
  const advanceScenario = useCallback((stopVoice: boolean) => {
    if (!scenarioIntroRef.current) return
    if (stopVoice) stopSpeech()
    setScenarioIntro(null)
  }, [])
  const beginScenario = useCallback(() => advanceScenario(true), [advanceScenario])

  // Jump the playhead to an index and re-show the pass intro wherever we land.
  const jumpToIndex = useCallback(
    (target: number) => {
      clearTimer()
      stopSpeech()
      closeEmbedRef.current()
      lastLevelRef.current = null // force the pass-intro modal wherever we land
      lastSelPhaseRef.current = null // re-focus the phase + banner wherever we land
      setPassIntro(null)
      setPhaseIntro(null) // never leave a stale first-encounter modal up after a jump
      setPaused(false)
      setIndex(target)
    },
    [clearTimer]
  )

  const currentBlock = useCallback(() => {
    let cur = 0
    passStartsRef.current.forEach((s, i) => {
      if (s.start <= indexRef.current) cur = i
    })
    return cur
  }, [])

  const nextPass = useCallback(() => {
    const nxt = passStartsRef.current.at(currentBlock() + 1)
    if (nxt) jumpToIndex(nxt.start)
  }, [currentBlock, jumpToIndex])

  const prevPass = useCallback(() => {
    const cur = currentBlock()
    const curStart = passStartsRef.current.at(cur)?.start ?? 0
    const target =
      indexRef.current > curStart ? curStart : (passStartsRef.current.at(cur - 1)?.start ?? 0)
    jumpToIndex(target)
  }, [currentBlock, jumpToIndex])

  // Scenario-framing card (run start, before pass 1): with voice ON, speak the
  // EO / country framing and advance WHEN IT FINISHES (kept on screen at least
  // MODAL_MIN_HOLD_MS so a short line still lingers, and at most MODAL_MAX_HOLD_MS
  // as a safety cap in case onDone never fires). With voice OFF (or no speech),
  // keep a brief fixed hold. The card's "Begin" advances sooner.
  useEffect(() => {
    if (!scenarioIntro || paused || !running) return
    let advanced = false
    const safety = setTimeout(
      () => {
        if (!advanced) {
          advanced = true
          advanceScenario(false)
        }
      },
      voiceSafetyMs(scenarioIntro.summary, MODAL_MAX_HOLD_MS)
    )
    let minTimer: ReturnType<typeof setTimeout> | null = null
    const finish = () => {
      // Hold the modal at least MODAL_MIN_HOLD_MS from when narration ends.
      minTimer = setTimeout(() => {
        if (!advanced) {
          advanced = true
          advanceScenario(false)
        }
      }, MODAL_MIN_HOLD_MS)
    }
    if (voiceOnRef.current && !spokenScenarioRef.current) {
      spokenScenarioRef.current = true
      speakSequence(splitSentences(scenarioIntro.summary), finish)
    } else if (!voiceOnRef.current) {
      // Voice OFF: nothing to wait for — brief fixed hold.
      minTimer = setTimeout(() => {
        if (!advanced) {
          advanced = true
          advanceScenario(false)
        }
      }, MODAL_OFF_HOLD_MS)
    }
    // (If voice is on but already spoken, only the safety cap applies.)
    return () => {
      clearTimeout(safety)
      if (minTimer) clearTimeout(minTimer)
    }
  }, [scenarioIntro, paused, running, advanceScenario])

  // Pass-intro modal: with voice ON, speak the maturity-pass summary and advance
  // WHEN IT FINISHES ([MIN .. MAX] bounded). With voice OFF, brief fixed hold. The
  // modal's "Begin" advances sooner; the voice keeps reading into the pass.
  useEffect(() => {
    if (!passIntro || paused || !running || scenarioIntro) return
    let advanced = false
    const safety = setTimeout(
      () => {
        if (!advanced) {
          advanced = true
          advancePass(false)
        }
      },
      voiceSafetyMs(passIntro.summary, MODAL_MAX_HOLD_MS)
    )
    let minTimer: ReturnType<typeof setTimeout> | null = null
    const finish = () => {
      minTimer = setTimeout(() => {
        if (!advanced) {
          advanced = true
          advancePass(false)
        }
      }, MODAL_MIN_HOLD_MS)
    }
    if (voiceOnRef.current && spokenIntroForRef.current !== passIntro.level) {
      spokenIntroForRef.current = passIntro.level
      speakSequence(splitSentences(passIntro.summary), finish)
    } else if (!voiceOnRef.current) {
      minTimer = setTimeout(() => {
        if (!advanced) {
          advanced = true
          advancePass(false)
        }
      }, MODAL_OFF_HOLD_MS)
    }
    return () => {
      clearTimeout(safety)
      if (minTimer) clearTimeout(minTimer)
    }
  }, [passIntro, paused, running, scenarioIntro, advancePass])

  // First-encounter phase modal: with voice ON (and not turbo), speak the phase's
  // framework summary and advance WHEN IT FINISHES ([MIN .. MAX] bounded) — so the
  // phase summary always completes BEFORE the phase's steps start narrating. With
  // voice OFF or turbo, brief fixed hold. Shown at most once per phase (the
  // Set-guard is set when the modal opens).
  useEffect(() => {
    if (!phaseIntro || paused || !running) return
    let advanced = false
    const safety = setTimeout(
      () => {
        if (!advanced) {
          advanced = true
          advancePhase(false)
        }
      },
      voiceSafetyMs(phaseIntro.summary, MODAL_MAX_HOLD_MS)
    )
    let minTimer: ReturnType<typeof setTimeout> | null = null
    const finish = () => {
      minTimer = setTimeout(() => {
        if (!advanced) {
          advanced = true
          advancePhase(false)
        }
      }, MODAL_MIN_HOLD_MS)
    }
    const speakable = voiceOnRef.current && speed !== 'turbo'
    if (speakable && !spokenPhaseRef.current.has(phaseIntro.phase)) {
      spokenPhaseRef.current.add(phaseIntro.phase)
      speakSequence(splitSentences(phaseIntro.summary), finish)
    } else if (!speakable) {
      // Voice OFF or turbo: nothing to wait for — brief fixed hold (turbo stays fast).
      minTimer = setTimeout(() => {
        if (!advanced) {
          advanced = true
          advancePhase(false)
        }
      }, MODAL_OFF_HOLD_MS)
    }
    return () => {
      clearTimeout(safety)
      if (minTimer) clearTimeout(minTimer)
    }
  }, [phaseIntro, paused, running, speed, advancePhase])

  // The step cycle: peek the tool → complete + return to the board (sections update,
  // clock advances) → dwell on the board → next.
  useEffect(() => {
    if (!running || paused || done || passIntro || scenarioIntro || phaseIntro) return
    const q = queueRef.current
    const item = q.at(index)
    if (!item) return

    let cancelled = false
    const timers: ReturnType<typeof setTimeout>[] = []
    const after = (ms: number, fn: () => void) => {
      timers.push(
        setTimeout(() => {
          if (!cancelled) fn()
        }, ms)
      )
    }

    // Per-step announcement pacing. The step's brief "resource name" voice (spoken in
    // Beat A) flips `voiceDone`; Beat C will not advance to the next step until it
    // does (bounded by [dwell .. STEP_VOICE_MAX_MS]). When per-step voice is not
    // spoken (voice off / turbo / a modal up), it is treated as done immediately so
    // today's fast beat timing is preserved.
    let voiceDone = false
    let onVoiceDone: (() => void) | null = null
    const markVoiceDone = () => {
      if (voiceDone) return
      voiceDone = true
      const fn = onVoiceDone
      onVoiceDone = null
      fn?.()
    }

    after(index === 0 ? 500 : 300, () => {
      // True when this beat already started speaking the phase summary (a later
      // encounter, non-modal) — the per-step announcement below then stays silent.
      let spokeSummaryThisBeat = false
      setReveal(null) // clear any prior reveal at the start of each step's beat
      if (item.level !== lastLevelRef.current) {
        // New maturity pass — pause for the pass-intro modal (the board stays behind it).
        const sc = scenarioRef.current
        // The walkthrough is a single level-1 pass with no maturity passes — never
        // interrupt it with a pass-intro modal. A single-phase run also skips it:
        // the modal's copy is whole-program framed ("raise EVERY phase to level
        // N"), which is wrong when only one phase is being played.
        if (sc && modeRef.current !== 'walkthrough' && !isPhaseMode(modeRef.current)) {
          setPassIntro(passIntroFor(item.level, sc))
          return
        }
        lastLevelRef.current = item.level
      }
      // Within a pass: keep the board focused on the phase currently being raised.
      if (item.phase !== lastSelPhaseRef.current) {
        lastSelPhaseRef.current = item.phase
        useSimulationStore.getState().setSel(item.phase)
        setLabel(phaseLabel(item.phase))
        // Per-phase framework explanation: update the persistent banner; on the FIRST
        // encounter of this phase show the modal (Set-guarded) and let its effect speak;
        // on later encounters just narrate the summary (deduped, suppressed on turbo).
        const focus = phaseFocusFor(item.phase)
        setPhaseFocus(focus)
        if (focus.summary) {
          if (!shownPhaseModalRef.current.has(item.phase)) {
            shownPhaseModalRef.current.add(item.phase)
            setPhaseIntro(focus) // first encounter → modal (its effect handles the voice)
            return
          }
          if (voiceOnRef.current && speed !== 'turbo' && !spokenPhaseRef.current.has(item.phase)) {
            spokenPhaseRef.current.add(item.phase)
            // Speak the phase summary AND pace this step to it (Beat C waits on
            // voiceDone) — the per-step announcement below is skipped so it can't
            // cut the summary off.
            speakSequence(splitSentences(focus.summary), markVoiceDone)
            spokeSummaryThisBeat = true
          }
        }
      }
      // Beat A — open the tool inline (like a manual click) + announce the resource.
      // Speak a BRIEF one-line announcement of the resource being shown (the step's
      // own label), and pace the step to it (Beat C waits on `voiceDone`). No
      // per-step voice on turbo or with voice off (keep today's fast beat timing),
      // and none while a modal is up (guarded by the effect's early-return above).
      // If a phase summary was just spoken for this same step beat, that IS the
      // narration — don't speak again (it would cancel the summary).
      const text = narrationFor(item)
      openStepRef.current(item.step)
      setCaption(text) // overlay shows the self-explanatory title
      if (spokeSummaryThisBeat) {
        // already speaking the phase summary; Beat C is paced to it via markVoiceDone
      } else if (voiceOnRef.current && speed !== 'turbo') {
        speakSequence([text], markVoiceDone)
      } else {
        markVoiceDone() // nothing to wait for — preserve the fast beat
      }
      const toOutput = () => {
        if (cancelled) return
        // Beat B — complete + return to the board so the OUTPUT shows (sections
        // update, clock advances).
        completeStepGenuine(item.step)
        // Walkthrough: when a board document is generated, surface its "what this is" line.
        if (
          isWalkthroughMode(modeRef.current) &&
          item.step.kind === 'activity' &&
          item.step.artifactType &&
          EXEC_TOUR_REVEAL_TYPES.includes(item.step.artifactType)
        ) {
          setReveal(item.step.artifactType)
        }
        closeEmbedRef.current()
        // Scenario-paced clock: this index's planned {year, q} (passes land on the EO years).
        const plan = clockPlanRef.current[index]
        if (plan) {
          const cs = useSimulationStore.getState()
          if (plan.year !== cs.year || plan.q !== cs.q) {
            cs.applyQuarter({
              crqcShift: cs.crqcShift,
              year: plan.year,
              q: plan.q,
              newEvents: [],
            })
          }
        }
        after(80, scrollBoardToTop) // board re-rendered — show it from the top
        const next = index + 1
        const goNext = () => {
          if (cancelled) return
          if (next >= q.length) {
            setCaption(
              isWalkthroughMode(modeRef.current)
                ? 'That’s the full program, end to end.'
                : isPhaseMode(modeRef.current)
                  ? `${phaseLabel(item.phase)} complete.`
                  : 'Migration complete — full program maturity reached.'
            )
            setAutoRunFill(false)
            setRunning(false)
            setDone(true)
            setIndex(q.length) // land the counter on N/N — it never advances past the last item otherwise
            // Finished — clear the resume point so the button reads "Play all" and a
            // fresh press replays from the top. Climb-family only: a single-phase
            // run never touched the shared playhead (usesSharedResumeIndex), so it
            // must not clear an unrelated in-progress climb's saved position either.
            if (usesSharedResumeIndex(modeRef.current)) {
              useSimulationStore.getState().setAutoRunResumeIndex(0)
            }
          } else {
            setIndex(next)
          }
        }
        // Beat C — linger on the output, then advance — but never before the step's
        // brief announcement voice has finished (so step N+1 can't cut it off). The
        // dwell (lookMs) is the MIN; STEP_VOICE_MAX_MS is a safety cap so a dropped
        // onend can't stall the run.
        let stepAdvanced = false
        const advanceStep = () => {
          if (stepAdvanced || cancelled) return
          stepAdvanced = true
          goNext()
        }
        after(lookMs(speed), () => {
          if (voiceDone) {
            advanceStep()
          } else {
            onVoiceDone = advanceStep // advance the moment the announcement finishes
            after(voiceSafetyMs(item.step.label, STEP_VOICE_MAX_MS), advanceStep) // …or at the safety cap
          }
        })
      }
      // Beat A — let the embed mount, then slowly scroll its FULL content; advance
      // ONLY when the scroll finishes (or, for an empty/non-scrollable page, after a
      // brief dwell).
      after(500, () => {
        slowScrollEmbed({ speed, isCancelled: () => cancelled, onDone: toOutput })
      })
    })

    return () => {
      cancelled = true
      timers.forEach(clearTimeout)
    }
  }, [running, paused, done, index, speed, passIntro, scenarioIntro, phaseIntro])

  // Reactive "is there a saved playhead to resume from?" — the remembered queue
  // index (set by stop(), cleared on completion + by Reset). Subscribing to it makes
  // the play button flip to "Resume" the moment a run is interrupted, and back to
  // "Play all" after the run finishes or the simulation is reset.
  const resumable = useSimulationStore((s) => s.autoRunResumeIndex) > 0
  // The mode "▶ Resume" should restart — the last climb-family mode that was
  // running, so resuming an Extended Migration Journey doesn't silently drop
  // back to plain Full Migration Journey. Defaults to 'climb' if never set
  // (fresh state / older persisted saves from before this field existed).
  const resumeModeRaw = useSimulationStore((s) => s.autoRunLastMode)
  const resumeMode: RunMode =
    resumeModeRaw === 'climb' || resumeModeRaw === 'climb-deep' ? resumeModeRaw : 'climb'

  // Stop the timer + any speech if the sim unmounts mid-run.
  useEffect(
    () => () => {
      clearTimer()
      stopSpeech()
    },
    [clearTimer]
  )

  return {
    running,
    paused,
    done,
    mode,
    reveal,
    caption,
    phaseLabel: label,
    index,
    total,
    speed,
    voiceOn,
    voiceName,
    passIntro,
    phaseFocus,
    phaseIntro,
    scenarioIntro,
    resumable,
    resumeMode,
    start,
    pause,
    resume,
    stop,
    cycleSpeed,
    toggleVoice,
    beginPass,
    beginPhase,
    beginScenario,
    prevPass,
    nextPass,
  }
}
