// SPDX-License-Identifier: GPL-3.0-only

/** Maps country name values from the leaders CSV to ISO 3166-1 alpha-2 flag codes.
 *  Dual-country entries use the first-listed country's code. */
export const FLAG_CODE_MAP: Record<string, string> = {
  USA: 'us',
  UK: 'gb',
  France: 'fr',
  Germany: 'de',
  Switzerland: 'ch',
  Canada: 'ca',
  Singapore: 'sg',
  Japan: 'jp',
  'South Korea': 'kr',
  Australia: 'au',
  Israel: 'il',
  Belgium: 'be',
  Portugal: 'pt',
  Netherlands: 'nl',
  Sweden: 'se',
  Spain: 'es',
  Italy: 'it',
  India: 'in',
  China: 'cn',
  Russia: 'ru',
  Finland: 'fi',
  Ireland: 'ie',
  'New Zealand': 'nz',
  'Estonia/EU': 'eu',
  'USA/Switzerland': 'us',
  'USA/Germany': 'us',
  'USA/Canada': 'us',
  'USA/China': 'us',
  'USA/Israel': 'us',
  'USA/Netherlands': 'us',
  'Belgium/USA': 'be',
  'France/Netherlands': 'fr',
  'France/USA': 'fr',
  'Germany/Netherlands': 'de',
  'Japan/USA': 'jp',
  'Netherlands/USA': 'nl',
}

/** Maps region IDs to the country name values used in the leaders CSV. */
export const LEADERS_REGION_COUNTRIES: Record<string, string[]> = {
  americas: [
    'USA',
    'Canada',
    'Belgium/USA',
    'France/USA',
    'Japan/USA',
    'Netherlands/USA',
    'USA/Canada',
    'USA/China',
    'USA/Germany',
    'USA/Israel',
    'USA/Netherlands',
    'USA/Switzerland',
  ],
  eu: [
    'UK',
    'France',
    'Germany',
    'Switzerland',
    'Belgium',
    'Portugal',
    'Estonia/EU',
    'Netherlands',
    'Sweden',
    'Russia',
    'Spain',
    'Italy',
    'Finland',
    'Ireland',
    'France/Netherlands',
    'Germany/Netherlands',
    'Israel',
  ],
  apac: ['Singapore', 'Japan', 'South Korea', 'Australia', 'India', 'China', 'New Zealand'],
}
