// SPDX-License-Identifier: GPL-3.0-only
import React, { useState } from 'react'
import { AlertTriangle, CheckCircle, Download } from 'lucide-react'
import { ROTATION_POLICIES } from '../data/secretsConstants'
import { FilterDropdown } from '@/components/common/FilterDropdown'
import { Button } from '@/components/ui/button'

interface PolicyRow {
  id: string
  secretType: string
  currentTtl: string
  pqcTtl: string
  renewalWindow: string
  complianceFramework: string
  automationTool: string
  pqcConsideration: string
}

// TTL options for dropdowns
const TTL_OPTIONS = [
  '1 hour',
  '8 hours',
  '1 day',
  '7 days',
  '30 days',
  '60 days',
  '90 days',
  '180 days',
  '1 year',
  '2 years',
]

// Parse days from TTL string for comparison
function parseTtlDays(ttl: string): number {
  if (ttl.includes('hour')) return 1 / 24
  if (ttl.includes('day')) return parseFloat(ttl)
  if (ttl.includes('week')) return parseFloat(ttl) * 7
  if (ttl.includes('month')) return parseFloat(ttl) * 30
  if (ttl.includes('year')) return parseFloat(ttl) * 365
  const num = parseFloat(ttl)
  return isNaN(num) ? 365 : num
}

// PQC-recommended max TTLs (in days)
const PQC_MAX_TTL_DAYS: Record<string, number> = {
  'api-key-rotation': 90,
  'db-credential-rotation': 1,
  'tls-cert-rotation': 90,
  'signing-key-rotation': 365,
  'dek-rotation': 30,
  'oauth-token-rotation': 1,
}

const generateYaml = (rows: PolicyRow[]): string => {
  const lines: string[] = [
    '# PQC-Aware Secrets Rotation Policy',
    '# Generated by PQC Today — Secrets Management Module',
    `# Date: ${new Date().toISOString().split('T')[0]}`,
    '',
    'rotation_policies:',
  ]

  rows.forEach((row) => {
    const key = row.id.replace(/-rotation$/, '').replace(/-/g, '_')
    lines.push(`  ${key}:`)
    lines.push(`    secret_type: "${row.secretType}"`)
    lines.push(`    ttl: "${row.currentTtl}"`)
    lines.push(`    renewal_window: "${row.renewalWindow}"`)
    lines.push(`    compliance_framework: "${row.complianceFramework}"`)
    lines.push(`    automation_tool: "${row.automationTool}"`)
    lines.push(`    # PQC: ${row.pqcConsideration.substring(0, 80)}...`)
    lines.push('')
  })

  lines.push('pqc_requirements:')
  lines.push('  vault_version: ">=1.18.0"')
  lines.push('  kek_algorithm: "ML-KEM-768"')
  lines.push('  signing_algorithm: "ML-DSA-65"')
  lines.push('  tls_hybrid: "X25519+ML-KEM-768"')

  return lines.join('\n')
}

export const RotationPolicyDesigner: React.FC = () => {
  const [policyRows, setPolicyRows] = useState<PolicyRow[]>(
    ROTATION_POLICIES.map((p) => ({
      id: p.id,
      secretType: p.secretType,
      currentTtl: p.ttl,
      pqcTtl: p.ttl,
      renewalWindow: p.renewalWindow,
      complianceFramework: p.complianceFramework,
      automationTool: p.automationTool,
      pqcConsideration: p.pqcConsideration,
    }))
  )
  const [showYaml, setShowYaml] = useState(false)

  const updateTtl = (id: string, ttl: string) => {
    setPolicyRows((prev) => prev.map((r) => (r.id === id ? { ...r, currentTtl: ttl } : r)))
  }

  // Check which rows exceed PQC recommendations
  const warningRows = policyRows.filter((row) => {
    const maxDays = PQC_MAX_TTL_DAYS[row.id]
    if (!maxDays) return false
    const currentDays = parseTtlDays(row.currentTtl)
    return currentDays > maxDays
  })

  const yamlContent = generateYaml(policyRows)

  return (
    <div className="space-y-6">
      {/* Instructions */}
      <div className="bg-muted/50 rounded-lg p-4 border border-border text-xs text-muted-foreground">
        Adjust TTL values for each secret type. The designer compares your selections against
        PQC-recommended maximums and flags over-long lifetimes that increase HNDL risk. Click
        &quot;Generate Policy YAML&quot; to export a rotation config.
      </div>

      {/* Policy Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-xs">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left py-3 px-2 text-muted-foreground font-medium min-w-[140px]">
                Secret Type
              </th>
              <th className="text-left py-3 px-2 text-muted-foreground font-medium min-w-[120px]">
                Your TTL
              </th>
              <th className="text-left py-3 px-2 text-muted-foreground font-medium hidden sm:table-cell">
                PQC Max TTL
              </th>
              <th className="text-left py-3 px-2 text-muted-foreground font-medium hidden md:table-cell">
                Automation
              </th>
              <th className="text-left py-3 px-2 text-muted-foreground font-medium hidden lg:table-cell">
                Compliance
              </th>
              <th className="text-center py-3 px-2 text-muted-foreground font-medium">Status</th>
            </tr>
          </thead>
          <tbody>
            {policyRows.map((row) => {
              const maxDays = PQC_MAX_TTL_DAYS[row.id]
              const currentDays = parseTtlDays(row.currentTtl)
              const isOver = maxDays !== undefined && currentDays > maxDays
              const origPolicy = ROTATION_POLICIES.find((p) => p.id === row.id)

              return (
                <tr
                  key={row.id}
                  className={`border-b border-border/50 ${isOver ? 'bg-status-warning/5' : ''}`}
                >
                  <td className="py-3 px-2 font-medium text-foreground">{row.secretType}</td>
                  <td className="py-3 px-2">
                    <FilterDropdown
                      noContainer
                      selectedId={row.currentTtl}
                      onSelect={(id) => updateTtl(row.id, id)}
                      items={TTL_OPTIONS.map((opt) => ({ id: opt, label: opt }))}
                      className="max-w-[120px]"
                    />
                  </td>
                  <td className="py-3 px-2 text-muted-foreground hidden sm:table-cell">
                    {origPolicy?.maxTTL ?? '—'}
                  </td>
                  <td className="py-3 px-2 text-muted-foreground hidden md:table-cell">
                    <span className="line-clamp-1">{row.automationTool}</span>
                  </td>
                  <td className="py-3 px-2 text-muted-foreground hidden lg:table-cell">
                    <span className="line-clamp-1">{row.complianceFramework}</span>
                  </td>
                  <td className="py-3 px-2 text-center">
                    {isOver ? (
                      <AlertTriangle size={14} className="text-status-warning inline-block" />
                    ) : (
                      <CheckCircle size={14} className="text-status-success inline-block" />
                    )}
                  </td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* Warnings */}
      {warningRows.length > 0 && (
        <div className="bg-status-warning/10 border border-status-warning/30 rounded-lg p-4 space-y-2">
          <div className="flex items-center gap-2 mb-2">
            <AlertTriangle size={16} className="text-status-warning" />
            <span className="text-sm font-bold text-status-warning">
              TTL Exceeds PQC Recommendation
            </span>
          </div>
          {warningRows.map((row) => {
            const origPolicy = ROTATION_POLICIES.find((p) => p.id === row.id)
            return (
              <div key={row.id} className="text-xs text-muted-foreground">
                <strong className="text-foreground">{row.secretType}</strong>: Selected{' '}
                <span className="text-status-warning font-mono">{row.currentTtl}</span> exceeds PQC
                max <span className="font-mono">{origPolicy?.maxTTL}</span>.{' '}
                {row.pqcConsideration.substring(0, 120)}
              </div>
            )
          })}
        </div>
      )}

      {/* PQC Considerations Table */}
      <div className="bg-muted/50 rounded-lg p-4 border border-border">
        <div className="text-sm font-bold text-foreground mb-3">PQC Rotation Considerations</div>
        <div className="space-y-2">
          {policyRows.map((row) => (
            <div key={row.id} className="flex items-start gap-2">
              <span className="text-primary shrink-0 mt-0.5 text-xs">&#8227;</span>
              <div className="text-[10px] text-muted-foreground">
                <strong className="text-foreground">{row.secretType}</strong>:{' '}
                {row.pqcConsideration}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Generate YAML button */}
      <div className="flex flex-wrap gap-3">
        <Button
          variant="ghost"
          onClick={() => setShowYaml(!showYaml)}
          className="flex items-center gap-2 px-4 py-2 bg-primary text-black font-bold rounded-lg hover:bg-primary/90 transition-colors text-sm"
        >
          <Download size={14} />
          {showYaml ? 'Hide' : 'Generate'} Policy YAML
        </Button>
        {warningRows.length === 0 && (
          <div className="flex items-center gap-2 text-sm text-status-success">
            <CheckCircle size={16} />
            All TTLs within PQC recommendations
          </div>
        )}
      </div>

      {showYaml && (
        <div>
          <div className="text-sm font-bold text-foreground mb-2">
            Rotation Policy Configuration
          </div>
          <div className="bg-muted font-mono text-xs rounded-lg p-4 overflow-x-auto border border-border whitespace-pre text-foreground/90 max-h-96 overflow-y-auto">
            {yamlContent}
          </div>
        </div>
      )}
    </div>
  )
}
