// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 07182026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p3',
  gate: {
    id: 'G3',
    criterion: 'Risk scoring complete; QRA with prioritized backlog delivered',
  },
  generated: '07182026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator:
        'Informal awareness of which systems are "probably vulnerable"; no structured scoring',
      activities: [
        {
          id: '3.1',
          title: 'Define Risk Scoring Model',
          decision:
            'Score risk across all four dimensions — HNDL exposure, trust criticality, feasibility, regulatory pressure — not just severity.',
          do: 'Establish the four-dimension model: (1) HNDL exposure, (2) TNFL/trust-infrastructure criticality, (3) migration feasibility, (4) regulatory & compliance pressure. (Practice note, not a framework requirement: some programs calibrate a fifth dimension — business impact/consequence of a breach — on top of these four; the framework itself defines exactly four.)',
          output: 'Risk scoring model',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Risk Management',
              to: '/learn/pqc-risk-management',
              moduleId: 'pqc-risk-management',
            },
            {
              kind: 'learn',
              label: 'Learn: data sensitivity & legal/data-retention horizon',
              to: '/learn/data-asset-sensitivity',
              moduleId: 'data-asset-sensitivity',
            },
            {
              kind: 'reference',
              label:
                "Reference: Mosca's inequality — shelf-life + migration time > time to Q-Day means you're already late",
              to: '/threats?view=horizon',
              refId: 'threats',
            },
            {
              kind: 'reference',
              label: 'Reference: why 256-bit ECC ≈ RSA-2048 under quantum (security levels)',
              to: '/algorithms?tab=detailed',
              refId: 'algorithms-detailed',
            },
            {
              kind: 'reference',
              label: 'Reference: PQC Protocol Matrix',
              to: '/algorithms?tab=support',
              refId: 'algorithms-protocol-matrix',
            },
            {
              kind: 'reference',
              label:
                'Reference: regulatory deadline clock — calibrate Dimension 4, Regulatory & Compliance Pressure (within 2 years = Critical)',
              to: '/timeline',
              refId: 'timeline',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Formal risk scoring model applied to Tier-1 CBOM entries; prioritized migration backlog exists; QRA document produced',
      activities: [
        {
          id: '3.2',
          title: 'Calculate Priority Scores',
          decision:
            "Compute a composite score and tier the whole CBOM — don't sequence by gut feel or alphabetical order.",
          do: 'Compute composite scores and classify systems into migration tiers.',
          output: 'Scored and tiered CBOM',
          steps: [
            {
              kind: 'activity',
              label: 'Produce a Risk Register',
              to: '/business/tools/risk-register',
              artifactType: 'risk-register',
            },
          ],
        },
        {
          id: '3.3',
          title: 'Apply Migration Sequencing Logic',
          decision:
            'Sequence key-exchange and signature migrations as two separate tracks — they move on different timelines.',
          do: 'Sequence with the two-track model (key exchange / signatures) by exposure and lead time.',
          output: 'Migration sequencing recommendation',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: the two-track migration sequencing model',
              to: '/learn/migration-program',
              moduleId: 'migration-program',
            },
            {
              kind: 'reference',
              label: 'Confirm your classical → PQC replacement mapping',
              to: '/algorithms?tab=transition',
              refId: 'algorithms-transition',
            },
            {
              kind: 'reference',
              label: 'Compare PQC candidates in detail and confirm your architecture',
              to: '/algorithms?tab=detailed',
              refId: 'algorithms-detailed',
            },
            {
              kind: 'activity',
              label: 'Draft a Risk Treatment Plan',
              to: '/business/tools/risk-treatment-plan',
              artifactType: 'risk-treatment-plan',
            },
          ],
        },
        {
          id: '3.4',
          title: 'Produce the Quantum Readiness Assessment (QRA)',
          decision:
            'Turn the scoring into a living QRA you update as standards and deadlines shift — not a one-time report you freeze.',
          do: 'Consolidate scoring into a defensible QRA: heatmap, backlog, gap analysis, compliance mapping.',
          output: 'Quantum Readiness Assessment (QRA)',
          steps: [
            {
              kind: 'reference',
              label: 'Map the QRA to NIST / CNSA 2.0 / ETSI / sector rules',
              to: '/compliance',
              refId: 'compliance',
            },
            {
              kind: 'reference',
              label:
                'View your auto-assembled QRA — heatmap, backlog, gap analysis, compliance mapping — on the Report page',
              to: '/report',
              refId: 'report',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Give everything equal priority',
      why: 'Treating all vulnerable crypto as equally urgent dilutes resources and stalls the highest-risk systems.',
    },
    {
      title: 'Ignore migration feasibility',
      why: 'Prioritising systems that cannot migrate yet wastes effort on unmigrable targets.',
    },
    {
      title: 'Produce the QRA once and freeze it',
      why: 'Risk scores change as standards mature and deadlines approach; a static QRA goes stale.',
    },
    {
      title: 'Migrate RSA before ECC for "strength"',
      why: '256-bit ECC is at least as exposed to quantum attack as RSA-2048; ordering by classical strength misreads the threat.',
    },
    {
      title: 'Skip the legal / data-retention review',
      why: 'Long-retention data (GDPR, contractual, >10–15y) changes the HNDL exposure window; without legal counsel the QRA under-scores the very data that needs protecting first.',
    },
  ],
}

export default TREE
