// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 07182026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p5',
  gate: {
    id: 'G5',
    criterion: 'Pilots validated; performance baselines established; Tier-1 rollout approved',
  },
  generated: '07182026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Lab testing only; no production exposure',
      activities: [
        {
          id: '5.1',
          title: 'Select Pilot Targets',
          decision:
            'Pilot on Tier-1 systems you fully control and can measure — not the easiest, lowest-stakes systems you can find.',
          do: 'Pick 2–4 Tier-1 pilots with full control, measurable baselines and rollback capability.',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Hybrid Cryptography',
              to: '/learn/hybrid-crypto',
              moduleId: 'hybrid-crypto',
            },
            {
              kind: 'catalog',
              label: 'Pick pilots from the Migrate catalog',
              to: '/migrate',
              catalogId: 'pilots',
            },
          ],
          deepDive: [
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: hybrid KEM + ECDH encryption',
              to: '/playground/hybrid-encrypt',
              workshopId: 'hybrid-encrypt',
            },
            {
              kind: 'workshop',
              label:
                'Deep dive — Practice: hybrid signature spectrums (composite signatures are far less standardized than hybrid KEMs — IETF LAMPS composites are still drafts)',
              to: '/playground/hybrid-sigs',
              workshopId: 'hybrid-sigs',
            },
          ],
        },
        {
          id: '5.2',
          title: 'Design Hybrid Deployments',
          decision:
            "Design the hybrid pattern and confirm your libraries actually support it before you pilot — don't discover a gap mid-rollout.",
          do: 'Design hybrid patterns (e.g. X25519+ML-KEM-768) and verify library readiness.',
          steps: [
            {
              kind: 'reference',
              label: 'Reference: which protocols have a PQC path',
              to: '/algorithms?tab=support',
              refId: 'algorithms-protocol-matrix',
            },
            {
              kind: 'learn',
              label:
                'Learn: TLS 1.3 hybrid — the recommended first pilot (X25519+ML-KEM-768, downgrade attack mitigations)',
              to: '/learn/tls-basics',
              moduleId: 'tls-basics',
            },
            {
              kind: 'learn',
              label: 'Learn: VPN/IPsec & SSH PQC patterns',
              to: '/learn/vpn-ssh-pqc',
              moduleId: 'vpn-ssh-pqc',
            },
            {
              kind: 'learn',
              label: 'Learn: code & firmware signing (Track B — integrity)',
              to: '/learn/code-signing',
              moduleId: 'code-signing',
            },
            {
              kind: 'activity',
              label: 'Plan the hybrid transition',
              to: '/business/tools/hybrid-transition-planner',
              artifactType: 'hybrid-transition',
            },
            {
              kind: 'activity',
              label: 'Negotiate the minimum-interop baseline for your hybrid protocol design',
              to: '/business/tools/mti-negotiator',
              artifactType: 'mti-negotiator',
            },
          ],
          deepDive: [
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: PQC SSH simulator',
              to: '/playground/pqc-ssh-sim',
              workshopId: 'pqc-ssh-sim',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: firmware signing',
              to: '/playground/firmware-signing',
              workshopId: 'firmware-signing',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        '2+ production pilots running with measured results; rollback procedures tested; validated patterns documented',
      activities: [
        {
          id: '5.3',
          title: 'Execute Pilots with Measurement',
          decision:
            "Measure pilots against real SLOs and prove rollback works — a pilot that only checks 'did it not crash' isn't validated.",
          do: 'Run pilots against SLOs (latency p50/p95/p99, CPU, throughput, error/fallback rate), budget for client-compatibility testing alongside server metrics, test rollback and validate compatibility. Canary the rollout at low traffic first — 6.4 covers the baseline/canary methodology in more depth for the phases running in parallel.',
          output: 'Pilot results reports',
          steps: [
            {
              kind: 'workshop',
              label: 'Practice: measure the TLS 1.3 hybrid handshake',
              to: '/playground/tls-simulator',
              workshopId: 'tls-simulator',
            },
            {
              kind: 'scenario',
              label: 'Lab: migration impact — classical vs PQC TLS (latency, cert size, bandwidth)',
              to: '/playground/sbx-migration-impact',
              scenarioId: 'migration-impact',
            },
            {
              kind: 'activity',
              label: 'Draft a Deployment Playbook',
              to: '/business/tools/deployment-playbook',
              artifactType: 'deployment-playbook',
            },
            {
              kind: 'reference',
              label:
                'Define pilot exit criteria — what threshold means go — before the rollout decision',
              to: '/report',
              refId: 'report',
            },
            {
              kind: 'architecture',
              label:
                'Decide the migration pattern (hybrid vs pure) for your first unlocked connections',
              to: '/simulation',
              minDecisions: 2,
            },
          ],
          deepDive: [
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: API Security & JWT Workshop',
              to: '/playground/api-security-jwt',
              workshopId: 'api-security-jwt',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: S/MIME & CMS email signing',
              to: '/playground/email-signing',
              workshopId: 'email-signing',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: multi-algorithm token/signing migration',
              to: '/playground/token-migration',
              workshopId: 'token-migration',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: AI Security & PQC',
              to: '/learn/ai-security-pqc',
              moduleId: 'ai-security-pqc',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: MLS Group Messaging',
              to: '/learn/mls-group-messaging',
              moduleId: 'mls-group-messaging',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: MLS Group Messaging workshop',
              to: '/playground/mls-group-messaging',
              workshopId: 'mls-group-messaging',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'Tier-1 internet-facing systems on hybrid/PQC; wave rollout underway for Tier-2; defense-in-depth measures (tokenization, AES-256, segmentation) deployed',
      activities: [
        {
          id: '5.4',
          title: 'Scale from Pilot to Production Through Waves',
          decision:
            'Roll out in controlled waves, each gated on the one before — not a single big-bang cutover to production.',
          do: 'Sequence deployment through six controlled waves, each with a defined scope and an explicit prerequisite gate from the one before: Lab/Staging → Internal Non-Critical → Internal Production → External Controlled (partners) → External Broad (public-facing) → Long Tail (legacy, OT, embedded).',
          output: 'Wave deployment plan',
          steps: [
            {
              kind: 'reference',
              label: 'Reference: staged-rollout & wave-sequencing patterns in the Library',
              to: '/library',
              refId: 'library',
            },
            {
              kind: 'architecture',
              label:
                'Extend pattern decisions across the wave — cover more of your unlocked connections',
              to: '/simulation',
              minDecisions: 4,
            },
          ],
        },
        {
          id: '5.5–5.6',
          title: 'Defense-in-Depth & Data-at-Rest Strategy',
          decision:
            'Decide a defense-in-depth strategy per data store — tokenize, wrap or accept-and-monitor — not one blanket policy for everything.',
          do: 'Deploy tokenization, segmentation and AES-256 defaults; decide a per-store data-at-rest strategy.',
          output: 'Defense-in-depth & data-at-rest plan',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Confidential Computing & defense-in-depth',
              to: '/learn/confidential-computing',
              moduleId: 'confidential-computing',
            },
            {
              kind: 'learn',
              label: 'Learn: data-at-rest strategy & DB encryption',
              to: '/learn/database-encryption-pqc',
              moduleId: 'database-encryption-pqc',
            },
            {
              kind: 'workshop',
              label: 'Practice: PQC key-wrapping (envelope encryption)',
              to: '/playground/envelope-encrypt',
              workshopId: 'envelope-encrypt',
            },
            {
              kind: 'scenario',
              label: 'Lab: ML-KEM key wrapping for cloud KMS (envelope encryption)',
              to: '/playground/sbx-cloud-kms',
              scenarioId: 'cloud-kms',
            },
            {
              kind: 'activity',
              label: 'Decide the per-store data-at-rest strategy',
              to: '/business/tools/data-at-rest-strategy',
              artifactType: 'data-at-rest-strategy',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Estate-wide hybrid/PQC deployment substantially complete; transitioning selected systems from hybrid to PQC-only; crypto-agility demonstrated via algorithm-swap drill',
      activities: [
        {
          id: '5.7',
          title: 'AI-Assisted Migration: Where It Helps, and the Gate That Stays Closed',
          decision:
            'Let AI triage and draft, but keep full human review on any AI-modified cryptographic code — that review gate never closes.',
          do: 'Use AI to triage and enrich, but keep full review rigor on AI-modified cryptographic code.',
          steps: [
            {
              kind: 'activity',
              label: 'Audit AI-assisted crypto refactors',
              to: '/business/tools/crypto-api-refactor-audit',
              artifactType: 'crypto-api-refactor',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Digital ID',
              // ?tab=workshop: openStep() parses it, and the value of this
              // module from inside the sim is the hands-on credential flow,
              // not its Learn tab.
              to: '/learn/digital-id?tab=workshop',
              moduleId: 'digital-id',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Digital Assets',
              to: '/learn/digital-assets',
              moduleId: 'digital-assets',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Pilot the easy systems, not the important ones',
      why: 'Convenience-based pilots prove little about real-world PQC viability on high-risk systems.',
    },
    {
      title: 'Skip rollback planning',
      why: 'Deploying without a tested rollback path leaves you unable to revert when a pilot fails.',
    },
    {
      title: 'Big-bang instead of waves',
      why: 'Migrating all Tier-1 at once prevents each wave validating assumptions for the next.',
    },
    {
      title: 'Measure only latency, not compatibility',
      why: 'Handshake metrics alone miss the downstream compatibility failures that break production.',
    },
    {
      title: 'Treat hybrid as the end state',
      why: 'Deploying hybrid without planning the PQC-only transition forces a second migration later.',
    },
    {
      title: 'Ignore library version as a hard constraint',
      why: 'PQC needs current libraries (OpenSSL 3.5+, BoringSSL, AWS-LC, Bouncy Castle); a lagging library/runtime silently blocks the deployment you designed.',
    },
  ],
}

export default TREE
