// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 07182026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'foundations',
  generated: '07182026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Cross-cutting capabilities recognized; ad hoc maturity awareness; no KPIs',
      activities: [
        {
          id: 'F.1',
          title: 'Establish GRC & Assess Program Maturity',
          decision:
            'Run the seven-domain maturity self-assessment first — your overall score is only as strong as your weakest domain.',
          do: 'Stand up the risk-appetite statement and KRI cascade; run (or refine) your PQC assessment across the seven domains — Cryptographic Inventory, Governance & Ownership, Pilots & Deployment, Vendor & Supply Chain, Compliance & Standards, Crypto-Agility, Risk & Prioritization. Program maturity is derived from your progress, overall = weakest domain. (Level 0 "Unaware" — no organizational awareness, nothing planned or underway — is where every domain starts; this activity is how you leave it.)',
          output: 'GRC structure & maturity baseline',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC GRC (risk appetite & KRIs)',
              to: '/learn/pqc-grc',
              moduleId: 'pqc-grc',
            },
            {
              kind: 'reference',
              label: 'Run / refine your PQC assessment',
              to: '/assess',
              refId: 'assess-engine',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Maturity self-assessment run; KPI baseline set; crypto-agility plan and skills plan drafted',
      activities: [
        {
          id: 'F.2',
          title: 'Baseline Metrics & the Evidence Dossier',
          decision:
            'Baseline the five board KPIs and start the evidence dossier now — reconstructing history for an auditor later is much harder.',
          do: 'Set the board KPI pack (Coverage/Trust/Inventory/Vendors/Agility) and the operational KPIs, and start the audit/litigation evidence dossier.',
          output: 'KPI baseline & evidence dossier',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: why these five KPIs — what the board actually needs to see',
              to: '/learn/pqc-governance',
              moduleId: 'pqc-governance',
            },
            {
              kind: 'activity',
              label: 'Baseline the board KPI pack',
              to: '/business/tools/kpi-dashboard',
              artifactType: 'kpi-dashboard',
            },
            {
              kind: 'activity',
              label: 'Track operational KPIs & the evidence dossier',
              to: '/business/tools/kpi-tracker',
              artifactType: 'kpi-tracker',
            },
          ],
        },
        {
          id: 'F.3',
          title: 'Build Crypto-Agility & the Team',
          decision:
            'Design for crypto-agility as the end state and staff the core roles now — retrofitting agility after the migration costs far more.',
          do: 'Adopt crypto-agility as the end-state architecture and staff the program with the framework core roles (≈1 FTE per 500 CBOM instances for the first two years, tapering to ≈1 per 1,000 once rollout stabilizes).',
          output: 'Crypto-agility roadmap & skills plan',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Crypto-Agility as end-state',
              to: '/learn/crypto-agility',
              moduleId: 'crypto-agility',
            },
            {
              kind: 'learn',
              label: 'Learn: skills & team structure (roles, FTE sizing)',
              to: '/learn/skills-team-structure',
              moduleId: 'skills-team-structure',
            },
            {
              kind: 'activity',
              label: 'Plan skills & team',
              to: '/business/tools/skills-team-plan',
              artifactType: 'skills-team-plan',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Cryptographic APIs & Developer Languages',
              to: '/learn/crypto-dev-apis',
              moduleId: 'crypto-dev-apis',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: SLH-DSA',
              to: '/learn/slh-dsa',
              moduleId: 'slh-dsa',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: SLH-DSA sign & verify',
              to: '/playground/slh-dsa',
              workshopId: 'slh-dsa',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Stateful Hash Signatures',
              to: '/learn/stateful-signatures',
              moduleId: 'stateful-signatures',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: LMS/HSS stateful signatures',
              to: '/playground/lms-hss',
              workshopId: 'lms-hss',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: OpenSSL Studio',
              to: '/playground/openssl-studio',
              workshopId: 'openssl-studio',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'KPIs reported to the board; regulatory/standards alignment maintained; crypto-agility OKRs tracked; evidence dossier kept',
      activities: [
        {
          id: 'F.4',
          title: 'Maintain Regulatory & Standards Alignment',
          decision:
            'Keep your regulation map current as deadlines and standards shift — a map built once in year one goes stale fast.',
          do: 'Keep the phase-to-regulation map current across the 2026–2035 deadline squeeze and the standards bodies that bind you.',
          output: 'Regulatory & standards alignment map',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Standards, Certification & Compliance Bodies',
              to: '/learn/standards-bodies',
              moduleId: 'standards-bodies',
            },
            {
              kind: 'reference',
              label: 'Maintain the regulatory & standards alignment map',
              to: '/compliance',
              refId: 'compliance',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: PQC Candidates & Lifecycle',
              to: '/learn/pqc-candidates',
              moduleId: 'pqc-candidates',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Foundations run as BAU; migration verification & program-closure standard applied; algorithm changes are routine',
      activities: [
        {
          id: 'F.5',
          title: 'Run Crypto-Agility as BAU',
          decision:
            'Fold crypto-agility into standing operations — an annual swap drill and continuous drift monitoring — so the next algorithm change is routine, not a re-run of the whole migration.',
          do: 'Fold the crypto-agility OKRs into standing operations — an annual algorithm-swap drill, continuous drift monitoring, and the Agility KPI tracked alongside Coverage/Trust/Inventory/Vendors — so a new algorithm recommendation becomes a routine change, not a re-run of the whole migration.',
          output: 'Crypto-agility OKR evidence, tracked as BAU',
          steps: [
            {
              kind: 'activity',
              label: 'Track the Agility KPI as a standing, recurring metric',
              to: '/business/tools/kpi-tracker',
              artifactType: 'kpi-tracker',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Let the evidence dossier lapse',
      why: "A documented decision to defer is defensible; undocumented inaction is not. Without a maintained record of risk-acceptance decisions, denied budget requests, and annual threat reassessments, there's no negligence defense if a known, unaddressed quantum risk turns into an incident.",
    },
    {
      title: 'Skip the maturity baseline (run no assessment)',
      why: 'Without the weakest-link view you over-report progress and miss the gating domain that actually constrains readiness.',
    },
  ],
}

export default TREE
