// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 07182026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p1',
  gate: {
    id: 'G1',
    criterion:
      'Scoping doc done; Priority-A inventory ≥90%; classical findings reported; continuous discovery live',
  },
  generated: '07182026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator:
        'Partial manual inventory of obvious systems (web servers, VPN); CMDB-only asset register; no continuous discovery',
      activities: [
        {
          id: '1.0',
          title: 'Risk-Driven Scoping — Decide What to Inventory First',
          decision:
            'Prioritize discovery by risk — the Tier-1 systems first — instead of scanning everything with equal priority.',
          do: 'Apply 80/20 prioritization to pick the Tier-1 systems and assign discovery priority tiers.',
          output: 'Risk-driven scoping document',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Data & Asset Sensitivity',
              to: '/learn/data-asset-sensitivity',
              moduleId: 'data-asset-sensitivity',
            },
            {
              kind: 'reference',
              label: 'Run the scoping assessment engine',
              to: '/assess',
              refId: 'assess-engine',
            },
            {
              kind: 'activity',
              label: 'Refine the scoping document with risk-driven prioritization',
              to: '/business/tools/initial-scoping',
              artifactType: 'initial-scoping',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Risk-driven scoping complete; automated discovery deployed on Priority A systems; ≥70% Tier-1 coverage; inventory is queryable; classical vulnerabilities being remediated; multiple asset data sources cross-referenced',
      activities: [
        {
          id: '1.1',
          title: 'Establish Three Parallel Inventory Tracks',
          decision:
            'Run crypto-usage, data-classification and systems/assets discovery as three parallel tracks, not one sequential sweep.',
          do: 'Stand up Track A (crypto usage), Track B (data classification), Track C (systems/assets — CMDB, ITAM, BIA cross-reference; detailed methodology in 1.4–1.5).',
          output: 'Sensitive-data classification map (Track B)',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Track A — cryptographic management modernization',
              to: '/learn/crypto-mgmt-modernization',
              moduleId: 'crypto-mgmt-modernization',
            },
            {
              kind: 'learn',
              label: 'Learn: Track B — data classification & confidentiality horizons',
              to: '/learn/data-asset-sensitivity',
              moduleId: 'data-asset-sensitivity',
            },
            {
              kind: 'activity',
              label: 'Build the sensitive-data classification map (Track B)',
              to: '/business/tools/data-at-rest-strategy',
              artifactType: 'data-at-rest-strategy',
            },
          ],
        },
        {
          id: '1.2',
          title: 'Deploy Cryptographic Discovery — Layered Approach',
          decision:
            'Layer discovery across network, code, config and runtime — a single scan type always misses real crypto usage.',
          do: 'Deploy discovery across network, code, config, runtime, and manual layers.',
          output: 'Layered discovery deployment',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: layered cryptographic discovery (CBOM)',
              to: '/learn/cbom',
              moduleId: 'cbom',
            },
            {
              kind: 'catalog',
              label: 'Browse the Migrate discovery catalog',
              to: '/migrate',
              catalogId: 'discovery',
            },
            {
              kind: 'activity',
              label: 'Run the Management-Tools Audit',
              to: '/business/tools/management-tools-audit',
              artifactType: 'management-tools-audit',
            },
          ],
        },
        {
          id: '1.3',
          title: 'Map the Cryptographic Estate',
          decision:
            'Record the full field set — algorithm, key size, protocol, owner — for every instance, not just a name and a checkbox.',
          do: 'Document algorithm, key size, protocol, library, cert, owner and vulnerability for each instance.',
          output: 'Cryptographic asset inventory',
          steps: [
            {
              kind: 'activity',
              label: 'Draw the crypto architecture diagram',
              to: '/business/tools/crypto-architecture-diagram',
              artifactType: 'crypto-architecture',
            },
            {
              kind: 'learn',
              label:
                'Learn: keys, secrets & HSM inventory — crypto you hold, not just crypto you run',
              to: '/learn/secrets-management-pqc',
              moduleId: 'secrets-management-pqc',
            },
          ],
        },
        {
          id: '1.4–1.5',
          title: 'Address Asset Discovery & Integrate Existing Data Sources',
          decision:
            'Cross-reference CMDB, ITAM, cloud and certificate data sources — a single system of record always undercounts the real estate.',
          do: 'Cross-reference CMDB, ITAM, cloud APIs, CT logs, BIA and certificate data for coverage — including OT and embedded systems, which none of those systems of record fully see.',
          output: 'Cross-referenced asset coverage',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: cross-reference CMDB / ITAM / cloud & certificate data sources',
              to: '/learn/crypto-mgmt-modernization',
              moduleId: 'crypto-mgmt-modernization',
            },
            {
              kind: 'reference',
              label: 'Reference: data-source & SBOM / CT-log standards in the Library',
              to: '/library?topic=SBOM',
              refId: 'library',
            },
            {
              kind: 'learn',
              label: 'Learn: OT & embedded systems — the hardest assets to discover',
              to: '/learn/iot-ot-pqc',
              moduleId: 'iot-ot-pqc',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        '≥90% coverage; continuous discovery in CI/CD and passive monitoring; integrated with CMDB, SBOM, BIA, and certificate management; change management integration live; crypto champions designated; alerting framework operational',
      activities: [
        {
          id: '1.6',
          title: 'Establish Continuous Discovery',
          decision:
            'Wire discovery into CI/CD and passive monitoring so it runs continuously — a one-time inventory goes stale within months.',
          do: 'Wire discovery into CI/CD and passive monitoring with quarterly rescans and tiered alerting.',
          output: 'Continuous discovery operating model',
          steps: [
            {
              kind: 'activity',
              label: 'Set up the Crypto-Vulnerability Watch',
              to: '/business/tools/crypto-vulnerability-watch',
              artifactType: 'crypto-vulnerability-watch',
            },
            {
              kind: 'learn',
              label: 'Learn: CBOM-driven continuous discovery',
              to: '/learn/cbom',
              moduleId: 'cbom',
            },
            {
              kind: 'learn',
              label:
                'Learn: what CVE-based vulnerability watch misses (side-channel, quantum progress)',
              to: '/learn/entropy-randomness',
              moduleId: 'entropy-randomness',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: finding hardcoded crypto in application code & APIs',
              to: '/learn/crypto-dev-apis',
              moduleId: 'crypto-dev-apis',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Platform Engineering & PQC',
              to: '/learn/platform-eng-pqc',
              moduleId: 'platform-eng-pqc',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Run an interview-only inventory',
      why: 'Application owners cannot reliably self-report crypto usage without automated discovery.',
    },
    {
      title: 'Keep the inventory in a spreadsheet',
      why: 'Static spreadsheets go stale within weeks without an automated, queryable refresh.',
    },
    {
      title: 'Wait for 100% completeness',
      why: 'Completeness is asymptotic; 80/20 risk-driven scoping delivers actionable results sooner.',
    },
    {
      title: 'Skip OT and embedded systems',
      why: 'The hardest systems to discover guarantee later surprises when excluded.',
    },
    {
      title: 'Trust a single discovery tool',
      why: 'No one tool covers all five discovery layers; multiple categories are required.',
    },
    {
      title: 'Rely on the CMDB alone for asset discovery',
      why: 'The CMDB is rarely complete; it systematically undercounts cloud resources, shadow IT, OT devices, and vendor-managed systems. Cross-reference the CMDB, ITAM, cloud API, CT-log, BIA and certificate data sources from Activity 1.4–1.5 or the CMDB gap becomes a migration gap.',
    },
    {
      title: 'Treat discovery as one-time',
      why: 'Discovery is a permanent capability; disbanding the team stales the CBOM within six months.',
    },
    {
      title: 'Ignore the immediate classical-crypto findings',
      why: 'Discovery surfaces weak/expired classical crypto with near-term value; ignoring it wastes the inventory and leaves the Level-2 "classical vulnerabilities being remediated" bar unmet.',
    },
  ],
}

export default TREE
