// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 09072026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p4',
  gate: {
    id: 'G4',
    criterion: 'Multi-year roadmap approved; Year 1 plan resourced',
  },
  generated: '09072026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Informal plan exists (spreadsheet, no governance); single-year horizon',
      activities: [
        {
          id: '4.1',
          title: 'Define Year-1 Starter Plan (90-Day Governance Sprint)',
          decision:
            'Nail down a concrete 90-day starting plan — leadership, a training cohort, two pilots — not just a vision statement.',
          do: 'Confirm leadership, training cohort, CBOM v1, two pilots, updated policy and baseline KPIs.',
          output: 'Year-1 starter plan',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Migration Program Management',
              to: '/learn/migration-program',
              moduleId: 'migration-program',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Multi-year roadmap approved; Year 1 plan resourced; SteerCo operational; KPI baseline set',
      activities: [
        {
          id: '4.2',
          title: 'Structure the Multi-Year Roadmap',
          decision:
            'Build a phased multi-year roadmap with a real critical path — not a wishlist of dates.',
          do: 'Define a phased 5-year plan with annual milestones and a critical path.',
          output: 'Multi-year roadmap',
          steps: [
            {
              kind: 'reference',
              label: 'See your country on the global PQC roadmap (2026–2030 deadline squeeze)',
              to: '/timeline',
              refId: 'timeline',
            },
            {
              kind: 'activity',
              label: 'Build a multi-year Roadmap',
              to: '/business/tools/roadmap-builder',
              artifactType: 'migration-roadmap',
            },
            {
              kind: 'activity',
              label: 'Cost the multi-year ask before the board sees the roadmap',
              to: '/business/tools/cost-model-explorer',
              artifactType: 'cost-model-comparison',
            },
            {
              kind: 'activity',
              label: 'Plan the roadmap stakeholder communications',
              to: '/business/tools/stakeholder-comms',
              artifactType: 'stakeholder-comms',
            },
          ],
        },
        {
          id: '4.3',
          title: 'Align to Infrastructure Refresh Cycles',
          decision:
            "Piggyback PQC work on refresh cycles that are already funded — don't ask for a separate budget line for everything.",
          do: 'Map PQC tasks onto already-funded refresh programs to embed cost avoidance.',
          output: 'Refresh-cycle alignment table',
          steps: [
            {
              kind: 'activity',
              label: 'Map PQC tasks onto funded refresh cycles',
              to: '/business/tools/refresh-cycle-alignment',
              artifactType: 'refresh-cycle-alignment',
            },
          ],
        },
        {
          id: '4.4',
          title: 'Establish PMO Structure for Scale',
          decision:
            'Stand up a real PMO — WBS, dependency map, risk register — before the program outgrows ad hoc tracking.',
          do: 'Define WBS, dependency map, critical path, resource leveling and risk register.',
          output: 'PMO operating model',
          steps: [
            {
              kind: 'activity',
              label: 'Define the 8 workstreams & RACI',
              to: '/business/tools/raci-builder',
              artifactType: 'raci-matrix',
            },
            {
              kind: 'activity',
              label: 'Baseline the program KPI pack',
              to: '/business/tools/kpi-dashboard',
              artifactType: 'kpi-dashboard',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'Quarterly roadmap reviews operational; dependency mapping maintained; refresh cycle alignment documented; vendor engagement tracked on dashboard',
      activities: [
        {
          id: '4.5–4.6',
          title: 'Manage the Roadmap as a Living Instrument & Define Milestone Gates',
          decision:
            "Review the roadmap quarterly against leading indicators and formal gate criteria — don't just check it once a year.",
          do: 'Run quarterly reviews with leading indicators and formal G0–G6 gate criteria.',
          output: 'Quarterly review process & gate criteria',
          steps: [
            {
              kind: 'reference',
              label:
                'Monitor the threat horizon — CRQC timeline signals that trigger accelerated execution',
              to: '/threats',
              refId: 'threats',
            },
            {
              kind: 'reference',
              label: 'Track gates on the Report page',
              to: '/report',
              refId: 'report',
            },
            {
              kind: 'activity',
              label: 'Track the roadmap on a quarterly cadence against gate criteria',
              to: '/business/tools/kpi-tracker',
              artifactType: 'kpi-tracker',
            },
            {
              kind: 'recurrence',
              label: 'Run the quarterly review again — L3 is reviews OPERATIONAL, not scheduled',
              to: '/business/tools/kpi-tracker',
              recurrenceOf: 'kpi-tracker',
              recurrenceQuarters: 1,
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Roadmap is a living instrument with quarterly updates; contingency triggers defined and tested; leading indicators monitored; program transitioning from migration execution to ongoing posture management',
      activities: [
        {
          id: '4.7',
          title: 'Pre-Draft the Accelerated Execution Profile',
          decision:
            'Pre-approve an accelerated execution plan now, before you need it — a CRQC-timeline surprise is the wrong moment to start drafting one.',
          do: 'Pre-approve a contingency package with triggers, compressed sequence and activation authority. By Year 4–5, plan the roadmap\'s own transition from a project (with an end date) to ongoing posture management (with no end date) — disbanding the program at "done" orphans the capability the moment the next algorithm break or deadline shift hits.',
          output: 'Accelerated Execution Profile',
          steps: [
            {
              kind: 'activity',
              label: 'Pre-draft the accelerated execution profile',
              to: '/business/tools/accelerated-execution-profile',
              artifactType: 'accelerated-execution-profile',
            },
            {
              kind: 'recurrence',
              label:
                'Re-issue the execution profile in a later quarter — L4 is a LIVING instrument, not a filed plan',
              to: '/business/tools/accelerated-execution-profile',
              recurrenceOf: 'accelerated-execution-profile',
              recurrenceQuarters: 1,
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Plan in isolation from refresh cycles',
      why: 'Ignoring funded hardware/cloud/contract cycles gets budget rejected and misses embedding opportunities.',
    },
    {
      title: 'Defer vendor engagement to Year 2',
      why: 'Vendor dependency is the longest critical path; late engagement makes the timeline vendor-constrained.',
    },
    {
      title: 'Build a roadmap with no contingencies',
      why: 'Assuming every vendor and pilot succeeds leaves no acceleration/deceleration triggers.',
    },
    {
      title: 'Stand up governance without teeth',
      why: 'A SteerCo with no binding decision or funding authority cannot govern the migration.',
    },
    {
      title: 'Treat the roadmap as a project plan, not a program',
      why: 'A project plan ends at a milestone; PQC migration must transition to ongoing posture management by Year 4–5 — disbanding at "done" orphans the capability.',
    },
  ],
}

export default TREE
