// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 09072026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'verify-close',
  gate: {
    id: 'G8',
    criterion: 'Verification complete; classical material decommissioned; closed to BAU',
  },
  generated: '09072026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator:
        'Closure discussed on milestones; no evidence standard applied; "done" is declared, not proven',
      activities: [
        {
          id: 'VC.1',
          title: 'Set the Verification Standard & Closure Plan',
          decision:
            "Adopt the evidence standard and closure record up front — decide what 'proven' means before you start declaring things done.",
          do: 'Adopt the 5-point migration-verification evidence standard and the program-closure record up front, so "done" means proven, not declared.',
          output: 'Verification standard & closure plan',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Decommissioning & Program Closure',
              to: '/learn/verification-closure',
              moduleId: 'verification-closure',
            },
            {
              kind: 'reference',
              label: 'Reference: the program closure record & 5-point evidence standard',
              to: '/business/tools/migration-verification',
              refId: 'migration-verification',
            },
            {
              kind: 'reference',
              label: 'Reference: the Executive Report — board-facing closure summary',
              to: '/report',
              refId: 'report',
            },
            {
              kind: 'reference',
              label: 'Reference: closeout attestations & applicable mandates',
              to: '/compliance',
              refId: 'compliance',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Migration verified against the 5-point evidence standard; classical key material decommissioning logged; program closure record produced',
      activities: [
        {
          id: 'VC.2',
          title: 'Assemble the Migration Evidence Dossier',
          decision:
            'Assemble real evidence — observed negotiation, negative testing, attestation — for every migrated system, not a checklist of milestones hit.',
          do: 'Prove each migrated system against the evidence standard (observed PQC negotiation, negative testing, configuration attestation) and log classical key-material decommissioning per org key-destruction standard — destruction certificates for HSM-held keys, not a verbal confirmation. Re-encrypt long-lived archives under PQC BEFORE destroying the classical keys that protect them — the sequencing matters, not just the two actions.',
          output: 'Migration-verification evidence dossier',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: decommission classical crypto & assemble evidence',
              to: '/learn/verification-closure',
              moduleId: 'verification-closure',
            },
            {
              kind: 'activity',
              label: 'Assemble the migration evidence dossier',
              to: '/business/tools/migration-verification',
              artifactType: 'migration-verification',
            },
            {
              kind: 'activity',
              label:
                'Log classical key-material decommissioning — destruction certificates, not a verbal confirmation',
              to: '/business/tools/migration-verification',
              artifactType: 'migration-verification',
            },
            {
              kind: 'activity',
              label: 'Run the closure audit-readiness checklist',
              to: '/business/tools/audit-checklist',
              artifactType: 'audit-checklist',
            },
            {
              kind: 'activity',
              label:
                'Confirm long-lived archives are re-encrypted under PQC before this system’s classical keys are destroyed',
              to: '/business/tools/data-at-rest-strategy',
              artifactType: 'data-at-rest-strategy',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'Independent verification of Tier-1 systems; crypto-agility/rollback drill evidenced; executive-sponsor sign-off; BAU handover funded',
      activities: [
        {
          id: 'VC.3',
          title: 'Independent Verification & Sign-off',
          decision:
            'Get independent verification and a funded BAU handover signed off — closure needs proof and a receiving team, not just a milestone check.',
          do: 'Independently verify Tier-1 systems, evidence the crypto-agility / rollback drill, and obtain executive-sponsor closure sign-off with a funded BAU handover.',
          output: 'Independent verification & signed closure',
          steps: [
            {
              kind: 'activity',
              label: 'Export the final CBOM as durable closure evidence',
              to: '/business/tools/crypto-cbom-builder',
              artifactType: 'crypto-cbom',
            },
            {
              kind: 'reference',
              label: 'Reference: decommissioning guidance & evidence standards',
              to: '/library?topic=800-88',
              refId: 'library',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Verification & closure run as BAU; evidence dossier continuously maintained; decommissioning and attestations folded into posture monitoring',
      activities: [
        {
          id: 'VC.4',
          title: 'Run Verification & Closure as BAU',
          decision:
            'Fold verification and decommissioning into continuous posture monitoring — closure is a permanent operating discipline, not a one-time event.',
          do: 'Fold verification, decommissioning and attestations into the continuous posture-monitoring loop so algorithm changes and re-verification are routine.',
          output: 'BAU verification & posture monitoring',
          steps: [
            {
              kind: 'activity',
              label: 'Track post-closure crypto-posture KPIs as BAU',
              to: '/business/tools/kpi-tracker',
              artifactType: 'kpi-tracker',
            },
            {
              kind: 'reference',
              label: 'Reference: monitor the algorithm-transition landscape',
              to: '/algorithms?tab=transition',
              refId: 'algorithms-transition',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Declare the migration "done" on milestones',
      why: 'Closing on milestone completion instead of verified posture — without evidence (observed negotiation, negative testing, the dossier) the migration is a belief, not a fact, and an auditor asks for proof, not milestones.',
    },
    {
      title: 'Orphan the capabilities at closure',
      why: 'Treating closure as end-of-funding rather than a funded BAU handover — CBOM, discovery and vendor governance decay within quarters without owners.',
    },
    {
      title: 'Skip classical-key decommissioning',
      why: "Leaving old classical keys and material live keeps the harvest-now-decrypt-later exposure open even after PQC is deployed — closure requires key-destruction evidence per the org's destruction standard.",
    },
  ],
}

export default TREE
