// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 09072026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p7',
  generated: '09072026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Ad-hoc inquiries to a few vendors; no structured tracking',
      activities: [
        {
          id: '7.1',
          title: 'Classify Vendor Portfolio by PQC Impact',
          decision:
            "Classify every vendor as Blocking, Enabling or Non-Critical — treating them all the same wastes effort on vendors that don't matter.",
          do: 'Categorize vendors as Strategic Blocking, Strategic Enabling or Non-Critical.',
          output: 'Vendor classification matrix',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Vendor & Supply-Chain Risk',
              to: '/learn/vendor-risk',
              moduleId: 'vendor-risk',
            },
            {
              kind: 'activity',
              label: 'Build the supply-chain matrix',
              to: '/business/tools/supply-chain-matrix',
              artifactType: 'supply-chain-matrix',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Top 10 vendors formally engaged; questionnaires sent; responses tracked; vendor criticality classification complete',
      activities: [
        {
          id: '7.2',
          title: 'Execute Vendor Engagement',
          decision:
            "Formally engage and score strategic vendors with a real questionnaire — a verbal 'they're working on it' isn't a tracked commitment.",
          do: 'Send PQC readiness questionnaires to strategic vendors and track responses.',
          output: 'Vendor questionnaire responses',
          steps: [
            {
              kind: 'reference',
              label: 'Reference: vendor FIPS/CC cert status',
              to: '/compliance?cert=A8273',
              refId: 'compliance-cert-check',
            },
            {
              kind: 'reference',
              label: 'Reference: which vendor protocols have a PQC path',
              to: '/algorithms?tab=support',
              refId: 'algorithms-protocol-matrix',
            },
            {
              kind: 'activity',
              label: 'Score vendors (Vendor Scorecard)',
              to: '/business/tools/vendor-scorecard',
              artifactType: 'vendor-scorecard',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'PQC in standard procurement language; contracts include dated commitments and remedies; bridging patterns deployed for blocked systems; vendor scorecard reported to SteerCo',
      activities: [
        {
          id: '7.3',
          title: 'Insert PQC Requirements into Procurement',
          decision:
            "Put dated PQC commitments and remedies into the contract language itself — a vendor's roadmap slide isn't binding.",
          do: 'Add PQC clauses to RFP and contract templates with dated commitments and remedies; require a product CBOM (CycloneDX format) plus a dated PQC attestation with every contract, not just a support statement.',
          output: 'Updated procurement templates',
          steps: [
            {
              kind: 'activity',
              label: 'Draft a PQC contract clause',
              to: '/business/tools/contract-clause',
              artifactType: 'contract-clause',
            },
          ],
        },
        {
          id: '7.4',
          title: 'Manage Vendor-as-Blocker Scenarios',
          decision:
            "Deploy a bridging pattern or formally accept the residual risk when a vendor blocks you — don't just wait and hope they catch up.",
          do: 'When a critical vendor cannot deliver PQC in time, deploy bridging patterns (gateway, overlay, key-wrap), run champion-challenger, escalate contractually, or accept-and-document the residual risk.',
          output: 'Bridging pattern deployments',
          steps: [
            {
              kind: 'activity',
              label: 'Deploy bridging patterns for blocked vendors',
              to: '/business/tools/deployment-playbook',
              artifactType: 'deployment-playbook',
            },
            {
              kind: 'activity',
              label:
                'Accept-and-document residual vendor risk when no bridge or alternative exists',
              to: '/business/tools/risk-register',
              artifactType: 'risk-register',
            },
          ],
        },
        {
          id: '7.5',
          title: 'Establish Ongoing Vendor Governance',
          decision:
            "Run vendor governance as a recurring cadence — this phase never closes, so a one-time review isn't enough.",
          do: 'Run the recurring vendor-governance cadence — track roadmaps, verify GA commitments, update the vendor scorecard, and report to SteerCo.',
          output: 'Vendor governance cadence',
          steps: [
            {
              kind: 'activity',
              label: 'Run the vendor-KPI / SteerCo governance cadence',
              to: '/business/tools/kpi-dashboard',
              artifactType: 'kpi-dashboard',
            },
          ],
        },
        {
          id: '7.6',
          title: 'Coordinate Counterparties You Cannot Contractually Compel',
          decision:
            "Coordinate dual-stack windows and deprecation timing with counterparties you can't compel — silently flipping a protocol breaks their integration.",
          do: 'For partners, customers and API consumers with no contractual leverage, run the coordination pattern — readiness discovery, dual-stack windows, deprecation protocol, interop test events, and API versioning.',
          output: 'Counterparty coordination plan',
          steps: [
            {
              kind: 'activity',
              label: 'Plan dual-stack windows & deprecation comms for counterparties',
              to: '/business/tools/stakeholder-comms',
              artifactType: 'stakeholder-comms',
            },
            {
              kind: 'activity',
              label: 'Record the counterparty refusal decision in the risk register',
              to: '/business/tools/risk-register',
              artifactType: 'risk-register',
            },
            {
              kind: 'recurrence',
              label:
                'Report to the SteerCo again in a later quarter — L3 is reported, not produced',
              to: '/business/tools/kpi-dashboard',
              recurrenceOf: 'kpi-dashboard',
              recurrenceQuarters: 1,
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'All strategic vendors PQC-committed with verified delivery; bridging patterns eliminated as vendor support matures; open-source dependency tracking operational; vendor governance is permanent BAU function',
      activities: [
        {
          id: '7.7',
          title: 'Cloud Shared Responsibility and the SaaS Class',
          decision:
            "Map exactly where your responsibility ends and the provider's begins — don't assume PQC migration is automatically their problem.",
          do: 'Define the provider/customer migration boundary and govern SaaS by sensitivity.',
          output: 'Cloud responsibility & SaaS governance',
          steps: [
            {
              kind: 'activity',
              label: 'Map the cloud responsibility split',
              to: '/business/tools/cloud-responsibility-matrix',
              artifactType: 'cloud-responsibility-matrix',
            },
          ],
        },
        {
          id: '7.5-vendor-governance-cycle',
          adaptationOf: '7.5',
          title: 'Operate vendor governance as a permanent function',
          decision:
            'Verify what suppliers actually delivered and keep the review running — a signed commitment is not delivered PQC.',
          do: 'Advance a reporting period and re-score the vendor portfolio: which commitments were met, which bridging patterns can now be retired, what open-source dependencies are tracked, and when the next review falls.',
          output: 'Re-scored vendor portfolio + next governance review',
          steps: [
            {
              kind: 'recurrence',
              label: 'Re-score vendors in a later quarter (permanent BAU governance)',
              to: '/business/tools/vendor-scorecard',
              recurrenceOf: 'vendor-scorecard',
              recurrenceQuarters: 1,
            },
            {
              kind: 'reference',
              label: 'Reference: supplier certification evidence behind a delivery claim',
              to: '/compliance',
              refId: 'compliance',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Start vendor engagement too late',
      why: 'Vendor dependency is the longest critical path; waiting for a complete CBOM loses a year or more.',
    },
    {
      title: 'Accept verbal commitments',
      why: 'Verbal assurances evaporate when priorities shift; written GA dates and remedies are essential.',
    },
    {
      title: 'Treat all vendors equally',
      why: 'Equal intensity wastes resources; focus on the 5–10 Strategic Blocking vendors.',
    },
    {
      title: 'Keep no bridging strategy',
      why: 'When critical vendors miss milestones, undeployable bridging patterns leave you stuck.',
    },
    {
      title: 'Ignore open-source crypto dependencies',
      why: 'OpenSSL/Bouncy Castle and language libraries need the same tracking as commercial vendors.',
    },
    {
      title: 'Delegate the risk, not just the implementation',
      why: 'The vendor owns the product, but you still own the risk to your data, operations and compliance — "the vendor will sort it out" leaves you accountable with no control.',
    },
    {
      title: 'Your top blocked vendors share one upstream crypto library',
      why: 'Vendor-diversity scorecards check for a single VENDOR failure point, not a shared fourth-party one — if five "independent" blocked vendors all depend on the same unpatched crypto library, that\'s one concentration risk wearing five faces, not five separate ones. Map upstream dependencies, not just first-party vendor names.',
    },
  ],
}

export default TREE
