// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 09072026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p0',
  gate: {
    id: 'G0',
    criterion: 'Charter, budget & QRPM approved',
  },
  generated: '09072026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Quantum risk acknowledged; no formal program',
      activities: [
        {
          id: '0.1',
          title: 'Frame the Business Case',
          decision:
            'Build the business case around HNDL/TNFL exposure and the regulatory clock — not a generic "quantum is coming" pitch.',
          do: 'Structure the executive argument around four concrete, current urgency drivers, not speculative Q-Day predictions: (1) regulatory & compliance deadlines, (2) Harvest-Now-Decrypt-Later (HNDL) exposure, (3) Trust-Now-Forge-Later (TNFL) exposure, (4) client, investor & insurer expectations.',
          output: 'Executive business case',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Business Case',
              to: '/learn/pqc-business-case',
              moduleId: 'pqc-business-case',
            },
            {
              kind: 'learn',
              label: 'Learn: Executive Quantum Impact',
              to: '/learn/exec-quantum-impact',
              moduleId: 'exec-quantum-impact',
            },
            {
              kind: 'learn',
              label: 'Learn: Compliance & Regulatory Strategy',
              to: '/learn/compliance-strategy',
              moduleId: 'compliance-strategy',
            },
            {
              kind: 'reference',
              label: 'Check the CRQC threat horizon',
              to: '/threats?view=horizon',
              refId: 'threats',
            },
            {
              kind: 'reference',
              label: 'Map the binding regulatory deadlines',
              to: '/compliance',
              refId: 'compliance',
            },
            {
              kind: 'reference',
              label:
                'Reference: the deadline classes driving urgency (EO / OMB / CNSA 2.0) — see the live timeline',
              to: '/timeline',
              refId: 'timeline',
            },
            {
              kind: 'activity',
              label: 'Quantify HNDL exposure with a CRQC scenario',
              to: '/business/tools/crqc-scenario',
              artifactType: 'crqc-scenario',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator: 'Charter approved; QRPM appointed; Year 1 budget secured',
      activities: [
        {
          id: '0.2',
          title: 'Build the Budget Structure',
          decision:
            'Ask for a phased multi-year budget backed by real cost models — not a single-year, back-of-envelope number.',
          do: 'Structure funding as a phased multi-year program aligned to existing infrastructure refresh cycles, sized from migration cost estimates and ROI.',
          output: 'Multi-year budget commitment',
          steps: [
            {
              kind: 'activity',
              label: 'Compare the six costing models before trusting a number',
              to: '/business/tools/cost-model-explorer',
              artifactType: 'cost-model-comparison',
            },
            {
              kind: 'activity',
              label: 'Model the multi-year migration budget & ROI',
              to: '/business/tools/roi-calculator',
              artifactType: 'roi-model',
            },
            {
              kind: 'activity',
              label: 'Quantify breach exposure (classical vs quantum)',
              to: '/business/tools/breach-simulator',
              artifactType: 'breach-scenario',
            },
            {
              kind: 'activity',
              label: 'Model the cost of inaction (delay vs migrate now)',
              to: '/business/tools/cost-of-inaction',
              artifactType: 'cost-of-inaction',
            },
          ],
        },
        {
          id: '0.3',
          title: 'Establish Governance Structure',
          decision:
            'Stand up real governance — Sponsor, SteerCo, QRPM and a RACI — before work starts, not after.',
          do: 'Stand up the roles (Sponsor, SteerCo, QRPM) and workstreams, the RACI, the decision cadence, and the cryptography policy / risk-appetite framing.',
          output: 'Governance structure',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Governance & Policy',
              to: '/learn/pqc-governance',
              moduleId: 'pqc-governance',
            },
            {
              kind: 'activity',
              label: 'Build the RACI matrix',
              to: '/business/tools/raci-builder',
              artifactType: 'raci-matrix',
            },
            {
              kind: 'activity',
              label: 'Draft the cryptography policy',
              to: '/business/tools/policy-generator',
              artifactType: 'policy-draft',
            },
          ],
        },
        {
          id: '0.4',
          title: 'Draft the Program Charter',
          decision:
            'Get the charter and board mandate signed with a KPI pack attached, so the board can track progress — not just approve a headline.',
          do: 'Produce the one-page charter (purpose, scope, success criteria, cadence, escalation) and secure the board mandate with the KPI pack.',
          output: 'Approved program charter & board mandate',
          steps: [
            {
              kind: 'activity',
              label: 'Produce the Program Charter',
              to: '/business/tools/program-charter',
              artifactType: 'program-charter',
            },
            {
              kind: 'activity',
              label: 'Pitch the board for the mandate',
              to: '/business/tools/board-pitch',
              artifactType: 'board-deck',
            },
            {
              kind: 'activity',
              label: 'Set the board KPI pack (Coverage/Trust/Inventory/Vendors/Agility)',
              to: '/business/tools/kpi-dashboard',
              artifactType: 'kpi-dashboard',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator: 'Multi-year budget committed; SteerCo operational; scoping assessment complete',
      activities: [
        {
          id: '0.5',
          title: 'Conduct Initial Scoping Assessment',
          decision:
            'Scope fast and narrow — the top ~20 critical systems and the vendors that constrain your timeline — rather than wait for a complete inventory.',
          do: 'Run a rapid 2–4 week scoping of the top ~20 critical systems — their cryptography, data sensitivity and confidentiality horizon, and the 5–10 timeline-constraining vendors.',
          output: 'Initial scoping assessment',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Data & Asset Sensitivity',
              to: '/learn/data-asset-sensitivity',
              moduleId: 'data-asset-sensitivity',
            },
            {
              kind: 'reference',
              label: 'Run the scoping assessment engine',
              to: '/assess',
              refId: 'assess-engine',
            },
            {
              kind: 'activity',
              label: 'Produce the scoping & asset assessment',
              to: '/business/tools/initial-scoping',
              artifactType: 'initial-scoping',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Program integrated into enterprise risk register; quantum risk reported to board quarterly alongside other strategic risks',
      activities: [
        {
          id: '0.3-board-cycle',
          adaptationOf: '0.3',
          title: 'Operate the governance cadence: recurring board reporting',
          decision:
            'Report quantum risk to the board on the same cadence as other strategic risks — a one-off briefing is not governance.',
          do: 'Advance a reporting period and take the board update again, so quantum risk is carried in the enterprise risk register with an owner, a review date and a follow-up rather than being raised once.',
          output: 'Recurring board update + enterprise-risk entry',
          steps: [
            {
              kind: 'recurrence',
              label: 'Report to the board again in a later quarter (recurring cadence)',
              to: '/business/tools/board-pitch',
              recurrenceOf: 'board-deck',
              recurrenceQuarters: 1,
            },
            {
              kind: 'reference',
              label:
                'Reference: your program report — the record the board decision is minuted against',
              to: '/report',
              refId: 'report',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Frame PQC as an innovation project',
      why: 'Treating migration as R&D instead of a governed program gets it deprioritized against operational work.',
    },
    {
      title: 'Commit only a single-year budget',
      why: 'One-year funding prevents realistic planning and talent retention over a 4–15 year program.',
    },
    {
      title: 'Leave business units off the SteerCo',
      why: 'Without business governance representation, workstream leads hit constant political resistance.',
    },
    {
      title: 'Delegate the program to vendors',
      why: 'Vendors execute on their own timelines, leaving you with no control over your migration.',
    },
    {
      title: 'Lock systems down prematurely',
      why: 'Knee-jerk restrictions burn operational goodwill without reducing HNDL risk.',
    },
  ],
}

export default TREE
