// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 09072026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p6',
  gate: {
    id: 'G6',
    criterion: 'Infrastructure upgrades scheduled; vendor commitments tracked',
  },
  generated: '09072026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Awareness of PKI/HSM/network challenges; no concrete plans',
      activities: [
        {
          id: '6.1-infra-awareness',
          adaptationOf: '6.1',
          title: 'Recognise the infrastructure constraints before planning',
          decision:
            'Understand what PQC does to PKI, HSMs and the network path before committing to any modernization plan.',
          do: 'Identify which PKI, HSM/KMS and network components the migration touches, and explain the constraint each one imposes — larger keys and signatures, hardware support, middlebox behaviour. Awareness only: no plans yet.',
          output: 'Stated infrastructure constraints',
          steps: [
            {
              kind: 'reference',
              label:
                'Reference: classical → PQC transition — what changes in keys, signatures and certificates',
              to: '/algorithms?tab=transition',
              refId: 'algorithms-transition',
            },
            {
              kind: 'reference',
              label:
                'Reference: detailed algorithm comparison — the size and performance constraints infrastructure has to absorb',
              to: '/algorithms?tab=detailed',
              refId: 'algorithms-detailed',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'HSMs inventoried with PQC status; PKI modernization plan drafted; initial middlebox testing underway',
      activities: [
        {
          id: '6.1',
          title: 'PKI Modernization',
          decision:
            'Shorten cert lifetimes and run a dual-stack CA — test every chain across your actual middleboxes before you rely on it.',
          do: 'Shorten certificate lifetimes, deploy dual-stack CA, and test chains across middleboxes.',
          output: 'PKI modernization plan',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PKI Workshop',
              to: '/learn/pki-workshop',
              moduleId: 'pki-workshop',
            },
            {
              kind: 'learn',
              label: 'Learn: Merkle Tree Certificates (a leading web-PKI candidate)',
              to: '/learn/merkle-tree-certs',
              moduleId: 'merkle-tree-certs',
            },
            {
              kind: 'workshop',
              label: 'Practice: Merkle Tree Certificates workshop',
              to: '/playground/merkle-proof',
              workshopId: 'merkle-proof',
            },
            {
              kind: 'scenario',
              label: 'Lab: enterprise PQC PKI chain (Root SLH-DSA → Int ML-DSA → Leaf)',
              to: '/playground/sbx-pki',
              scenarioId: 'pki',
            },
            {
              kind: 'activity',
              label: 'Draft the infrastructure modernization plan',
              to: '/business/tools/infra-modernization-planner',
              artifactType: 'infra-modernization-plan',
            },
          ],
          deepDive: [
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: PKI enrollment protocols',
              to: '/playground/pki-enrollment',
              workshopId: 'pki-enrollment',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: hybrid (classical + PQC) certificate chains',
              to: '/playground/hybrid-certs',
              workshopId: 'hybrid-certs',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: PKI Workshop (hands-on cert lifecycle)',
              to: '/playground/pki-workshop',
              workshopId: 'pki-workshop',
            },
          ],
        },
        {
          id: '6.2',
          title: 'HSM and KMS Modernization',
          decision:
            "Inventory every HSM's real PQC capability before upgrading — don't assume the vendor spec sheet matches your firmware version.",
          do: "Inventory HSMs by PQC capability, upgrade firmware and configure cloud KMS for PQC. Upgraded firmware re-enters FIPS validation — check the module's certificate status on the live CMVP list, not just the vendor's spec sheet, before treating it as production-ready in a FIPS-required environment.",
          output: 'HSM/KMS upgrade schedule',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: HSM & PQC Operations',
              to: '/learn/hsm-pqc',
              moduleId: 'hsm-pqc',
            },
            {
              kind: 'learn',
              label: 'Learn: KMS & PQC',
              to: '/learn/kms-pqc',
              moduleId: 'kms-pqc',
            },
            {
              kind: 'workshop',
              label: 'Practice: HSM capacity calculator',
              to: '/playground/hsm-capacity',
              workshopId: 'hsm-capacity',
            },
            {
              kind: 'workshop',
              label: 'Practice: PQC key-wrapping — bridge for HSMs not yet upgradeable',
              to: '/playground/envelope-encrypt',
              workshopId: 'envelope-encrypt',
            },
          ],
          deepDive: [
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: hardware root-of-trust (TPM)',
              to: '/playground/tpm-playground',
              workshopId: 'tpm-playground',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: Crypto-Agility Control Plane (KMIP)',
              to: '/playground/cacp-kmip',
              workshopId: 'cacp-kmip',
            },
          ],
        },
        {
          id: '6.3',
          title: 'Network Infrastructure Assessment',
          decision:
            'Test PQC handshake sizes against every production middlebox — a firewall with hardcoded buffer limits will silently drop the larger packets.',
          do: 'Test PQC handshake sizes and protocol impacts across all production middleboxes.',
          output: 'Network compatibility report',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Network Security & PQC',
              to: '/learn/network-security-pqc',
              moduleId: 'network-security-pqc',
            },
            {
              kind: 'reference',
              label: 'Reference: protocol PQC support',
              to: '/algorithms?tab=support',
              refId: 'algorithms-protocol-matrix',
            },
            {
              kind: 'workshop',
              label: 'Practice: certificate chain / handshake size',
              to: '/playground/cert-capacity',
              workshopId: 'cert-capacity',
            },
            {
              kind: 'scenario',
              label: 'Lab: A/B TLS handshake throughput (classical vs hybrid)',
              to: '/playground/sbx-ab-handshake-bench',
              scenarioId: 'ab-handshake-bench',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: API Gateways & Reverse Proxies + PQC',
              to: '/learn/web-gateway-pqc',
              moduleId: 'web-gateway-pqc',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: PQC VPN simulator',
              to: '/playground/vpn-sim',
              workshopId: 'vpn-sim',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'HSM upgrades in progress; PKI dual-stack operational; all production middleboxes tested; performance baselines established for Tier-1 systems',
      activities: [
        {
          id: '6.4',
          title: 'Performance Testing Methodology',
          decision:
            "Baseline performance and canary at low traffic before a full rollout — don't find out about a latency regression at 100% load.",
          do: 'Baseline metrics, run canary at 1–5% traffic and evaluate against SLOs.',
          output: 'Performance baseline and projections',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Testing & Validation',
              to: '/learn/pqc-testing-validation',
              moduleId: 'pqc-testing-validation',
            },
            {
              kind: 'reference',
              label: 'Reference: algorithm sizes & FIPS/CC certs',
              to: '/compliance?cert=A7285',
              refId: 'compliance-cert-check',
            },
          ],
          deepDive: [
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: TEE↔HSM trusted channel',
              to: '/playground/tee-channel',
              workshopId: 'tee-channel',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Secure Boot & PQC',
              to: '/learn/secure-boot-pqc',
              moduleId: 'secure-boot-pqc',
            },
          ],
        },
        {
          id: '6.5',
          title: 'Capacity Planning for PQC at Scale',
          decision:
            "Benchmark PQC's CPU/memory/bandwidth impact on production-class hardware — a laptop benchmark won't catch a capacity cliff at scale.",
          do: 'Estimate CPU, memory, bandwidth and storage impact; benchmark on production hardware.',
          output: 'Capacity plan',
          steps: [
            {
              kind: 'reference',
              label: 'Reference: detailed algorithm size comparison',
              to: '/algorithms?tab=detailed',
              refId: 'algorithms-detailed',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Operating Systems & PQC',
              to: '/learn/os-pqc',
              moduleId: 'os-pqc',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Infrastructure fully PQC-capable across IT estate; capacity planning validated at production scale; PKI automated with shortened lifetimes; middlebox monitoring integrated into continuous discovery',
      activities: [
        {
          id: '6.5-capacity-cycle',
          adaptationOf: '6.5',
          title: 'Operate infrastructure at production scale: capacity and monitoring',
          decision:
            'Validate capacity against real thresholds and keep measuring — a baseline taken once will not catch drift.',
          do: 'Advance a reporting period, re-run the capacity plan against the measured load, and treat any monitoring drift as a corrective action to be re-measured rather than noted.',
          output: 'Re-validated capacity plan + corrective action',
          steps: [
            {
              kind: 'recurrence',
              label:
                'Re-validate the infrastructure plan in a later quarter (production-scale capacity)',
              to: '/business/tools/infra-modernization-planner',
              recurrenceOf: 'infra-modernization-plan',
              recurrenceQuarters: 1,
            },
            {
              kind: 'workshop',
              label: 'Practice: HSM capacity — measure headroom against the threshold',
              to: '/playground/hsm-capacity',
              workshopId: 'hsm-capacity',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Treat PQC as a drop-in library swap',
      why: 'PQC changes key/handshake sizes, breaking untested network paths and TLS termination.',
    },
    {
      title: 'Ignore middleboxes on the path',
      why: 'Firewalls, IDS/IPS and WAFs have hardcoded buffers that fail with PQC-sized handshakes.',
    },
    {
      title: 'Defer HSM capability upgrades',
      why: 'Discovering HSM incompatibility late causes 12–18 month procurement delays.',
    },
    {
      title: 'Do all PKI modernization in one event',
      why: 'Changing root, intermediate and end-entity at once risks widespread outages.',
    },
    {
      title: 'Neglect capacity planning for high-volume TLS termination',
      why: 'At CDN edge and load-balancer aggregate scale, PQC handshake/bandwidth growth swamps capacity you never modelled — the outage shows up under peak load.',
    },
    {
      title: 'Issue the new PQC root and assume it is usable',
      why: 'A root distributed today still has to propagate through browser/OS/device trust-store update cycles — commonly a year or more, longer for legacy and embedded devices whose trust stores rarely update at all. Start root-distribution ceremonies early; a root sitting in your CA is not a root anything actually trusts yet.',
    },
  ],
}

export default TREE
