// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 09072026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p2',
  gate: {
    id: 'G2',
    criterion:
      'CBOM live for Layers 1–2; freshness governance enforced; protection controls applied',
  },
  generated: '09072026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Partial CBOM in spreadsheet form covering known systems; no standard format',
      activities: [
        {
          id: '2.1',
          title: 'Select CBOM Format and Tooling',
          decision:
            'Standardize on CycloneDX rather than a spreadsheet — you need something queryable, diffable and machine-verifiable.',
          do: 'Adopt CycloneDX (1.7, the current spec — cryptoProperties plus the newer Citations/provenance fields) and establish the record structure — at minimum, algorithm, key size, protocol, library and owner per entry — and tooling.',
          output: 'CycloneDX CBOM format spec',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Cryptography Bill of Materials',
              to: '/learn/cbom',
              moduleId: 'cbom',
            },
            {
              kind: 'learn',
              label: 'Learn: CBOM in Cryptographic Management',
              to: '/learn/crypto-mgmt-modernization',
              moduleId: 'crypto-mgmt-modernization',
            },
            {
              kind: 'reference',
              label: 'Reference: CycloneDX in the Library (1.7, cryptoProperties)',
              to: '/library?topic=CycloneDX',
              refId: 'library',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'CycloneDX CBOM operational for Layers 1–2; queryable; SBOM linkage established for key applications',
      activities: [
        {
          id: '2.2',
          title: 'Populate CBOM from Inventory Data',
          decision:
            'Turn the raw inventory into real CycloneDX records linked to the SBOM — not a static export nobody re-runs.',
          do: 'Transform Phase 1 inventory into enriched CycloneDX records linked to the SBOM.',
          output: 'Populated CycloneDX CBOM',
          steps: [
            {
              kind: 'learn',
              label:
                'Learn: CBOM population — six-step transformation (import → enrich → SBOM link → certs → classify → vendor flags)',
              to: '/learn/cbom',
              moduleId: 'cbom',
            },
            {
              kind: 'activity',
              label: 'Build a CycloneDX CBOM',
              to: '/business/tools/crypto-cbom-builder',
              artifactType: 'crypto-cbom',
            },
            {
              kind: 'catalog',
              label: 'Export your CBOM as CycloneDX from the Migrate workbench',
              to: '/migrate',
              catalogId: 'cyclonedx-export',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: enriching the CBOM from code-level crypto API calls',
              to: '/learn/crypto-dev-apis',
              moduleId: 'crypto-dev-apis',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'CBOM covers Layers 1–3; integrated into CI/CD; freshness governance enforced; change management integration live',
      activities: [
        {
          id: '2.3',
          title: 'Integrate CBOM into Operational Processes',
          decision:
            'Embed the CBOM into CI/CD and change management so it updates itself — a manually-maintained CBOM decays fast.',
          do: 'Embed CBOM governance into CI/CD, change management, vendor onboarding and audit.',
          steps: [
            {
              kind: 'activity',
              label: 'Wire CBOM freshness into CI/CD drift checks',
              to: '/business/tools/crypto-vulnerability-watch',
              artifactType: 'crypto-vulnerability-watch',
            },
          ],
        },
        {
          id: '2.4–2.5',
          title: 'CBOM Freshness Governance & Securing Program Artifacts',
          decision:
            "Treat the CBOM as sensitive — classify it, restrict access, log queries — it's effectively an attacker's shopping list.",
          do: 'Enforce refresh triggers and protect the CBOM with classification and access control; sign/attest the CBOM so "machine-verifiable" includes provenance, not just structure.',
          output: 'CBOM governance & protection policy',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: secure the CBOM & make it machine-verifiable',
              to: '/learn/cbom',
              moduleId: 'cbom',
            },
            {
              kind: 'learn',
              label:
                'Learn: involve the SOC — posture-registry integration and CBOM exfiltration monitoring',
              to: '/learn/soc-implementation-pqc',
              moduleId: 'soc-implementation-pqc',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'CBOM is a real-time operational asset; auto-updated on deployment; Layer 4 gaps systematically managed through vendor governance; CBOM drives automated compliance reporting',
      activities: [
        {
          id: '2.3-cbom-refresh',
          adaptationOf: '2.3',
          title: 'Operate the CBOM: refreshed on deployment',
          decision:
            'A CBOM is a live operational asset — if it is not refreshed when something ships, it is documentation, not inventory.',
          do: 'Advance a reporting period, re-issue the CBOM after a deployment or vendor change, and report its freshness plus any supplier evidence still unresolved.',
          output: 'Refreshed CBOM + freshness and supplier-gap report',
          steps: [
            {
              kind: 'recurrence',
              label: 'Re-issue the CBOM in a later quarter (auto-update on deployment)',
              to: '/business/tools/crypto-cbom-builder',
              recurrenceOf: 'crypto-cbom',
              recurrenceQuarters: 1,
            },
            {
              kind: 'reference',
              label: 'Reference: the deployment/vendor changes the refresh must account for',
              to: '/migrate',
              refId: 'migrate',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Insist on 100% CBOM coverage',
      why: 'Layer 4 is never fully visible; perfection blocks progress instead of managing gaps via vendor governance.',
    },
    {
      title: 'Keep the CBOM as a static document',
      why: 'A PDF/spreadsheet CBOM never updated is operationally useless; it must be live and queryable.',
    },
    {
      title: 'Ignore the SBOM↔CBOM linkage',
      why: 'CBOM entries without SBOM context miss dependency chains across shared libraries.',
    },
  ],
}

export default TREE
