// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-landing-counts.mjs from pqc_complete_algorithm_reference_08312026.csv / timeline_09072026_r3.csv / library_09072026_r16.csv — DO NOT EDIT BY HAND.
// Edit the source CSVs and re-run `npm run gen:landing-counts` (runs in prebuild).
// These seed LandingView's hero-counter INITIAL state only — see the script's
// own docstring for why they are estimates, not exact counts, and why that's fine.

export const ALGORITHM_COUNT_ESTIMATE = 127
export const TIMELINE_EVENT_COUNT_ESTIMATE = 264
export const LIBRARY_COUNT_ESTIMATE = 1028
