// SPDX-License-Identifier: GPL-3.0-only
// Generated by scripts/sync-sandbox-scenarios.ts — do not edit by hand.
// Source: pqctoday-sandbox/ui/src/data/scenarios.ts
// Regenerate with: npm run sync:sandbox

export type SandboxTrackId = 'infrastructure' | 'web' | 'applications' | 'quantum'
export type SandboxDifficulty = 'beginner' | 'intermediate' | 'advanced'

export interface SandboxScenario {
  id: string
  title: string
  emoji: string
  useCase: string
  algorithms: string[]
  difficulty: SandboxDifficulty
  trackId: SandboxTrackId
  tool: { name: string; url: string }
}

export interface SandboxTrack {
  id: string
  label: string
  subtitle: string
  difficulty: string
}

export const SANDBOX_SCENARIOS: SandboxScenario[] = [
  {
    id: 'pki',
    title: 'Enterprise PKI Chains',
    emoji: '🏛️',
    useCase:
      'Build a hierarchical PQC Certificate Authority — Root CA → Intermediate CA → Leaf — using Easy-RSA PQC backed by ML-DSA-65 keys in SoftHSMv3.',
    algorithms: ['ML-DSA-65', 'X.509'],
    difficulty: 'beginner',
    trackId: 'infrastructure',
    tool: {
      name: 'Easy-RSA PQC',
      url: 'https://github.com/wtfloris/easy-rsa-pqc',
    },
  },
  {
    id: 'vpn',
    title: 'Quantum-Resistant VPN',
    emoji: '🛡️',
    useCase:
      'Secure site-to-site IPsec routing hidden behind SoftHSMv3 IKEv2 Key Exchanges, contrasting classical Diffie-Hellman vulnerability against post-quantum encapsulation.',
    algorithms: ['ML-KEM', 'IKEv2'],
    difficulty: 'intermediate',
    trackId: 'infrastructure',
    tool: {
      name: 'strongSwan 5.9.14',
      url: 'https://www.strongswan.org',
    },
  },
  {
    id: 'browser-tls',
    title: 'Browser ML-KEM Handshake',
    emoji: '🌐',
    useCase:
      "Drive headless Chromium to connect to the container's nginx TLS endpoint and compare the network footprint of a standard TLS handshake vs one utilizing ML-KEM / ML-DSA.",
    algorithms: ['X25519MLKEM768', 'Chromium'],
    difficulty: 'intermediate',
    trackId: 'web',
    tool: {
      name: 'Playwright + Chromium',
      url: 'https://playwright.dev',
    },
  },
  {
    id: 'smime',
    title: 'Secure Email (S/MIME)',
    emoji: '📧',
    useCase:
      'Compare legacy RSA-2048 S/MIME encryption sequences against open-source ML-DSA & ML-KEM cryptographic integration protecting long-lived email archives.',
    algorithms: ['ML-DSA-65', 'ML-KEM-768'],
    difficulty: 'intermediate',
    trackId: 'infrastructure',
    tool: {
      name: 'OpenSSL 3.6.2 smime',
      url: 'https://github.com/openssl/openssl',
    },
  },
  {
    id: 'pqcflow',
    title: 'PQC Network Traffic Analysis',
    emoji: '📡',
    useCase:
      'Capture live TLS/SSH/QUIC/IKE traffic and run pqc-flow (CipherIQ) to identify which flows are quantum-safe (ML-KEM, sntrup761) vs classical-at-risk (X25519, RSA) — the zero-disruption first step of any PQC network migration.',
    algorithms: ['PCAP'],
    difficulty: 'intermediate',
    trackId: 'web',
    tool: {
      name: 'pqc-flow',
      url: 'https://github.com/CipherIQ/pqc-flow',
    },
  },
  {
    id: 'osslsigncode',
    title: 'Code Signing (osslsigncode)',
    emoji: '🔏',
    useCase:
      'Sign Windows PE binaries using osslsigncode with classical RSA vs post-quantum ML-DSA-65, demonstrating the supply-chain implications of harvest-now-decrypt-later on software distribution.',
    algorithms: ['ML-DSA-65', 'PE/Authenticode'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: {
      name: 'osslsigncode',
      url: 'https://github.com/mtrojnar/osslsigncode',
    },
  },
  {
    id: 'firmware-hss',
    title: 'Firmware Verification (HSS)',
    emoji: '💾',
    useCase:
      'Secure IoT endpoint firmware updates using NIST SP 800-208 Stateful Hash-Based Signatures (HSS/LMS) parsed natively through the SoftHSMv3 PKCS#11 provider in Verify-Only mode.',
    algorithms: ['HSS / LMS', 'Stateful Signature'],
    difficulty: 'advanced',
    trackId: 'applications',
    tool: {
      name: 'OpenSSL 3.6.2 provider',
      url: 'https://github.com/openssl/openssl',
    },
  },
  {
    id: 'stepca',
    title: 'Automated CA (Step-CA)',
    emoji: '🪜',
    useCase:
      'Deploy Smallstep step-ca with PQC-enabled certificate issuance, contrasting classical RSA ACME workflows against post-quantum ML-DSA-65 automated certificate management.',
    algorithms: ['ML-DSA-65', 'ACME'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: {
      name: 'step-ca',
      url: 'https://github.com/smallstep/certificates',
    },
  },
  {
    id: 'besu',
    title: 'Blockchain Node (Hyperledger Besu)',
    emoji: '⛓️',
    useCase:
      'Harden Hyperledger Besu node identity and transaction signing against quantum adversaries by migrating from secp256k1 ECDSA to ML-DSA-65 signatures.',
    algorithms: ['ML-DSA-65', 'EVM'],
    difficulty: 'advanced',
    trackId: 'applications',
    tool: {
      name: 'Hyperledger Besu',
      url: 'https://besu.hyperledger.org',
    },
  },
  {
    id: 'algorand',
    title: 'Algorand State Proofs',
    emoji: '🔷',
    useCase:
      "Demonstrate Algorand's native state proof mechanism using Falcon-1024 lattice signatures, the first production blockchain with built-in post-quantum cryptography.",
    algorithms: ['Falcon-1024', 'State Proof'],
    difficulty: 'advanced',
    trackId: 'applications',
    tool: {
      name: 'Algorand go-algorand',
      url: 'https://github.com/algorand/go-algorand',
    },
  },
  {
    id: 'database-postgres',
    title: 'PostgreSQL TLS Hardening',
    emoji: '🐘',
    useCase:
      'Migrate PostgreSQL client-server TLS connections from classical ECDHE to ML-KEM-768, protecting database traffic from harvest-now-decrypt-later attacks on sensitive data at rest.',
    algorithms: ['ML-KEM-768', 'PostgreSQL'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: {
      name: 'PostgreSQL',
      url: 'https://www.postgresql.org',
    },
  },
  {
    id: 'tls',
    title: 'OpenSSL TLS 1.3',
    emoji: '🔐',
    useCase:
      'Execute raw OpenSSL TLS 1.3 handshakes comparing X25519 ECDHE against X25519MLKEM768 hybrid key exchange, with full PKCS#11 spy telemetry from SoftHSMv3.',
    algorithms: ['ML-KEM-768', 'TLS 1.3'],
    difficulty: 'beginner',
    trackId: 'web',
    tool: {
      name: 'OpenSSL',
      url: 'https://github.com/openssl/openssl',
    },
  },
  {
    id: 'ssh',
    title: 'SSH PQC Key Exchange',
    emoji: '💻',
    useCase:
      'Compare classical Ed25519 SSH key exchange against the hybrid sntrup761x25519 post-quantum KEX already shipping in OpenSSH — one of the most widely deployed PQC protections today.',
    algorithms: ['sntrup761', 'OpenSSH'],
    difficulty: 'beginner',
    trackId: 'web',
    tool: {
      name: 'OpenSSH OQS',
      url: 'https://github.com/open-quantum-safe/openssh',
    },
  },
  {
    id: 'cert-validation',
    title: 'Certificate Chain Validation',
    emoji: '✅',
    useCase:
      'Verify ML-DSA-65 certificate chains end-to-end — from Root CA through Intermediate to Leaf — validating that PQC signatures are correctly chained and parseable by OpenSSL.',
    algorithms: ['ML-DSA-65', 'X.509 Chain'],
    difficulty: 'beginner',
    trackId: 'infrastructure',
    tool: {
      name: 'OpenSSL',
      url: 'https://github.com/openssl/openssl',
    },
  },
  {
    id: 'migration-impact',
    title: 'Migration Impact Analysis',
    emoji: '📊',
    useCase:
      'Measure the real-world performance impact of migrating from classical to hybrid to pure PQC — handshake latency, certificate sizes, and bandwidth expansion across all three modes.',
    algorithms: ['Classical → PQC'],
    difficulty: 'intermediate',
    trackId: 'web',
    tool: {
      name: 'OpenSSL + nginx',
      url: 'https://github.com/openssl/openssl',
    },
  },
  {
    id: 'cloud-kms',
    title: 'Cloud KMS Key Wrapping',
    emoji: '🔑',
    useCase:
      'Demonstrate SoftHSMv3 ML-KEM master key wrapping — the pattern used by cloud KMS services (AWS, Azure, GCP) to protect data encryption keys with quantum-safe key encapsulation.',
    algorithms: ['ML-KEM-768', 'AES-256-KW'],
    difficulty: 'beginner',
    trackId: 'infrastructure',
    tool: {
      name: 'SoftHSMv3',
      url: 'https://github.com/pqctoday/pqctoday-hsm',
    },
  },
  {
    id: 'dnssec',
    title: 'DNSSEC Zone Signing',
    emoji: '🌍',
    useCase:
      'Sign DNS zones with ML-DSA-65 using ldnsutils, comparing classical RSA DNSSEC signatures against post-quantum zone signing for domain integrity.',
    algorithms: ['ML-DSA-65', 'DNSSEC'],
    difficulty: 'intermediate',
    trackId: 'web',
    tool: {
      name: 'ldnsutils',
      url: 'https://nlnetlabs.nl/projects/ldns/',
    },
  },
  {
    id: 'crypto-discovery',
    title: 'Crypto Discovery & CBOM',
    emoji: '🔍',
    useCase:
      'Scan the sandbox infrastructure with testssl.sh, ssh-audit, and Syft to generate a complete Cryptographic Bill of Materials (CBOM) — the essential first step of any PQC migration.',
    algorithms: ['testssl.sh'],
    difficulty: 'advanced',
    trackId: 'quantum',
    tool: {
      name: 'testssl.sh + ssh-audit + Syft',
      url: 'https://testssl.sh',
    },
  },
  {
    id: 'qkdsim',
    title: 'QKD Simulation (BB84)',
    emoji: '🔬',
    useCase:
      'Simulate a two-node BB84 Quantum Key Distribution protocol using ns-3 and QKDNetSim — observe key rates, quantum bit error rates, and entanglement metrics.',
    algorithms: ['BB84', 'ns-3'],
    difficulty: 'advanced',
    trackId: 'quantum',
    tool: {
      name: 'ns-3 + QKDNetSim',
      url: 'https://github.com/nicovell3/qkdnetsim',
    },
  },
  {
    id: 'sequence',
    title: 'Quantum Repeater Networks',
    emoji: '🌌',
    useCase:
      'Simulate quantum repeater networks using SeQUeNCe (Argonne National Lab) — model entanglement distribution, memory decoherence, and long-distance quantum key delivery.',
    algorithms: ['SeQUeNCe', 'Entanglement'],
    difficulty: 'advanced',
    trackId: 'quantum',
    tool: {
      name: 'SeQUeNCe',
      url: 'https://github.com/sequence-toolbox/SeQUeNCe',
    },
  },
  {
    id: 'openqkd',
    title: 'Hybrid QKD + PQC',
    emoji: '🔗',
    useCase:
      'Integrate QKD-derived keys with PQC algorithms using HKDF key derivation — the recommended hybrid approach for defense-in-depth quantum security.',
    algorithms: ['QKD+PQC', 'HKDF'],
    difficulty: 'advanced',
    trackId: 'quantum',
    tool: {
      name: 'OpenQKDNetwork',
      url: 'https://github.com/Open-QKD-Network/cqptoolkit',
    },
  },
  {
    id: 'sequoia',
    title: 'PGP Code Signing (Sequoia)',
    emoji: '🦅',
    useCase:
      'Use Sequoia PGP to sign and verify artifacts with ML-KEM-1024 + Curve25519 hybrid keys — demonstrating post-quantum OpenPGP for software supply chain integrity.',
    algorithms: ['ML-KEM-1024', 'OpenPGP'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: {
      name: 'Sequoia PGP',
      url: 'https://sequoia-pgp.org',
    },
  },
  {
    id: 'web3',
    title: 'Ethereum Harvest Risk',
    emoji: '💎',
    useCase:
      'Demonstrate the quantum harvest risk to Ethereum — derive secp256k1 keys, sign transactions, and show how public transaction history exposes private keys to a future CRQC.',
    algorithms: ['HNDL'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: {
      name: 'Geth',
      url: 'https://geth.ethereum.org',
    },
  },
  {
    id: 'cosmian-kms',
    title: 'Cosmian KMS (KMIP 2.1)',
    emoji: '🏢',
    useCase:
      'Operate Cosmian KMS with KMIP 2.1 protocol to manage PQC key lifecycle — generation, wrapping, rotation, and destruction using ML-DSA and ML-KEM algorithms.',
    algorithms: ['ML-DSA/ML-KEM', 'KMIP'],
    difficulty: 'advanced',
    trackId: 'infrastructure',
    tool: {
      name: 'Cosmian KMS',
      url: 'https://github.com/Cosmian/kms',
    },
  },
  {
    id: 'sops',
    title: 'GitOps Secrets (SOPS)',
    emoji: '🗝️',
    useCase:
      'Encrypt GitOps secrets with SOPS + age using post-quantum key encapsulation, protecting infrastructure-as-code secrets from harvest-now-decrypt-later attacks.',
    algorithms: ['age PQC', 'SOPS'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: {
      name: 'SOPS + age',
      url: 'https://github.com/getsops/sops',
    },
  },
  {
    id: 'hybrid-certs',
    title: 'Hybrid Certificate Formats',
    emoji: '📜',
    useCase:
      'Generate and compare all 6 hybrid X.509 certificate formats — Pure ML-DSA, Pure SLH-DSA, Composite, Alt-Sig/Catalyst, Related Certificates, and Chameleon — measuring DER sizes, keygen times, and backward compatibility.',
    algorithms: ['6 Formats', 'X.509'],
    difficulty: 'advanced',
    trackId: 'infrastructure',
    tool: {
      name: 'OpenSSL 3.6.2 + pkcs11-provider + SoftHSMv3',
      url: 'https://github.com/openssl/openssl',
    },
  },
  {
    id: 'haproxy',
    title: 'Enterprise Edge Load-Balancing',
    emoji: '⚖️',
    useCase:
      'Deploy HAProxy configured with hybrid ML-KEM/ECDHE bindings to measure Post-Quantum TLS handshake performance under heavy concurrent edge load.',
    algorithms: ['ML-KEM-768'],
    difficulty: 'advanced',
    trackId: 'web',
    tool: {
      name: 'HAProxy',
      url: 'https://haproxy.org',
    },
  },
  {
    id: 'chronyd',
    title: 'Micro-Packet Timing Integrity',
    emoji: '⏱️',
    useCase:
      'Analyze the devastating consequences of injecting massive Lattice (ML-DSA) signatures into strictly constrained UDP-packet structures (NTS) inside Chronyd.',
    algorithms: ['ML-DSA-65'],
    difficulty: 'advanced',
    trackId: 'web',
    tool: {
      name: 'Chronyd',
      url: 'https://chrony.tuxfamily.org',
    },
  },
  {
    id: 'wireguard',
    title: 'Modern Transport Tunnels',
    emoji: '🚇',
    useCase:
      'Deploy userspace Wireguard (wireguard-go) wrapped in a PQC hybrid layer to protect tunnel establishment against "Harvest Now, Decrypt Later" capabilities.',
    algorithms: ['ML-KEM-768'],
    difficulty: 'intermediate',
    trackId: 'infrastructure',
    tool: {
      name: 'WireGuard-Go',
      url: 'https://wireguard.com',
    },
  },
  {
    id: 'api-security-jwt',
    title: 'Post-Quantum JWT Identity Constraints',
    emoji: '🛂',
    useCase:
      'Deploy native Post-Quantum JSON Web Tokens (JWTs) using ML-DSA signatures and measure the devastating impact to HTTP request header boundaries (Max Header Size: 4KB / 8KB).',
    algorithms: ['ML-DSA-65'],
    difficulty: 'advanced',
    trackId: 'applications',
    tool: {
      name: 'PyJWT',
      url: 'https://pyjwt.readthedocs.io/',
    },
  },
  {
    id: 'iot-mqtt',
    title: 'Lightweight MQTT Telemetry',
    emoji: '📡',
    useCase:
      'Measure the compute execution burden of hybridizing IoT device metrics via MQTT protocol layers protected by ML-KEM encapsulation.',
    algorithms: ['ML-KEM-768'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: {
      name: 'Eclipse Mosquitto',
      url: 'https://mosquitto.org/',
    },
  },
  {
    id: 'secrets-vault',
    title: 'Zero-Trust Secrets Transit',
    emoji: '🔐',
    useCase:
      'Abstracted HashiCorp Vault transit simulations designed to test symmetric AES secrets dynamically shielded by an ML-KEM KEM boundary prior to database storage.',
    algorithms: ['ML-KEM-768', 'OpenBao'],
    difficulty: 'intermediate',
    trackId: 'infrastructure',
    tool: {
      name: 'HashiCorp Vault',
      url: 'https://www.vaultproject.io/',
    },
  },
]

export const SANDBOX_TRACKS: SandboxTrack[] = [
  {
    id: 'infrastructure',
    label: 'Cryptographic Infrastructure',
    subtitle: 'PKI, HashiCorp Vault transit, Wireguard VPNs, and foundational key stacks',
    difficulty: 'Beginner → Intermediate',
  },
  {
    id: 'web',
    label: 'Web & Network Security',
    subtitle: 'HAProxy edge-termination, NTP protocols (Chronyd), TLS migrations, and SSH',
    difficulty: 'Intermediate',
  },
  {
    id: 'applications',
    label: 'Application Security',
    subtitle: 'Microservice auth (JWT), IoT Telemetry (MQTT), and decentralized ledger bounds',
    difficulty: 'Intermediate → Advanced',
  },
  {
    id: 'quantum',
    label: 'Quantum & Discovery',
    subtitle: 'QKD simulation, quantum networks, and cryptographic inventory',
    difficulty: 'Advanced',
  },
]
