// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-timeline-facts.mjs from timeline_09072026_r3.csv — DO NOT EDIT BY HAND.
// Edit the timeline CSV and re-run `npm run gen:timeline-facts` (runs in prebuild).
// Single source of truth: the timeline reference CSV.

/** Each country's canonical PQC migration deadline — the row tagged
 *  `is_sim_deadline=true` in the timeline CSV. Untagged countries fall back to
 *  the Q-Day anchor in moscaClock. */
export const TIMELINE_COUNTRY_DEADLINE_YEAR: Record<string, number> = {
  AU: 2030, // Legacy Asymmetric Crypto Disallowed — Full PQC Transition
  CA: 2031, // High Priority Systems Complete
  DE: 2030, // Critical Applications PQC — Hybrid No Longer Required
  EU: 2035, // Full EU PQC Transition
  FR: 2027, // PQC Qualification Requirement
  IN: 2027, // CII PQC Foundations Deadline
  JP: 2035, // Government PQC Transition Deadline
  KR: 2035, // Full PQC Roadmap Complete
  UK: 2035, // Full PQC Compliance
  US: 2030, // Key-Establishment Migration Deadline (EO June 22 2026)
}

/** The same canonical deadlines keyed by full country NAME (matches the
 *  assessment's `country` field). This is the single source the assessment and
 *  the report read — it replaced the former hand-coded COUNTRY_PLANNING_HORIZON,
 *  so Assess/Report now agree with the Timeline and the Simulation. Countries
 *  without a tagged CSV deadline are omitted and fall back via the consumer's
 *  EU-member / Q-Day logic. */
export const TIMELINE_COUNTRY_DEADLINE_BY_NAME: Record<string, number> = {
  Australia: 2030, // Legacy Asymmetric Crypto Disallowed — Full PQC Transition
  Canada: 2031, // High Priority Systems Complete
  'European Union': 2035, // Full EU PQC Transition
  France: 2027, // PQC Qualification Requirement
  Germany: 2030, // Critical Applications PQC — Hybrid No Longer Required
  India: 2027, // CII PQC Foundations Deadline
  Japan: 2035, // Government PQC Transition Deadline
  'South Korea': 2035, // Full PQC Roadmap Complete
  'United Kingdom': 2035, // Full PQC Compliance
  'United States': 2030, // Key-Establishment Migration Deadline (EO June 22 2026)
}

export type DeadlineMandate = 'HARD' | 'SOFT' | 'DRAFT' | 'NONE'

/** Whether each country's canonical deadline is a binding legal mandate (`HARD` —
 *  law, regulation, executive order, binding directive) or soft guidance / roadmap /
 *  strategy (`SOFT`), from the timeline CSV `mandate_type` column. Lets the UI label
 *  "regulatory deadline" vs "guidance target" instead of presenting every government
 *  date as binding. Keyed by sim code and by full country name. */
export const TIMELINE_COUNTRY_DEADLINE_MANDATE: Record<string, DeadlineMandate> = {
  AU: 'HARD',
  CA: 'HARD',
  DE: 'SOFT',
  EU: 'SOFT',
  FR: 'SOFT',
  IN: 'HARD',
  JP: 'SOFT',
  KR: 'SOFT',
  UK: 'SOFT',
  US: 'HARD',
}

export const TIMELINE_COUNTRY_DEADLINE_MANDATE_BY_NAME: Record<string, DeadlineMandate> = {
  Australia: 'HARD',
  Canada: 'HARD',
  'European Union': 'SOFT',
  France: 'SOFT',
  Germany: 'SOFT',
  India: 'HARD',
  Japan: 'SOFT',
  'South Korea': 'SOFT',
  'United Kingdom': 'SOFT',
  'United States': 'HARD',
}

/** Per-country scenario milestone years, from rows tagged `sim_milestone` in the
 *  timeline CSV (e.g. 'hndl-critical', 'tnfl-critical', 'governance'). Powers the
 *  scenario-configurable simulation; untagged milestones (general-asset, governance)
 *  are derived in scenarioConfig. */
export const TIMELINE_COUNTRY_MILESTONES: Record<string, Partial<Record<string, number>>> = {
  US: { 'hndl-critical': 2030, 'tnfl-critical': 2031 },
}
