// SPDX-License-Identifier: GPL-3.0-only
import {
  mergeEnrichmentFiles,
  hasSubstantiveEnrichment,
  type EnrichmentLookup,
  type LibraryEnrichment,
} from './libraryEnrichmentData'
import { libraryData } from './libraryData'

export type { LibraryEnrichment, EnrichmentLookup }
export { hasSubstantiveEnrichment }

/**
 * Maps library downloadUrl → referenceId for cross-linking timeline events to library records.
 * Used by UI components to show "Also in Library →" badges when a timeline SourceUrl
 * matches a library document.
 */
export const timelineToLibraryRef: Record<string, string> = Object.fromEntries(
  libraryData.filter((item) => item.downloadUrl).map((item) => [item.downloadUrl, item.referenceId])
)

function loadTimelineEnrichments(): EnrichmentLookup {
  const modules = import.meta.glob('./doc-enrichments/timeline_doc_enrichments_*.md', {
    query: '?raw',
    import: 'default',
    eager: true,
  }) as Record<string, string>
  return mergeEnrichmentFiles(modules)
}

export const timelineEnrichments: EnrichmentLookup = loadTimelineEnrichments()

/**
 * Build the enrichment lookup key for a timeline document row.
 * Matches the key format generated by the enrichment script:
 * "{countryName}:{org} — {title}"
 */
export function getTimelineEnrichmentKey(countryName: string, org: string, title: string): string {
  return `${countryName}:${org} — ${title}`
}
