// SPDX-License-Identifier: GPL-3.0-only
import {
  parseEnrichmentMarkdown,
  hasSubstantiveEnrichment,
  type EnrichmentLookup,
  type LibraryEnrichment,
} from './libraryEnrichmentData'

export type { LibraryEnrichment, EnrichmentLookup }
export { hasSubstantiveEnrichment }

function loadTimelineEnrichments(): EnrichmentLookup {
  const modules = import.meta.glob('./doc-enrichments/timeline_doc_enrichments_*.md', {
    query: '?raw',
    import: 'default',
    eager: true,
  }) as Record<string, string>

  const paths = Object.keys(modules)
  if (paths.length === 0) return {}

  // Sort by embedded MMDDYYYY date, then by revision descending (latest _rN wins on same date)
  const withDates = paths.map((p) => {
    const match = p.match(/(\d{2})(\d{2})(\d{4})(?:_r(\d+))?\.md$/)
    if (!match) return { path: p, date: 0, revision: 0 }
    const [, mm, dd, yyyy, rev] = match
    return { path: p, date: parseInt(yyyy + mm + dd), revision: rev ? parseInt(rev) : 0 }
  })
  withDates.sort((a, b) => {
    const dateDiff = b.date - a.date
    return dateDiff !== 0 ? dateDiff : b.revision - a.revision
  })

  const raw = modules[withDates[0].path]
  if (!raw) return {}

  return parseEnrichmentMarkdown(raw)
}

export const timelineEnrichments: EnrichmentLookup = loadTimelineEnrichments()

/**
 * Build the enrichment lookup key for a timeline document row.
 * Matches the key format generated by the enrichment script:
 * "{countryName}:{org} — {title}"
 */
export function getTimelineEnrichmentKey(countryName: string, org: string, title: string): string {
  return `${countryName}:${org} — ${title}`
}
